In [11]:
import tensorflow as tf
import numpy as np

In [12]:
tf.__version__

'2.4.1'

In [13]:
tf.__name__

'tensorflow'

In [14]:
np.__name__

'numpy'

# [NumPy Compatibility](https://www.tensorflow.org/tutorials/customization/basics#numpy_compatibility)

> Converting between a TensorFlow tf.Tensors and a NumPy ndarray is easy:<br>
> * TensorFlow operations automatically convert NumPy ndarrays to Tensors.<br>
> * NumPy operations automatically convert Tensors to NumPy ndarrays.<br>
> 
> Tensors are explicitly converted to NumPy ndarrays using their .numpy() method. These conversions are typically cheap since the array and tf.Tensor share the underlying memory representation, if possible.<br><br> However, sharing the underlying representation isn't always possible since the tf.Tensor may be hosted in GPU memory while NumPy arrays are always backed by host memory, and the conversion involves a copy from GPU to host memory.
> ```
> import numpy as np
> ndarray = np.ones([3, 3])
> 
> print("TensorFlow operations convert numpy arrays to Tensors automatically")
> tensor = tf.multiply(ndarray, 42)
> print(tensor)
> 
> print("And NumPy operations convert Tensors to numpy arrays automatically")
> print(np.add(tensor, 1))
> 
> print("The .numpy() method explicitly converts a Tensor to a numpy array")
> print(tensor.numpy())
> ```

## Numpy to Tensor

It is automatic.

In [5]:
tf.constant(np.arange(6).reshape(2,3))

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

##  [tf.convert_to_tensor](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)

```
tf.convert_to_tensor(
    value, dtype=None, dtype_hint=None, name=None
)
```

In [10]:
# Same with tf.constant([[1,2,3],[4,5,6]], dtype=np.float16)
tf.convert_to_tensor([[1,2,3],[4,5,6]], dtype=np.float16) # np.dtype is compatible

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

## Tensor to Numpy

Use ```.numpy()``` method of tensors.

In [7]:
a = tf.constant(np.random.rand(3,4))
print(f"TF:\n{str(a)}\n\nTF.numpy():\n{a.numpy()}")

TF:
tf.Tensor(
[[0.59714963 0.90234098 0.12215724 0.61160119]
 [0.71039645 0.42370418 0.16797831 0.47807252]
 [0.60772922 0.75861112 0.58765084 0.63336087]], shape=(3, 4), dtype=float64)

TF.numpy():
[[0.59714963 0.90234098 0.12215724 0.61160119]
 [0.71039645 0.42370418 0.16797831 0.47807252]
 [0.60772922 0.75861112 0.58765084 0.63336087]]
