In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

# square

Element-wise square which is ```axis=-1```.

* [tf.math.square](https://www.tensorflow.org/api_docs/python/tf/math/square)

> ```
> tf.math.square(
>    x, name=None
>)
> ```

In [3]:
x: tf.Tensor = tf.constant(
    np.arange(3*2*2).reshape((3,2,2)), 
    dtype=np.float32
)
x

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 0.,  1.],
        [ 2.,  3.]],

       [[ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.]]], dtype=float32)>

In [5]:
tf.math.square(x)

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[  0.,   1.],
        [  4.,   9.]],

       [[ 16.,  25.],
        [ 36.,  49.]],

       [[ 64.,  81.],
        [100., 121.]]], dtype=float32)>

### square of subtract

Element-wise subtract and square

In [9]:
x: tf.Tensor = tf.constant(
    np.arange(1, 3*2*2+1).reshape((3,2,2)), 
    dtype=np.float32
)
x

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>

In [10]:
y = tf.constant(
    np.ones(12).reshape((3,2,2)),
    dtype=np.float32
)
y

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [11]:
tf.math.square(x-y)

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[  0.,   1.],
        [  4.,   9.]],

       [[ 16.,  25.],
        [ 36.,  49.]],

       [[ 64.,  81.],
        [100., 121.]]], dtype=float32)>