## Chain Rule (Jacobian Product)

$
\begin{align*}
\frac{\partial}{\partial x} (f \; \circ \; g)(x) 
= \frac{\partial }{\partial x} (\; f (\; g(x) \;) \;) 
= \frac {\partial f}{\partial g} \frac {\partial g}{\partial x}
\end{align*}
$

# dL/dX



\begin{align*}
\frac{\partial L}{\partial x_{(n=0,d=1)}}
\end{align*}


$
\begin{align*}
\frac{\partial Y}{\partial X} \quad \frac{\partial L}{\partial X} \quad \frac{\partial L}{\partial Y}
\\
\frac{\partial L}{\partial x_{(n=0,d=0)}} \quad \frac{\partial L}{\partial x_{(n=0,d=1)}} \quad \frac{\partial L}{\partial x_{(n=0,d=2)}}
\\
\frac{\partial L}{\partial X}  = 
\begin{bmatrix} 
\frac{\partial L}{\partial x_{(n=0,d=0)}} \\ \frac{\partial L}{\partial x_{(n=0,d=1)}} \\ \frac{\partial L}{\partial x_{(n=0,d=2)}}
\end{bmatrix}
\\
\frac{\partial Y}{\partial x_{(n=0,d=0)}} \quad \frac{\partial Y}{\partial x_{(n=0,d=1)}} \quad \frac{\partial Y}{\partial x_{(n=0,d=2)}}
\\
\text{This is dY/x00} \\
\frac{\partial y_{(n=0,m=0)}}{\partial x_{(n=0,d=0)}} \rightarrow w_{(m=0,d=0)}
\frac{\partial y_{(n=0,m=1)}}{\partial x_{(n=0,d=0)}} \rightarrow w_{(m=1,d=0)}
\\
\text{This is dY/x01} \\
\frac{\partial y_{(n=0,m=0)}}{\partial x_{(n=0,d=1)}} \rightarrow w_{(m=0,d=1)}
\frac{\partial y_{(n=0,m=1)}}{\partial x_{(n=0,d=1)}} \rightarrow w_{(m=1,d=1)}
\\
\text{This is dY/x02} \\
\frac{\partial y_{(n=0,m=0)}}{\partial x_{(n=0,d=2)}} \rightarrow w_{(m=0,d=2)}
\frac{\partial y_{(n=0,m=1)}}{\partial x_{(n=0,d=2)}} \rightarrow w_{(m=1,d=2)}
\\
\text{dY/dX00 this is where transpose happen?} \\
\frac{\partial Y}{\partial x_{(n=0,d=0)}} \rightarrow 
\begin{bmatrix} w_{(m=0,d=0)}&w_{(m=1,d=0)}  \end{bmatrix} \qquad 
\\
\frac{\partial Y}{\partial x_{(n=0,d=1)}} \rightarrow 
\begin{bmatrix} w_{(m=0,d=1)}&w_{(m=1,d=1)}  \end{bmatrix} \qquad 
\\
\frac{\partial Y}{\partial x_{(n=0,d=2)}} \rightarrow 
\begin{bmatrix} w_{(m=0,d=2)}&w_{(m=1,d=2)}  \end{bmatrix} \qquad 
\\
\frac{\partial Y}{\partial x_{(n=0,d=0)}} \quad \frac{\partial Y}{\partial x_{(n=0,d=1)}} \quad \frac{\partial Y}{\partial x_{(n=0,d=2)}} 
\\
shape(m=2,) \; shape(m=2,d=3) \; shape() \; shape(d=3,)
\end{align*}
$

$
\begin{align*}
\frac{\partial Y}{\partial x_{(n=0,d=0)}} \rightarrow 
\begin{bmatrix} w_{(m=0,d=0)}&w_{(m=1,d=0)}  \end{bmatrix} \qquad 
\\
\frac{\partial Y}{\partial x_{(n=0,d=1)}} \rightarrow 
\begin{bmatrix} w_{(m=0,d=1)}&w_{(m=1,d=1)}  \end{bmatrix} \qquad 
\\
\frac{\partial Y}{\partial x_{(n=0,d=2)}} \rightarrow 
\begin{bmatrix} w_{(m=0,d=2)}&w_{(m=1,d=2)}  \end{bmatrix} \qquad 
\\
\\
\\
W_{shape(m=2,d=3)} = 
\begin{bmatrix} 
w_{(m=0,d=0)} & w_{(m=0,d=1)} & w_{(m=0,d=2)} \\  
w_{(m=1,d=0)} & w_{(m=1,d=1)} & w_{(m=1,d=2)} \\  
\end{bmatrix}
\\
\\
\\
\frac{\partial Y}{\partial X} =
W^{T}_{shape(d=3,m=2)} &= \;
\begin{bmatrix} 
\frac{\partial Y}{\partial x_{(n=0,d=0)}} \\
\frac{\partial Y}{\partial x_{(n=0,d=1)}} \\
\frac{\partial Y}{\partial x_{(n=0,d=2)}} \\
\end{bmatrix} =
\begin{bmatrix} 
w_{(m=0,d=0)} & 
w_{(m=1,d=0)}  
\\
w_{(m=0,d=1)} & 
w_{(m=1,d=1)}
\\
w_{(m=0,d=2)} & 
w_{(m=1,d=2)}  
\end{bmatrix}
\end{align*}
$

$
\begin{align*}
\frac{\partial Y}{\partial x_{(n=0,d=0)}} \rightarrow 
\begin{bmatrix} w_{(m=0,d=0)}&w_{(m=1,d=0)}  \end{bmatrix} \qquad 
\\
\frac{\partial Y}{\partial x_{(n=0,d=1)}} \rightarrow 
\begin{bmatrix} w_{(m=0,d=1)}&w_{(m=1,d=1)}  \end{bmatrix} \qquad 
\\
\frac{\partial Y}{\partial x_{(n=0,d=2)}} \rightarrow 
\begin{bmatrix} w_{(m=0,d=2)}&w_{(m=1,d=2)}  \end{bmatrix} \qquad 
\\
\end{align*}
$

$
\begin{align*}
\begin{bmatrix} 
w_{(m=0,d=0)}&w_{(m=1,d=0)}  
\end{bmatrix} 
\\
\begin{bmatrix} 
w_{(m=0,d=1)}&w_{(m=1,d=1)}
\end{bmatrix} 
\\
\begin{bmatrix} 
w_{(m=0,d=2)} & 
w_{(m=1,d=2)}  
\end{bmatrix} 
\\
\\
W^{T} &= 
\begin{bmatrix} 
w_{(m=0,d=0)} & 
w_{(m=1,d=0)}  
\\
w_{(m=0,d=1)} & 
w_{(m=1,d=1)}
\\
w_{(m=0,d=2)} & 
w_{(m=1,d=2)}  
\end{bmatrix}
\\
\end{align*}
$

$
\begin{align*}
\frac{\partial L}{\partial Y} \quad @   \quad  W \quad 
\\
W^{T} \quad @ \quad \frac{\partial L}{\partial Y}^{T} \quad 
\end{align*}
$

\begin{align*}
Y_{(n=0)} = X_{(n=0)} \cdot W^{T} \\
\text{shape(m=2,)}
\end{align*}

\begin{align*}
\frac{ \partial y_{(n=0,d=1,m=1)} }{ \partial x_{(n=0,d=1)} } \rightarrow w_{(d=1,m=1)}
\end{align*}

\begin{align*}
y_{(n=0,m=1)} = x_{(n=0,d=1)} * w_{(d=1,m=1)}
\end{align*}

\begin{align*}
y_{(n=0,m=1)} &=  
\sum_{d=0,1,2} {
    y_{(n=0,m=1)}  
} \\
&= \sum_{d=0,1,2} {
   x_{(n=0,d)} * w_{(d,m=1)}
} \\
y_{(n,m)} &\rightarrow \sum_{d} {
   x_{(n,d)} * w_{(d,m)}
}
\\
\end{align*}

\begin{align*}
\frac { \partial y_{(n=0,m=1)} }{ \partial x_{(n=0,d=1)} } &= 
\frac {\partial}{\partial x_{(n=0,d=1)}} \biggl[ \sum_{d=0,1,2} {  x_{(n=0,d)} * w_{(d,m=1)}  } \biggl] \\
&=w_{(d=1,m=1)} \\
\frac { \partial y_{(n,m)} }{ \partial x_{(n,d)} } &\rightarrow 
w_{(d,m)}
\\
\frac{ \partial y_{(n=0,m=1)} }{ \partial x_{(n=0,d=1)} }
\end{align*}

# Gradient dL/dX

Gradient $
\begin{align*}
    \frac{\partial L}{\partial X}
\end{align*}
$
has the same shape with ```X(d=3)``` because ```L``` is scalar. It is calculated as $
\begin{align*}
    \sum_{d} {
        \frac{\partial L}{\partial x_{(n=0,d)}} 
    }
\end{align*}
$ because each $
\begin{align*}
    x_{(n=0,d)}
\end{align*}
$ is independent.

## Element gradient dL/dx(n=0,d)

Element gradient $
\begin{align*}
    \frac{\partial L}{\partial x_{(n=0,d)}}
\end{align*}
$
is scalar because ```x``` and ```L``` are scalar. For ```d=1```, it is first transformed using the chain rule. 

<br>
$
\begin{align*}
\frac{\partial L}{\partial x_{n=0,d=1}} &=
    \frac{\partial L}{\partial Y} 
    \frac{\partial Y} {\partial x_{n=0,d=1} }
\quad \text{(shape())} 
\\
\\
\frac{\partial L} {\partial Y } &= 
\begin{bmatrix}
    \frac{\partial L}{\partial y_{d=0,m=0}} & \frac{\partial L}{\partial y_{d=0,m=1}} & \frac{\partial L}{\partial y_{d=0,m=2}} & \frac{\partial L}{\partial y_{d=0,m=3}} \\ 
    \frac{\partial L}{\partial y_{d=1,m=0}} & \frac{\partial L}{\partial y_{d=1,m=1}} & \frac{\partial L}{\partial y_{d=1,m=2}} & \frac{\partial L}{\partial y_{d=1,m=3}} \\ 
    \frac{\partial L}{\partial y_{d=2,m=0}} & \frac{\partial L}{\partial y_{d=2,m=1}} & \frac{\partial L}{\partial y_{d=2,m=2}} & \frac{\partial L}{\partial y_{d=2,m=3}} \\ 
\end{bmatrix}
\qquad \qquad \qquad \text{(shape(d=3,m=4))}
\\
\\
\frac{\partial Y} {\partial x_{n=0,d=1} } &= 
\begin{bmatrix}
0 & 0 & 0 & 0\\
w_{(d=1,m=0)} & w_{(d=1,m=1)} & w_{(d=1,m=2)} & w_{(d=1,m=3)} \\
0 & 0 & 0 & 0\\
\end{bmatrix}
\qquad \; \text{(shape(d=3,m=4))}
\end{align*}
$

$
\begin{align*}
\frac{\partial L} {\partial Y } = 
\begin{bmatrix}
    \frac{\partial L}{\partial y_{(n=0,m=0)}} & \frac{\partial L}{\partial y_{(n=0,m=1)}}  \\ 
\end{bmatrix}
\\
\\
\begin{bmatrix}
\frac{\partial L}{\partial y_{(n=0,m=0)}} & \frac{\partial L}{\partial y_{(n=0,m=1)}} 
\end{bmatrix}
-----------------------\\
\begin{bmatrix}
\frac{\partial L}{\partial y_{(n=0,m=0)}} \\ \frac{\partial L}{\partial y_{(n=0,m=1)}} 
\end{bmatrix}
\\
\end{align*}
$

$
\begin{align*}
\frac{\partial L} {\partial Y } = 
\begin{bmatrix}
 \vdots & \vdots \\
 v_1 & v_2\\
 \vdots & \vdots
\end{bmatrix}
\end{align*}
$

$
\begin{align*}
\frac{\partial L}{\partial x_{n=0,d=1}} &=
\sum_{m=0,1,2,3}{
    \frac{\partial L}{\partial y_{n=0,m}} 
    \frac{\partial y_{n=0,m}} {\partial x_{n=0,d=1} }
}  \\
&= \sum_{m=0,1,2,3}{
    \frac{\partial L}{\partial y_{n=0,m}} w_{(d=1,m)}
}
\end{align*}
$

\begin{align*}
\frac{\partial L}{\partial x_{n=0,d=0,1,2}} &=
\sum_{m=0,1,2,3}{
    \frac{\partial L}{\partial y_{n=0,m}} w_{(d=0,1,2,m)}
} \\
&= \bigl[
    \sum_{m}{
        \frac{\partial L}{\partial y_{n=0,m}} w_{(d=0,m)}
    },
    \sum_{m}{
        \frac{\partial L}{\partial y_{n=0,m}} w_{(d=1,m)}
    },
    \sum_{m}{
        \frac{\partial L}{\partial y_{n=0,m}} w_{(d=2,m)}
    }
\bigl]
\quad \text{(shape(d=3,))} \\
\frac{\partial L}{\partial x_{n,d}} &\rightarrow
\sum_{m}{
    \frac{\partial L}{\partial y_{n,m}} w_{(d,m)}
}
\quad \text{(shape(d=3,))}
\end{align*}

\begin{align*}
\frac{\partial L}{\partial x_{n=0,d=1}} \rightarrow 
\sum_{d}{\frac{\partial L}{\partial x_{n=0,d}}}  \rightarrow 
\frac{\partial L}{\partial x_{n=0}}  
\; \text{(shape(3,))}
\end{align*}

\begin{equation*}
\mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} &  \frac{\partial Y}{\partial u} & 0 \\
\frac{\partial X}{\partial v} &  \frac{\partial Y}{\partial v} & 0
\end{vmatrix}
\end{equation*}

# Jacobian

$
\begin{align*}
\text{With} \quad Z = W^{T}
\\
Y &= g(Z) = X \; @ \; Z
\\
L &= f(Y)
\\
(f\circ g)'(Z) &= f'(g(Z)) \; @ \; g'(Z)
\\
\\
Jf(Y) = \frac {\partial {L}}{\partial {Y}} 
&=
\begin{bmatrix} 
\frac{\partial f_0}{\partial y_0}&\cdots&\frac{\partial f_0}{\partial y_{M-1}}\\ 
\vdots&&\vdots
\\
\frac{\partial f_{M-1}}{\partial y_0} & \cdots & \frac{\partial f_{M-1}}{\partial y_{M-1}}
\end{bmatrix}
\\
\\
Jg(Z) = \frac {\partial {L}}{\partial Z} 
&=
\begin{bmatrix} 
\frac{\partial y_0}{\partial w_0}&\cdots&\frac{\partial y_0}{\partial w_{D-1}}\\ 
\vdots&&\vdots\\ 
\frac{\partial y_{M-1}}{\partial w_0}&\cdots&\frac{\partial y_{M-1}}{\partial w_{D-1}} 
\end{bmatrix}
\\
\\
J(f\circ g)(Z) &= \; Jf(g(Z)) \quad @ \quad Jg(Z) 
\\
\\
&=
\frac {\partial {L}}{\partial {Y}} \quad @ \quad \frac {\partial {L}}{\partial Z} \quad
\end{align*}
$

**Derivative Matrix**

If *f* : $\Bbb R^n \to \Bbb R^m$ is a differentiable function, then the derivative is an  *m* x *n* matrix given by 

$$\mathbf D f = \begin{bmatrix} \frac{\partial f_1}{\partial x_1} & \frac{\partial f_1}{\partial x_2} & \cdots & \frac{\partial f_1}{\partial x_n}\\ \vdots & \vdots & \ddots & \vdots \\ \frac{\partial f_m}{\partial x_1} & \frac{\partial f_m}{\partial x_2} & \cdots & \frac{\partial f_m}{\partial x_n}\end{bmatrix}$$ 

where $ f(x_1, x_2, ... , x_n) = (f_1(x_1, ... x_n), f_2(x_1, ..., x_n)..., f_m(x_1,...,x_n))$

**Matrix Version of Chain Rule**

If *f* : $\Bbb R^m \to  \Bbb R^p $ and *g* : $\Bbb R^n \to \Bbb R^m$ are differentiable functions and the composition *f* $\circ$ *g* is defined then $$\mathbf D(f \circ g) = \mathbf Df \mathbf Dg$$  

Note: (*f* $\circ$ *g*)$(x_1, x_2,...,x_n)$ = *f* [*g* ($x_1,x_2,...,x_n)]$

# dL/dW.T

$
\begin{align*}
\frac{\partial L}{\partial W^{T}} \quad
\frac{\partial Y}{\partial W^{T}} \quad
\frac{\partial L}{\partial Y}
\\
\text{--------------------------------------------------------------------------------} \\
\text{dL/dW.T} \\
\text{--------------------------------------------------------------------------------} \\
\frac{\partial L}{\partial w_{(m=0,d=0)}} \quad 
\frac{\partial L}{\partial w_{(m=0,d=1)}} \quad 
\frac{\partial L}{\partial w_{(m=0,d=2)}}
\\
\frac{\partial L}{\partial w_{(m=1,d=0)}} \quad
\frac{\partial L}{\partial w_{(m=1,d=1)}} \quad
\frac{\partial L}{\partial w_{(m=1,d=2)}}
\\
\frac{\partial L}{\partial W^{T}}  =
\begin{bmatrix} 
\frac{\partial L}{\partial w_{(m=0,d=0)}} & \frac{\partial L}{\partial w_{(m=1,d=0)}} \\
\frac{\partial L}{\partial w_{(m=0,d=1)}} & \frac{\partial L}{\partial w_{(m=1,d=1)}} \\
\frac{\partial L}{\partial w_{(m=0,d=2)}} & \frac{\partial L}{\partial w_{(m=1,d=2)}}
\end{bmatrix}
\\
\text{--------------------------------------------------------------------------------} \\
\text{dY/dW.T} \\
\text{--------------------------------------------------------------------------------} \\
\frac{\partial Y}{\partial w_{(m=0,d=0)}} \quad 
\frac{\partial Y}{\partial w_{(m=0,d=1)}} \quad 
\frac{\partial Y}{\partial w_{(m=0,d=2)}}
\\ \\
\frac{\partial Y}{\partial w_{(m=1,d=0)}} \quad
\frac{\partial Y}{\partial w_{(m=1,d=1)}} \quad
\frac{\partial Y}{\partial w_{(m=1,d=2)}}
\\
\frac{\partial Y}{\partial W^{T}}  =
\begin{bmatrix}
\frac{\partial Y}{\partial w_{(m=0,d=0)}} & \frac{\partial Y}{\partial w_{(m=1,d=0)}} \\
\frac{\partial Y}{\partial w_{(m=0,d=1)}} & \frac{\partial Y}{\partial w_{(m=1,d=1)}} \\
\frac{\partial Y}{\partial w_{(m=0,d=2)}} & \frac{\partial Y}{\partial w_{(m=1,d=2)}}
\end{bmatrix}
\\
\end{align*}
$

### dy/dw

$
\frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=0,d=0)}} \rightarrow x_{(n=0,d=0)} \quad
\frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=0,d=0)}} \rightarrow 0 \\
\\
\frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=0,d=1)}} \rightarrow x_{(n=0,d=1)} \quad
\frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=0,d=1)}} \rightarrow 0
\\
\frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=0,d=2)}} \rightarrow x_{(n=0,d=2)} \quad
\frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=0,d=2)}} \rightarrow 0
\\
\frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=1,d=0)}} \rightarrow 0 \quad
\frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=1,d=0)}} \rightarrow x_{(n=0,d=0)} \\
\\
\frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=1,d=1)}} \rightarrow 0 \quad
\frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=1,d=1)}} \rightarrow x_{(n=0,d=1)}
\\
\frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=1,d=2)}} \rightarrow 0 \quad
\frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=1,d=2)}} \rightarrow x_{(n=0,d=2)}
$

## Y = X @ W.T

$
\begin{align*}
X &=
\begin{bmatrix}
    x_{(n=0,d=0)} &  x_{(n=0,d=1)} & x_{(n=0,d=2)}
\end{bmatrix} \\
\\
W & = 
\begin{bmatrix}
    \begin{matrix}
    w_{(m=0,d=0)} & w_{(m=0,d=1)} & w_{(m=0,d=2)}
    \end{matrix} 
    \\
    \begin{matrix}
    w_{(m=1,d=0)} & w_{(m=1,d=1)} & w_{(m=1,d=2)}
    \end{matrix}
\end{bmatrix} \\
\\
W^{T} & = 
\begin{bmatrix}
    \begin{matrix}
    w_{(m=0,d=0)} \\ w_{(m=0,d=1)} \\ w_{(m=0,d=2)}
    \end{matrix} 
    &
    \begin{matrix}
    w_{(m=1,d=0)} \\ w_{(m=1,d=1)} \\ w_{(m=1,d=2)}
    \end{matrix}
\end{bmatrix} \\
\\
Y &= 
X @ W^{T} \\
& = 
\begin{bmatrix}
    \begin{matrix}
    x_{(n=0,d=0)} * w_{(m=0,d=0)} \\
    + \\
    x_{(n=0,d=1)} * w_{(m=0,d=1)} \\
    + \\ 
    x_{(n=0,d=2)} * w_{(m=0,d=2)}
    \end{matrix} &
    \begin{matrix}
    x_{(n=0,d=0)} * w_{(m=1,d=0)} \\
    + \\
    x_{(n=0,d=1)} * w_{(m=1,d=1)}\\
    + \\
    x_{(n=0,d=2)} * w_{(m=1,d=2)}
    \end{matrix}
\end{bmatrix} \\
\end{align*}
$

$
\begin{align*}
Y_{shape(N=1,M=2)} = X_{shape(N=1,D=3)} \quad @ \quad W^{T}_{shape(D=3,M=2)}
\end{align*}
$

### dL/dY
shape(N=1,M=2)

$
\begin{align*}
\frac{\partial L} {\partial Y } = 
\begin{bmatrix}
    \frac{\partial L}{\partial y_{(n=0,m=0)}} & \frac{\partial L}{\partial y_{(n=0,m=1)}}  \\ 
\end{bmatrix}
\end{align*}
$

### dY/dW.T

$
\begin{align*}
\frac{\partial Y}{\partial W^{T}} 
&=
\quad
    \begin{bmatrix}
        \begin{matrix}
            \frac{\partial Y}{\partial w_{(m=0,d=0)}} \\
            \frac{\partial Y}{\partial w_{(m=0,d=1)}} \\
            \frac{\partial Y}{\partial w_{(m=0,d=2)}} 
        \end{matrix} 
        &
        \begin{matrix}
            \frac{\partial Y}{\partial w_{(m=1,d=0)}} \\
            \frac{\partial Y}{\partial w_{(m=1,d=1)}} \\
            \frac{\partial Y}{\partial w_{(m=1,d=2)}} 
        \end{matrix}
    \end{bmatrix}
\\
&=
\quad
    \begin{bmatrix}
        \begin{matrix}
            \begin{bmatrix}
                \frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=0,d=0)}} & \frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=0,d=0)}}
            \end{bmatrix}
            \\
            \begin{bmatrix}
                \frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=0,d=1)}} & \frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=0,d=1)}} 
            \end{bmatrix}
            \\
            \begin{bmatrix} 
                \frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=0,d=2)}} & \frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=0,d=2)}} 
            \end{bmatrix}
        \end{matrix}
        &
        \begin{matrix}
            \begin{bmatrix}
                \frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=1,d=0)}} & \frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=1,d=0)}}
            \end{bmatrix}
            \\
            \begin{bmatrix}
                \frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=1,d=1)}} & \frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=1,d=1)}} 
            \end{bmatrix} 
            \\
            \begin{bmatrix} 
                \frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=1,d=2)}} & \frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=1,d=2)}} 
            \end{bmatrix}
        \end{matrix}
    \end{bmatrix}
\\
&=
\quad
    \begin{bmatrix}
        \begin{matrix}
            \begin{bmatrix}
                \frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=0,d=0)}} & 0
            \end{bmatrix}
            \\
            \begin{bmatrix}
                \frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=0,d=1)}} & 0
            \end{bmatrix}
            \\
            \begin{bmatrix} 
                \frac{\partial y_{(n=0,m=0)}}{\partial w_{(m=0,d=2)}} & 0
            \end{bmatrix}
        \end{matrix}
        &
        \begin{matrix}
            \begin{bmatrix}
                0 & \frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=1,d=0)}}
            \end{bmatrix}
            \\
            \begin{bmatrix}
                0 & \frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=1,d=1)}} 
            \end{bmatrix} 
            \\
            \begin{bmatrix} 
                0 & \frac{\partial y_{(n=0,m=1)}}{\partial w_{(m=1,d=2)}} 
            \end{bmatrix}
        \end{matrix}
    \end{bmatrix}
\\
&=
\quad
    \begin{bmatrix}
        \begin{matrix}
            \begin{bmatrix}
            x_{(n=0,d=0)} & 0
            \end{bmatrix}
            \\
            \begin{bmatrix}
            x_{(n=0,d=1)} & 0
            \end{bmatrix}
            \\
            \begin{bmatrix} 
            x_{(n=0,d=2)} & 0
            \end{bmatrix}
        \end{matrix}
        &
        \begin{matrix}
            \begin{bmatrix}
            0 & x_{(n=0,d=0)}
            \end{bmatrix}
            \\
            \begin{bmatrix}
            0 & x_{(n=0,d=1)}
            \end{bmatrix}
            \\
            \begin{bmatrix} 
            0 & x_{(n=0,d=2)}
            \end{bmatrix}
        \end{matrix}
    \end{bmatrix}
\end{align*}
$

In [1]:
import numpy as np
W = np.arange(1, 7).reshape((2,3))
print("W is \n{}\n".format(W))
print("W.T is \n{}\n".format(W.T))

dLdY = np.array([-1, -10])
print("dLdY is \n{}\n".format(dLdY))

print("np.dot(W.T, dLdY)\n{}".format(np.dot(W.T, dLdY)))
print("np.inner(W.T, dLdY)\n{}".format(np.inner(W.T, dLdY)))
print("np.matmul(W.T, dLdY)\n{}".format(np.matmul(W.T, dLdY)))
print("W.T@dLdY\n{}".format(W.T@dLdY))

W is 
[[1 2 3]
 [4 5 6]]

W.T is 
[[1 4]
 [2 5]
 [3 6]]

dLdY is 
[ -1 -10]

np.dot(W.T, dLdY)
[-41 -52 -63]
np.inner(W.T, dLdY)
[-41 -52 -63]
np.matmul(W.T, dLdY)
[-41 -52 -63]
W.T@dLdY
[-41 -52 -63]


In [2]:
dLdY = np.array([-1, -10])
print("dLdY is {}".format(dLdY))
import numpy as np
W = np.arange(1, 7).reshape((2,3))
print("W is \n{}\n".format(W))
print("W.T is \n{}\n".format(W.T))

print("""dL/dX = dX/dY x dL/dY with np.array([
  np.inner(W.T[0], dLdY),
  np.inner(W.T[1], dLdY),
  np.inner(W.T[2], dLdY)
]) is {}\n""".format(
    np.array([
      np.inner(W.T[0], dLdY),
      np.inner(W.T[1], dLdY),
      np.inner(W.T[2], dLdY)
    ])
))
print("With np.matmul(W.T, dLdY)\n{}".format(np.matmul(W.T, dLdY)))

dLdY is [ -1 -10]
W is 
[[1 2 3]
 [4 5 6]]

W.T is 
[[1 4]
 [2 5]
 [3 6]]

dL/dX = dX/dY x dL/dY with np.array([
  np.inner(W.T[0], dLdY),
  np.inner(W.T[1], dLdY),
  np.inner(W.T[2], dLdY)
]) is [-41 -52 -63]

With np.matmul(W.T, dLdY)
[-41 -52 -63]


In [3]:
import numpy as np
W = np.arange(1, 7).reshape((2,3))
dLdY = np.array([-1, -10])

print("np.dot(W.T, dLdY) is only valid if dL/dY is shape(m,) but NOT with shape(n, m)")
print("--------------------------------------------------------------------------------")
print("np.dot(W.T, dLdY)\n{}".format(np.dot(W.T, dLdY)))
print("np.inner(W.T, dLdY)\n{}".format(np.inner(W.T, dLdY)))
print("W.T@dLdY\n{}".format(W.T@dLdY))

print()
dLdY_2 = np.array([dLdY])
print("np.dot(W.T, dLdY), np.inner(W.T, dLdY) does not work with shape(n, m) e.g. {}".format(dLdY_2))
print("--------------------------------------------------------------------------------")
try:
    np.dot(W.T, dLdY_2)
except Exception as e:
    print("error: {}\n".format(e))

print("Need consistently use @ or np.matmul(W.T, dLdY)")
print("--------------------------------------------------------------------------------")
print("{}".format(
    np.matmul(W.T, dLdY)
))


np.dot(W.T, dLdY) is only valid if dL/dY is shape(m,) but NOT with shape(n, m)
--------------------------------------------------------------------------------
np.dot(W.T, dLdY)
[-41 -52 -63]
np.inner(W.T, dLdY)
[-41 -52 -63]
W.T@dLdY
[-41 -52 -63]

np.dot(W.T, dLdY), np.inner(W.T, dLdY) does not work with shape(n, m) e.g. [[ -1 -10]]
--------------------------------------------------------------------------------
error: shapes (3,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

Need consistently use @ or np.matmul(W.T, dLdY)
--------------------------------------------------------------------------------
[-41 -52 -63]
