# Inner Product is expressed with column outer products

<img src="inner_product_as_sum_of_column_vector_outer_products.JPG" align="left"/>

In [5]:
import numpy as np
np.set_printoptions(suppress=True)

In [39]:
A = np.array([
    [1, -0.8],
    [0, 1],
    [1, 0]
])

In [47]:
U, s, VT = np.linalg.svd(A)
V = VT.T

In [48]:
print(U)
print(VT)
print(s)

[[-0.78817011  0.         -0.61545745]
 [ 0.38447322 -0.78086881 -0.49236596]
 [-0.48059153 -0.62469505  0.61545745]]
[[-0.78086881  0.62469505]
 [-0.62469505 -0.78086881]]
[1.62480768 1.        ]


In [49]:
S = np.r_[
    np.eye(2) * s,
    [[0, 0]]
]

In [50]:
S

array([[1.62480768, 0.        ],
       [0.        , 1.        ],
       [0.        , 0.        ]])

---
# Inner product $U \cdot S \cdot V^T$

In [51]:
U @ S @ VT

array([[ 1. , -0.8],
       [-0. ,  1. ],
       [ 1. ,  0. ]])

In [46]:
US = U @ S
US

array([[-1.28062485,  0.        ],
       [ 0.62469505, -0.78086881],
       [-0.78086881, -0.62469505]])

# Inner product $US \cdot V^T$ as $\sum US[:, i] \otimes V[:, i]^T$

In [52]:
u0 = US[:, 0]
u1 = US[:, 1]
v0t = V[:, 0].T
v1t = V[:, 1].T

In [59]:
u0_v0t = np.outer(u0, v0t)
u0_v0t

array([[ 1.        , -0.8       ],
       [-0.48780488,  0.3902439 ],
       [ 0.6097561 , -0.48780488]])

In [61]:
u1_v1t = np.outer(u1, v1t)
u1_v1t

array([[-0.        , -0.        ],
       [ 0.48780488,  0.6097561 ],
       [ 0.3902439 ,  0.48780488]])

In [67]:
np.add(u0_v0t, u1_v1t)

array([[ 1. , -0.8],
       [-0. ,  1. ],
       [ 1. ,  0. ]])