In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np
X = np.array(list(range(1, 13))).reshape(3, 4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
THETA = np.pi / 12

# Eigen Decomposition

## Eigen vector matrix P

Define **P** as a row ordered matrix where the row $\overrightarrow{\boldsymbol{p_1}} = \left [ cos(\theta), sin(\theta) \right ]$ and $\overrightarrow{\boldsymbol{p_2}} = \left [ -sin(\theta), cos(\theta) \right ]$ are eigen vectors.

$\begin{bmatrix}cos(\theta) & sin(\theta) \\ -sin(\theta) & cos(\theta)\end{bmatrix}$



In [5]:
def get_eigen_vector_matrix(theta):
    return np.array([
        [np.cos(theta), np.sin(theta)],
        [-np.sin(theta), np.cos(theta)]
    ])

In [6]:
P = get_eigen_vector_matrix(THETA)
print(P)

[[ 0.96592583  0.25881905]
 [-0.25881905  0.96592583]]


## Eigen value diagonal matrix D

D extends the eigen vector $\overrightarrow{\boldsymbol{p_1}}$ for $\lambda_1$ times and  $\overrightarrow{\boldsymbol{p_2}}$ for $\lambda_2$ times.

$D = \begin{bmatrix}\lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix}$


In [7]:
D = np.array([
    [3, 0],
    [0, 2]
])
print(D)

[[3 0]
 [0 2]]


# Projection Matrix $A = PDP^{-1}$

Generate **A** from **P** and **D**.

Projection by the matrix $A \cdot \begin{bmatrix}x_1 \\ x_2 \end{bmatrix} = P \cdot D \cdot P^{-1} \cdot \begin{bmatrix}x_1 \\ x_2 \end{bmatrix}$ where:

1. $P^{-1} \cdot x$ maps the coefficients of $x = (x_1, x_2)$ in space **X** in purple into those of $u = (u_1, u_2)$ in space **U** in orange 
where the eigen vectors $(\overrightarrow{\boldsymbol{p_1}}, \overrightarrow{\boldsymbol{p_2}})$ are the basis vectors in **U**.
2. $D \cdot u$ extends the coefficent of $\overrightarrow{\boldsymbol{p_1}}$ by $\lambda_1$ times and that of $\overrightarrow{\boldsymbol{p_2}}$ by $\lambda_2$ times as $\begin{bmatrix}\lambda_1u_1 \\ \lambda_2u_2 \end{bmatrix}$.
3. $P$ projects $\begin{bmatrix}\lambda_1u_1 \\ \lambda_2u_2 \end{bmatrix}$ back to space **X**.


In [12]:
A = P @ D @ np.linalg.inv(P)
print(A)

[[ 2.9330127 -0.25     ]
 [-0.25       2.0669873]]


## Verify the eigen vector matrix P

In [13]:
l, e = np.linalg.eig(A)
print(l)      # eigen values lambda
print(e.T)    # eigen vectors e. Transpose to be row oriented

[3. 2.]
[[ 0.96592583 -0.25881905]
 [ 0.25881905  0.96592583]]


---

# Projection Matrix $A = P^TD(P^T)^{-1}$

In [14]:
_A = P.T @ D @ np.linalg.inv(P.T)
print(_A)

[[2.9330127 0.25     ]
 [0.25      2.0669873]]


## Verify the eigen vector matrix $P^T$

In [15]:
_l, _e = np.linalg.eig(_A)
print(_l)      # eigen values lambda
print(_e.T)    # eigen vectors e. Transpose to be row oriented

[3. 2.]
[[ 0.96592583  0.25881905]
 [-0.25881905  0.96592583]]
