# Mistake
Quite silly thinking the reshape is the same with transpose.

In [80]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(suppress=True)

In [112]:
N = 4   # Number of vectors
THETA = np.pi / 12

# Data

## Slope

In [113]:
slope = np.sin(THETA) / np.cos(THETA)
slope

0.2679491924311227

## Data points X

Row oriented vector.

In [129]:
buf = []
for x in np.linspace(-1, 1, num=int(N/2)):
    y = x * slope
    deviation = np.random.uniform(0.01, 0.8)
    buf.append([x, y * (1+deviation)])
    buf.append([x, y * (1-deviation)])
    
X = np.array(buf)
D = X.shape[1] # Dimension of the vector
X.shape

(4, 2)

In [130]:
# Make sure to zero-centered per each feature
X_mean = np.mean(X, axis=0)
X = X - X_mean

In [131]:
X

array([[-1.        , -0.36440124],
       [-1.        , -0.17149715],
       [ 1.        ,  0.47465933],
       [ 1.        ,  0.06123906]])

# Transpose

In [132]:
X.T

array([[-1.        , -1.        ,  1.        ,  1.        ],
       [-0.36440124, -0.17149715,  0.47465933,  0.06123906]])

# Reshape

In [134]:
X.reshape((D, -1))

array([[-1.        , -0.36440124, -1.        , -0.17149715],
       [ 1.        ,  0.47465933,  1.        ,  0.06123906]])