In [1]:
import matplotlib.pyplot as plt

In [25]:
import numpy as np

In [3]:
THETA = np.pi / 12

# Eigen Decomposition


$A = VDV^T$ 

$V = \begin{bmatrix}
\overrightarrow{\boldsymbol{v_0}} & 
\overrightarrow{\boldsymbol{v_1}} 
\end{bmatrix}$ 
is a **column ordered** matrix where $\overrightarrow{\boldsymbol{v_0}}$ and $\overrightarrow{\boldsymbol{v_0}}$ are the basis vectors of space **V** whose coordinates are specified in X space. 

$D = \begin{bmatrix}\lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix}$ is an eigen value matrix that extends $\overrightarrow{\boldsymbol{v_0}}$ for $\lambda_0$ times and $\overrightarrow{\boldsymbol{v_1}}$ for $\lambda_1$ times.


## Geometric interpretation of $A = VDV^T$ 

1. $V^T$ projects the coordinate (coefficients) in space **X** into the coefficients in space **V**.
2. $D$ scales the coordinate in U according to the eigen values.
3. $V$ projects the coordinate in space **V** back into that in space **X**.

<img src="matrix_linear_mapping_to_another_space.JPG" align="left" />

In [11]:
A = np.array([
    [2,1],
    [1,2]
])

In [12]:
(lambda_0, lambda_1), E = np.linalg.eig(A)
print(f"eigen value lambda_0 is {lambda_0}")
print(f"eigen value lambda_1 is {lambda_1}")
print(f"eigen vector v0 is {E[:, 0]}")
print(f"eigen vector v1 is {-E[:, 1]}")      

eigen value lambda_0 is 3.0
eigen value lambda_1 is 1.0
eigen vector v0 is [0.70710678 0.70710678]
eigen vector v1 is [ 0.70710678 -0.70710678]


## Eigen value matrix D

In [13]:
D = np.array([
    [lambda_0, 0],
    [0, lambda_1]
])
D

array([[3., 0.],
       [0., 1.]])

In [14]:
def get_basis_vector_matrix_of_V(v0, v1):
    """Get the basis vector matrix of space U using the corrdinates in X space.
    Args:
        v0: first basis vector represented using the coordinate in X
        v1: 2nd basis vector represented using the coordinate in X
    Returns:
        U = [
           v0, v1,
        ] as column ordered vectors where the basis vector 
        v0, v1 are the columns in U
    """
    v0 = np.array(v0).reshape((-1))   # Make it a column vector
    v1 = np.array(v1).reshape((-1))   # Make it a column vector
    assert np.dot(v0, v1.T) == 0, \
        f"expected orthogonal basis vectors, got {v0} and {v1} whose dot product is {np.dot(v0, v1)}."

    U = np.c_[
        v0 / np.sqrt((v0**2).sum()), v1 / np.sqrt((v1**2).sum())
    ]
    return U

In [15]:
def get_X_to_V_mapping_matrix(v0, v1):
    """Get the projection matrix that map the coordinate of X space into that in V space.
    Args:
        v0: first basis vector represented using the coordinate in X
        v1: 2nd basis vector represented using the coordinate in X
    """
    return np.linalg.inv(get_basis_vector_matrix_of_V(v0, v1))

In [16]:
def apply_matrix_n_times(m: np.ndarray, n: int):
    return np.linalg.matrix_power(m, n)

## Basis vectors of space V

In [17]:
v0 = [1, 1]      # not normalized
v1 = [1, -1]

## Basis vector matrix of spae V

In [18]:
V = get_basis_vector_matrix_of_V(v0, v1)
V

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

## Coordinate (Coefficient) projection matrix $V^T$
Matrix $V^T$ to map the coordinate (x0, x1) in space X to (u0, u1) in V.

In [19]:
VT = get_X_to_V_mapping_matrix(v0, v1)
VT

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

## Point x_eigen_0

The point is the same with the basis vector of space U, which is the eigen vector of the matrix A whose eigen value is ```lambda_0 = 3```. Hence, applying A n times will not extend it $3^n$ times.

In [20]:
x_eigen_0 = np.array(v0)
x_eigen_0

array([1, 1])

## Projection from space X to space V

1. Apply $V^T$ to project the coefficient ```x``` in space X into coefficient ```u``` in the space V.
2. Scale ```u``` by applying the eigev value matrix $D$ n times in space V.
3. Apply $V$ to project the result $E^n \cdot u$ back into space X.

### Project x into space V

In [21]:
u = np.dot(VT, x_eigen_0)
u

array([1.41421356, 0.        ])

### Apply **D** k times

In [22]:
K = 3
u_transferred = np.dot(apply_matrix_n_times(D, K), u)
u_transferred

array([38.18376618,  0.        ])

### Project back into space X

In [23]:
np.dot(V, u_transferred)

array([27., 27.])

# Transformation in space X

This results in the same with transformation result in space **V**.

In [24]:
np.dot(apply_matrix_n_times(A, K), x_eigen_0)

array([27, 27])