In [1]:
import matplotlib.pyplot as plt

In [2]:
import numpy as np
X = np.array(list(range(1, 13))).reshape(3, 4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
THETA = np.pi / 12

# Eigen Decomposition

## Eigen vector matrix P

Define **P** as a row ordered matrix where the row $\overrightarrow{\boldsymbol{p_1}} = \left [ cos(\theta), sin(\theta) \right ]$ and $\overrightarrow{\boldsymbol{p_2}} = \left [ -sin(\theta), cos(\theta) \right ]$ are eigen vectors.

$\begin{bmatrix}cos(\theta) & sin(\theta) \\ -sin(\theta) & cos(\theta)\end{bmatrix}$



In [4]:
def get_eigen_vector_matrix(theta):
    return np.array([
        [np.cos(theta), np.sin(theta)],
        [-np.sin(theta), np.cos(theta)]
    ])

In [5]:
P = get_eigen_vector_matrix(THETA)
print(P)

[[ 0.96592583  0.25881905]
 [-0.25881905  0.96592583]]


## Eigen value diagonal matrix D

D extends the eigen vector $\overrightarrow{\boldsymbol{p_1}}$ for $\lambda_1$ times and  $\overrightarrow{\boldsymbol{p_2}}$ for $\lambda_2$ times.

$D = \begin{bmatrix}\lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix}$


In [6]:
D = np.array([
    [3, 0],
    [0, 2]
])
print(D)

[[3 0]
 [0 2]]


# Projection Matrix $A = PDP^{-1}$

Generate **A** from **P** and **D**.

Projection by the matrix $A \cdot \begin{bmatrix}x_1 \\ x_2 \end{bmatrix} = P \cdot D \cdot P^{-1} \cdot \begin{bmatrix}x_1 \\ x_2 \end{bmatrix}$ where:

1. $P^{-1} \cdot x$ maps the coefficients of $x = (x_1, x_2)$ in space **X** in purple into those of $u = (u_1, u_2)$ in space **U** in orange 
where the eigen vectors $(\overrightarrow{\boldsymbol{p_1}}, \overrightarrow{\boldsymbol{p_2}})$ are the basis vectors in **U**.
2. $D \cdot u$ extends the coefficent of $\overrightarrow{\boldsymbol{p_1}}$ by $\lambda_1$ times and that of $\overrightarrow{\boldsymbol{p_2}}$ by $\lambda_2$ times as $\begin{bmatrix}\lambda_1u_1 \\ \lambda_2u_2 \end{bmatrix}$.
3. $P$ projects $\begin{bmatrix}\lambda_1u_1 \\ \lambda_2u_2 \end{bmatrix}$ back to space **X**.


In [7]:
A = P @ D @ np.linalg.inv(P)
print(A)

[[ 2.9330127 -0.25     ]
 [-0.25       2.0669873]]


## Verify the eigen vector matrix P

In [8]:
l, e = np.linalg.eig(A)
print(l)      # eigen values lambda
print(e.T)    # eigen vectors e. Transpose to be row oriented

[3. 2.]
[[ 0.96592583 -0.25881905]
 [ 0.25881905  0.96592583]]


---

# Projection Matrix $A = P^TD(P^T)^{-1}$

In [9]:
_A = P.T @ D @ np.linalg.inv(P.T)
print(_A)

[[2.9330127 0.25     ]
 [0.25      2.0669873]]


## Verify the eigen vector matrix $P^T$

In [10]:
_l, _e = np.linalg.eig(_A)
print(_l)      # eigen values lambda
print(_e.T)    # eigen vectors e. Transpose to be row oriented

[3. 2.]
[[ 0.96592583  0.25881905]
 [-0.25881905  0.96592583]]


---
# Experiment

$A = EDV$ 

$E = \begin{bmatrix}
\overrightarrow{\boldsymbol{v_0}} & 
\overrightarrow{\boldsymbol{v_1}} 
\end{bmatrix}$ 
is a column ordered matrix where $\overrightarrow{\boldsymbol{v_0}}$ and $\overrightarrow{\boldsymbol{v_0}}$ are the basis vectors of space **V** whose coordinates are specified in X space. 

$D = \begin{bmatrix}\lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix}$ is an eigen value matrix that extends $\overrightarrow{\boldsymbol{v_0}}$ for $\lambda_0$ times and $\overrightarrow{\boldsymbol{v_1}}$ for $\lambda_1$ times.

$V = \begin{bmatrix}
\overrightarrow{\boldsymbol{v_0}} \cdot \begin{bmatrix} 1 \\ 0 \end{bmatrix}& 
\overrightarrow{\boldsymbol{v_1}} \cdot \begin{bmatrix} 0 \\ 1 \end{bmatrix}
\end{bmatrix}$ 
is a column ordered matrix where each column is the coordinate in space **V** for the basis vectors of space **X**.

**V** projects the coordinate (coefficients) in space **X** into that in space **V**.
**E** projects the coordinate in space **V** back into that in space **X**.

<img src="matrix_linear_mapping_to_another_space.JPG" align="left" />

In [103]:
A = np.array([
    [2,1],
    [1,2]
])

In [112]:
(lambda_0, lambda_1), E = np.linalg.eig(A)
print(f"eigen value lambda_0 is {lambda_0}")
print(f"eigen value lambda_1 is {lambda_1}")
print(f"eigen vector v0 is {E[:, 0]}")
print(f"eigen vector v1 is {-E[:, 1]}")      

eigen value lambda_0 is 3.0
eigen value lambda_1 is 1.0
eigen vector v0 is [0.70710678 0.70710678]
eigen vector v1 is [ 0.70710678 -0.70710678]


## Eigen value matrix D

In [120]:
D = np.array([
    [lambda_0, 0],
    [0, lambda_1]
])
D

array([[3., 0.],
       [0., 1.]])

In [76]:
def get_basis_vector_matrix_of_V(v0, v1):
    """Get the basis vector matrix of space U using the corrdinates in X space.
    Args:
        v0: first basis vector represented using the coordinate in X
        v1: 2nd basis vector represented using the coordinate in X
    Returns:
        U = [
           [v0, v1],
        ] as column ordered vectors where the basis vector 
        v0, v1 are the columns in U
    """
    v0 = np.array(v0).reshape((-1))   # Make it a column vector
    v1 = np.array(v1).reshape((-1))   # Make it a column vector
    assert np.dot(v0, v1.T) == 0, \
        f"expected orthogonal basis vectors, got {v0} and {v1} whose dot product is {np.dot(v0, v1)}."

    U = np.c_[
        v0 / np.sqrt((v0**2).sum()), v1 / np.sqrt((v1**2).sum())
    ]
    return U

In [77]:
def get_X_to_V_mapping_matrix(v0, v1):
    """Get the projection matrix that map the coordinate of X space into that in V space.
    Args:
        v0: first basis vector represented using the coordinate in X
        v1: 2nd basis vector represented using the coordinate in X
    """
    return np.linalg.inv(get_basis_vector_matrix_of_V(v0, v1))

In [78]:
def project_X_to_V(X:np.ndarray, V: np.ndarray)-> np.ndarray:
    """Project coordinates in X space into those in V space
    Args:
        X: list of x coordinate (x0, x1) in the shape (N, D) where 
           N is number of data points, D is the demension of a data point x.
        V: X to V mapping matrix
    Returns: list of v coordinate in the shape (N, M)
    """
    N, D = X.shape
    M, _D = V.shape
    assert D == _D, f"expected X.shape=(N, D),V.shape=(M, D) got X:{X.shape}, V:{V.shape}"
    
    U = V @ V.T
    return U    

In [98]:
def apply_matrix_n_times(m: np.ndarray, n: int):
    return np.linalg.matrix_power(m, n)

## Basis vectors of space V

In [113]:
v0 = [1, 1]      # not normalized
v1 = [1, -1]

## Basis vector matrix of spae V

In [114]:
E = get_basis_vector_matrix_of_V(v0, v1)
E

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

## Projection matrix 
Matrix **V** to map the coordinate (x0, x1) in space X to (u0, u1) in V.

In [80]:
V = get_X_to_V_mapping_matrix(v0, v1)
V

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

## Point x_eigen_0

The point is the same with the basis vector of space U, which is the eigen vector of the matrix A whose eigen value is ```lambda_0 = 3```. Hence, applying A n times will not extend it $3^n$ times.

In [115]:
x_eigen_0 = np.array(v0)
x_eigen_0

array([1, 1])

## Transformation in space V

1. Apply $V$ to project the point ```x``` in space X into ```u``` in the space V.
2. Transform ```u``` by applying $D$ n times in space V.
3. Apply $E = V^{-1}$ to project the result $E^n \cdot u$ back into space X.

### Project x into space V

In [116]:
u = np.dot(V, x_eigen_0)
u

array([1.41421356, 0.        ])

### Apply **D** k times

In [121]:
K = 3
u_transferred = np.dot(apply_matrix_n_times(D, K), u)
u_transferred

array([38.18376618,  0.        ])

### Project back into space X

In [122]:
np.dot(E, u_transferred)

array([27., 27.])

# Transformation in space X

This results in the same with transformation result in space **V**.

In [124]:
np.dot(apply_matrix_n_times(A, K), x_eigen_0)

array([27, 27])