In [2]:
import tensorflow as tf
import numpy as np

# Update tf.Variable with Boolean indices

In [7]:
x = tf.Variable(np.random.uniform(-1, 1, size=(3,4)), dtype=tf.float32)
print(f"x:\n{x}\n")

# --------------------------------------------------------------------------------
# Boolean indices with the condition
# --------------------------------------------------------------------------------
mask = x > 0
print(f"Boolean indices (x > 0):\n{mask}\n")

# --------------------------------------------------------------------------------
# Update values in Variable wih boolean indices
# --------------------------------------------------------------------------------
x.assign(tf.where(mask, 1, x))
print(f"x.assign(tf.where(x>0, 1, x)):\n{x}")

x:
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.8369873 , -0.86152446,  0.8997076 ,  0.92364746],
       [ 0.815089  ,  0.89769685,  0.6156549 ,  0.7531403 ],
       [-0.091079  , -0.25003907, -0.92162824,  0.10137004]],
      dtype=float32)>

Boolean indices (x > 0):
[[False False  True  True]
 [ True  True  True  True]
 [False False False  True]]

x.assign(tf.where(x>0, 1, x)):
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.8369873 , -0.86152446,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [-0.091079  , -0.25003907, -0.92162824,  1.        ]],
      dtype=float32)>


# Extract Tensor elements with boolean indices

* [tf.boolean_mask](https://www.tensorflow.org/api_docs/python/tf/boolean_mask)

> Numpy equivalent is tensor[mask].

```
tf.boolean_mask(
    tensor, mask, axis=None, name='boolean_mask'
)
```

In [3]:
def in1d(target, source, invert: bool = False):
    """
    Return boolean tensor of the target shape that tells if an element of
    'target' b is in 'source'.

    Example:
        target = tf.constant([1,2,3,4,5])
        source = tf.constant([1,3,5])
        is_in(target, source)
        -----
        [ True, False,  True, False,  True]

    Args:
        target: Target 1D array to test
        source: list of elements to check if in 'target'
        invert: If True, the values in the returned array are inverted
   """
    mask = tf.reduce_any(tf.equal(tf.reshape(source, shape=(-1, 1)), target), axis=0)
    # return np.in1d(target, source, invert)
    return tf.math.logical_not(mask) if invert else mask

In [7]:
target = tf.constant([1,2,3,4,5])
source = tf.constant([1,3,5])
#a = np.array([1,6,7,8,9])
#b = np.array([1,3,5])
print(f"Select elements from {target} that are not in {source}\n")
boolean_indices = in1d(target, source, True)
print(f"Boolean indices:{boolean_indices}\n")
tf.boolean_mask(target, boolean_indices)

Select elements from [1 2 3 4 5] that are not in [1 3 5]

Boolean indices:[False  True False  True False]



<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>