# map_fn

```map_fn``` iterates through rows (along the **axis 0**) in a Tensor to apply ```fn``` then stacks the results. 

Provide ```fn_output_signature``` argument if ```fn```'s input and output **signatures** are different (e.g dtype or shape are different between input and output).

* [tf.map_fn](https://www.tensorflow.org/api_docs/python/tf/map_fn)

```
tf.map_fn(
    fn,
    elems,
    dtype=None,
    parallel_iterations=None,
    back_prop=True,
    swap_memory=False,
    infer_shape=True,
    name=None,
    fn_output_signature=None
)
```

In [4]:
import numpy as np
import tensorflow as tf

# Example

Convert (x,y) coordinate within a rectanble to a (row, col) coordinate of (S x S) grid of the rectangle. (x, y) are relative to the rectangle size, meaning normalized to a value between 0 and 1.

Meaning divide the rectangle into cells of grid where each side is divided into S sections. Then, find out the grid (row, col) in which a (x,y) coordinate exists.

In [17]:
S = 7
N = 4
D = 2

In [18]:
xy = np.random.random(size=(N,D))
xy

array([[0.99104158, 0.80679893],
       [0.29602966, 0.08578804],
       [0.68821346, 0.46920149],
       [0.82437506, 0.07704665]])

In [19]:
def fn_xy_to_grid_coordinate(x_y):
    grid_row = tf.cast(tf.math.floor(S * x_y[1]), dtype=tf.int32)   # y
    grid_col = tf.cast(tf.math.floor(S * x_y[0]), dtype=tf.int32)   # x
    return tf.stack([grid_row, grid_col], axis=-1)

In [20]:
coordinates = tf.map_fn(
    fn=fn_xy_to_grid_coordinate,
    elems=xy,                               # shape:(n,2)
    fn_output_signature=tf.TensorSpec(
        shape=(2,),                         # Output shape of fn
        dtype=tf.dtypes.int32,
        name=None
    )
)

In [22]:
coordinates   # (row, col) grid coordinate from (x, y)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[5, 6],
       [0, 2],
       [3, 4],
       [0, 5]], dtype=int32)>