# Broadcast

* [tensorflow - Is broadcasting in Tensorflow a view or a copy?
](https://stackoverflow.com/questions/66978119/tensorflow-is-broadcasting-in-tensorflow-a-view-or-a-copy)
* [Introduction to Tensors - Broadcasting](https://www.tensorflow.org/guide/tensor#broadcasting)

> The broadcast operation never materializes the expanded tensors in memory.

* [tf.broadcast()](https://www.tensorflow.org/api_docs/python/tf/broadcast_to)

```
tf.broadcast_to(
    input, shape, name=None
)
```

In [3]:
import tensorflow as tf
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)
