# word2vec implementation

## Original papers
* [Distributed Representations of Words and Phrases and their Compositionality](https://arxiv.org/abs/1310.4546)
* [word2vec Explained: deriving Mikolov et al.'s negative-sampling word-embedding method](https://arxiv.org/abs/1402.3722)



## Overview

The original paper proposed using:
1. Matmul to extract word vectors from ```Win```.
2. Softmax to calculate scores with all the word vectors from ```Wout```.

<img src="image/word2vec_cbow_mechanism.png" align="left"/>

## Negative Sampling

### Motivation

The original implementation was computationally expensive.

1. Matmal to extract word vectors from ```Win```.
2. Softmax can happen vocabulary size times with ```Wout```.

<img src="image/word2vec_negative_sampling_motivation.png" align="left"/>


### Solution

1. Use index to extract word vectors from Win.
2. Instead of calculating softmax with all the word vectors from ```Wout```, sample small number (SL) of negative/false word vectors from ```Wout``` and calculate logistic log loss with each sample. 

<img src="image/wors2vec_neg_sample_backprop.png" align="left"/>

## Using only one Word vector space W

There is no reasoning nor proof why two word vector space are required. In the end, we only use one word vector space, which appears to be ```Win```. 

However, if we use one vector space ```W``` for ```event```, ```context``` and ```negative samples```,then an event vector ```event=W[i]``` in a sentence can be used as a negative sample in another setence. Then the weight ```W[i]``` is updated for both positive and negative labels in the same gradient descent on ```W```. The actual [experiment of using only one vector space](./layer/embedding_single_vector_space.py) ```W``` did not work well.

* [Why do we need 2 matrices for word2vec or GloVe](https://datascience.stackexchange.com/a/94422/68313)


<img src="image/word2vec_why_not_one_W.png" align="left" width=800/>

---
# Setups

In [1]:
import cProfile
import sys
import os
import time
import re
from itertools import islice
from typing import Dict, List
import numpy as np
import tensorflow as tf

np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(linewidth=400) 

## Setup for Google Colab environment

Colab gets disconnected within approx 20 min. Hence not suitable for training (or need to upgrade to the pro version).

### Clone github to Google Drive

In [2]:
try:
    import google.colab
    IN_GOOGLE_COLAB = True
except:
    IN_GOOGLE_COLAB = False
    
if IN_GOOGLE_COLAB:
    !pip install line_profiler
    !google.colab.drive.mount('/content/gdrive')
    !rm -rf /content/drive/MyDrive/github
    !mkdir -p /content/drive/MyDrive/github
    !git clone https://github.com/oonisim/python-programs.git /content/drive/MyDrive/github


### Clone github to local directory

In [3]:
try:
    import google.colab
    IN_GOOGLE_COLAB = True
except:
    IN_GOOGLE_COLAB = False
    
if IN_GOOGLE_COLAB:
    !pip install line_profiler
    !google.colab.drive.mount('/content/gdrive')
    !rm -rf /content/github
    !mkdir -p /content/github
    !git clone https://github.com/oonisim/python-programs.git /content/github
        
    import sys
    sys.path.append('/content/github/nlp/src')

# Jupyter notebook setups

Auto reolaod causes an error in Jupyter notebooks. Restart the Jupyter kernel for the error:
```TypeError: super(type, obj): obj must be an instance or subtype of type```
See
- https://stackoverflow.com/a/52927102/4281353
- http://thomas-cokelaer.info/blog/2011/09/382/

> The problem resides in the mechanism of reloading modules.
> Reloading a module often changes the internal object in memory which
> makes the isinstance test of super return False.

In [4]:
%load_ext line_profiler
%load_ext autoreload

## Utilites

In [5]:
%autoreload 2

def take(n, iterable):
    "Return first n items of the iterable as a list"
    return list(islice(iterable, n))

import function.fileio as fileio
import function.text as text

---
# Data Types


In [6]:
from common.constant import (
    TYPE_INT,
    TYPE_FLOAT,
    TYPE_LABEL,
    TYPE_TENSOR,
)

# Constants

In [7]:
USE_PTB = True
DEBUG = False
VALIDATION = True

TARGET_SIZE = 1   # Size of the target event (word)
CONTEXT_SIZE = 10  # Size of the context.
WINDOW_SIZE = TARGET_SIZE + CONTEXT_SIZE
SAMPLE_SIZE = 5   # Size of the negative samples
VECTOR_SIZE = 100  # Number of features in the event vector.
STATE_FILE = "/home/oonisim/home/repository/git/oonisim/python_programs/nlp/models/word2vec_vecsize_100.pkl"

---

# Data
## Corpus

In [8]:
corpus = "To be, or not to be, that is the question that matters"
_file = "ptb.train.txt"
if USE_PTB:
    if not fileio.Function.is_file(f"~/.keras/datasets/{_file}"):
        path_to_ptb = tf.keras.utils.get_file(
            _file, 
            f'https://raw.githubusercontent.com/tomsercu/lstm/master/data/{_file}'
        )
    corpus = fileio.Function.read_file(path_to_ptb)

In [9]:
examples = corpus.split('\n')[:5]
for line in examples:
    print(line)

 aer banknote berlitz calloway centrust cluett fromstein gitano guterman hydro-quebec ipo kia memotec mlx nahb punts rake regatta rubens sim snack-food ssangyong swapo wachter 
 pierre <unk> N years old will join the board as a nonexecutive director nov. N 
 mr. <unk> is chairman of <unk> n.v. the dutch publishing group 
 rudolph <unk> N years old and former chairman of consolidated gold fields plc was named a nonexecutive director of this british industrial conglomerate 
 a form of asbestos once used to make kent cigarette filters has caused a high percentage of cancer deaths among a group of workers exposed to it more than N years ago researchers reported 


---
# Event (word) indexing
Index the events that have occurred in the event sequence.

In [10]:
%autoreload 2
from layer.preprocessing import (
    EventIndexing, 
)

In [11]:
word_indexing = EventIndexing(
    name="word_indexing_on_ptb",
    corpus=corpus,
    min_sequence_length=WINDOW_SIZE
)
del corpus

## EventIndexing  for the corpus

Adapt to the ```corpus``` and provides:
* event_to_index dictionary
* vocaburary of the corpus
* word occurrence probabilites

In [12]:
words = word_indexing.list_events(range(10))
print(f"EventIndexing.vocabulary[10]:\n{words}\n")

indices = word_indexing.list_indices(words)
print(f"EventIndexing.event_to_index[10]:")
for item in zip(words, indices):
    print(item)

probabilities = word_indexing.list_probabilities(words)
print(f"\nEventIndexing.probabilities[10]:")
for word, p in zip(words, probabilities):
    print(f"{word:20s} : {p:.5e}")

EventIndexing.vocabulary[10]:
['<nil>' '<unk>' 'aer' 'banknote' 'berlitz' 'calloway' 'centrust' 'cluett' 'fromstein' 'gitano']

EventIndexing.event_to_index[10]:
('<nil>', 0)
('<unk>', 1)
('aer', 2)
('banknote', 3)
('berlitz', 4)
('calloway', 5)
('centrust', 6)
('cluett', 7)
('fromstein', 8)
('gitano', 9)

EventIndexing.probabilities[10]:
<nil>                : 0.00000e+00
<unk>                : 1.65308e-02
aer                  : 5.34860e-06
banknote             : 5.34860e-06
berlitz              : 5.34860e-06
calloway             : 5.34860e-06
centrust             : 5.34860e-06
cluett               : 5.34860e-06
fromstein            : 5.34860e-06
gitano               : 5.34860e-06


## Sampling using the probability

Sample events according to their probabilities.

In [13]:
sample = word_indexing.sample(size=5)
print(sample)

['on', 'surgery', 'educational', 'full', 'worried']


## Negative Sampling
Sample events not including those events already sampled.

In [14]:
negative_indices = word_indexing.negative_sample_indices(
    size=5, excludes=word_indexing.list_indices(sample)
)
print(f"negative_indices={negative_indices} \nevents={word_indexing.list_events(negative_indices)}")

negative_indices=[2112, 66, 1989, 779, 3788] 
events=['sony' 'to' 'contributed' 'shore' 'actually']


## Sentence to Sequence

In [15]:
# sentences = "\n".join(corpus.split('\n')[5:6])
sentences = """
the asbestos fiber <unk> is unusually <unk> once it enters the <unk> 
with even brief exposures to it causing symptoms that show up decades later researchers said
"""
sequences = word_indexing.function(sentences)
for pair in zip(sentences.strip().split(" "), sequences[0]):
    print(f"{pair[0]:15} : {pair[1]:5}")

Sentence is empty. Skipping...
Sentence is empty. Skipping...


the             :    34
asbestos        :    63
fiber           :    86
<unk>           :     1
is              :    42
unusually       :    87
<unk>           :     1
once            :    64
it              :    80
enters          :    88
the             :    34
<unk>           :     1

with           :     0
even            :     0
brief           :     0


---
# EventContext

EventContext layer generates ```(event, context)``` pairs from sequences.

In [16]:
%autoreload 2
from layer.preprocessing import (
    EventContext
)

In [17]:
event_context = EventContext(
    name="ev",
    window_size=WINDOW_SIZE,
    event_size=TARGET_SIZE
)

## Context of an event (word) in a sentence

In the sentence ```"a form of asbestos once used to make kent cigarette filters"```, one of the context windows ```a form of asbestos once``` of size 5 and event size 1 has.
* ```of``` as a target word.
* ```(a, form) and (asbestos, once)``` as its context.

### Sequence of the word indices for the sentence

In [18]:
sentences = """
a form of asbestos once used to make kent cigarette filters

N years old and former chairman of consolidated gold fields plc was named a nonexecutive director
"""

sequence = word_indexing.function(sentences)
sequence

Sentence is empty. Skipping...
Sentence is empty. Skipping...
Sentence is empty. Skipping...


array([[37, 62, 44, 63, 64, 65, 66, 67, 68, 69, 70,  0,  0,  0,  0,  0],
       [29, 30, 31, 50, 51, 43, 44, 52, 53, 54, 55, 56, 57, 37, 38, 39]])

## (event, context) pairs

For each word (event) in the setence ```(of, asbestos, ... , kent)``` excludnig the ends of the sentence, create ```(target, context)``` as:

```
[
  [of, a, form, asbestos, once],              # target is 'of', context is (a, form, asbestos, once)
  ['asbestos', 'form', 'of', 'once', 'used'],
  ['once', 'of', 'asbestos', 'used', 'to'],
  ...
]
```

### Format of the (event, context) pairs

* **E** is the target event indices
* **C** is the context indices

<img src="image/event_context_format.png" align="left"/>

In [19]:
event_context_pairs = event_context.function(sequence)
print(
    f"Event context pairs. Shape %s, Target event size %s, Window size %s." % 
    (event_context_pairs.shape, event_context.event_size, event_context.window_size)
)
event_context_pairs[:10]

Event context pairs. Shape (12, 11), Target event size 1, Window size 11.


array([[65, 37, 62, 44, 63, 64, 66, 67, 68, 69, 70],
       [66, 62, 44, 63, 64, 65, 67, 68, 69, 70,  0],
       [67, 44, 63, 64, 65, 66, 68, 69, 70,  0,  0],
       [68, 63, 64, 65, 66, 67, 69, 70,  0,  0,  0],
       [69, 64, 65, 66, 67, 68, 70,  0,  0,  0,  0],
       [70, 65, 66, 67, 68, 69,  0,  0,  0,  0,  0],
       [43, 29, 30, 31, 50, 51, 44, 52, 53, 54, 55],
       [44, 30, 31, 50, 51, 43, 52, 53, 54, 55, 56],
       [52, 31, 50, 51, 43, 44, 53, 54, 55, 56, 57],
       [53, 50, 51, 43, 44, 52, 54, 55, 56, 57, 37]], dtype=int32)

### (event, context) pairs in textual words

In [20]:
word_indexing.sequence_to_sentence(event_context_pairs[:10])

[['used',
  'a',
  'form',
  'of',
  'asbestos',
  'once',
  'to',
  'make',
  'kent',
  'cigarette',
  'filters'],
 ['to',
  'form',
  'of',
  'asbestos',
  'once',
  'used',
  'make',
  'kent',
  'cigarette',
  'filters',
  '<nil>'],
 ['make',
  'of',
  'asbestos',
  'once',
  'used',
  'to',
  'kent',
  'cigarette',
  'filters',
  '<nil>',
  '<nil>'],
 ['kent',
  'asbestos',
  'once',
  'used',
  'to',
  'make',
  'cigarette',
  'filters',
  '<nil>',
  '<nil>',
  '<nil>'],
 ['cigarette',
  'once',
  'used',
  'to',
  'make',
  'kent',
  'filters',
  '<nil>',
  '<nil>',
  '<nil>',
  '<nil>'],
 ['filters',
  'used',
  'to',
  'make',
  'kent',
  'cigarette',
  '<nil>',
  '<nil>',
  '<nil>',
  '<nil>',
  '<nil>'],
 ['chairman',
  'n',
  'years',
  'old',
  'and',
  'former',
  'of',
  'consolidated',
  'gold',
  'fields',
  'plc'],
 ['of',
  'years',
  'old',
  'and',
  'former',
  'chairman',
  'consolidated',
  'gold',
  'fields',
  'plc',
  'was'],
 ['consolidated',
  'old',
  'and'

---
# Word Embedding

Embedding is to train the model to group similar events in a close proximity in the event vector space. If two events e.g. 'pencil' and 'pen' are similar concepts, then their event vectors resides in a close distance in the event space. 

* [Thought Vectors](https://wiki.pathmind.com/thought-vectors)

## Training process

1. Calculate ```Bc```, the BoW (Bag of Words) from context event vectors.
2. Calculate ```Be```,  the BoW (Bag of Words) from target event vectors.
3. The dot product ```Ye = dot(Bc, Be)``` is given the label 1 to get them closer.
4. For each negative sample ```Ws(s)```, the dot product with ```Ys = dot(Be, Ws(s)``` is given the label 0 to get them apart. 
5. ```np.c_[Ye, Ys]``` is fowarded to the logistic log loss layer.

<img src="image/word2vec_backprop_Be.png" align="left"/>


In [21]:
%autoreload 2
from layer import (
    Embedding
)
from optimizer import (
    SGD
)

In [22]:
embedding: Embedding = Embedding(
    name="embedding",
    num_nodes=WINDOW_SIZE,
    target_size=TARGET_SIZE,
    context_size=CONTEXT_SIZE,
    negative_sample_size=SAMPLE_SIZE,
    event_vector_size=VECTOR_SIZE,
    optimizer=SGD(lr=TYPE_FLOAT(0.3)),
    dictionary=word_indexing
)

### Scores ```np.c_[Ye, Ys]``` from the Embedding

The 0th column is the scores for ```dot(Bc, Be``` for positive labels. The rest are the scores for ```dot(Bc, Ws)``` for negative labels.

In [23]:
scores = embedding.function(event_context_pairs)
print(f"Scores:\n{scores[:5]}\n")
print(f"Scores for dot(Bc, Be): \n{scores[:5, :1]}")

Scores:
[[ 2.8448356e-03 -4.6626781e-04 -1.0513982e-03 -3.1637019e-03 -7.7288365e-05  9.3030103e-05]
 [-1.8796960e-03 -7.1030618e-03 -1.3254826e-03  2.5461549e-03 -1.7686044e-03 -1.0504745e-03]
 [ 6.2393253e-03 -1.6674981e-03  3.5888143e-04  4.0004007e-04  1.3552639e-03  1.2281188e-03]
 [ 1.1894747e-04  3.4915728e-03  1.0206593e-03 -6.8337061e-03  2.8054942e-03  2.2942876e-04]
 [-4.2786673e-03 -3.6547363e-03 -4.2858580e-04 -4.0217284e-03 -1.5611844e-03 -5.2395929e-03]]

Scores for dot(Bc, Be): 
[[ 0.00284484]
 [-0.0018797 ]
 [ 0.00623933]
 [ 0.00011895]
 [-0.00427867]]


In [24]:
tf.constant([1,2,3]).numpy().ravel()

array([1, 2, 3], dtype=int32)

---
# Logistic Log Loss

Train the model to get:
1. BoW of the context event vectors close to the target event vector. Label 1
2. BoW of the context event vectors away from each of the negative sample event vectors Label 0.

This is a binary logistic classification, hence use Logistic Log Loss as the network objective function.

In [25]:
from common.function import (
    sigmoid_cross_entropy_log_loss,
    sigmoid
)
from layer.objective import (
    CrossEntropyLogLoss
)

In [26]:
loss = CrossEntropyLogLoss(
    name="loss",
    num_nodes=1,  # Logistic log loss
    log_loss_function=sigmoid_cross_entropy_log_loss
)

---
# Adapter

The logistic log loss layer expects the input of shape ```(N,M=1)```, however Embedding outputs ```(N,(1+SL)``` where ```SL``` is SAMPLE_SIZE. The ```Adapter``` layer bridges between Embedding and the Loss layers.


In [27]:
from layer.adapter import (
    Adapter
)

In [28]:
adapter_function = embedding.adapt_function_to_logistic_log_loss(loss=loss)
adapter_gradient = embedding.adapt_gradient_to_logistic_log_loss()

adapter: Adapter = Adapter(
    name="adapter",
    num_nodes=1,    # Number of output M=1 
    function=adapter_function,
    gradient=adapter_gradient
)

---
# Word2vec Network

## Construct a sequential network

$ \text {Sentences} \rightarrow EventIndexing \rightarrow EventContext \rightarrow  Embedding \rightarrow Adapter \rightarrow LogisticLogLoss$

In [29]:
from network.sequential import (
    SequentialNetwork
)

In [30]:
network = SequentialNetwork(
    name="word2vec",
    num_nodes=1,
    inference_layers=[
        word_indexing,
        event_context,
        embedding,
        adapter
    ],
    objective_layers=[
        loss
    ]
)

## Run training

### Load the saved model file if exists

In [31]:
if fileio.Function.is_file(STATE_FILE):
    print("Loading model...\nSTATE_FILE: %s" % STATE_FILE)
    state = embedding.load(STATE_FILE)

    fmt="""Model loaded.
    event_size %s
    context_size: %s
    event_vector_size: %s
    """
    print(fmt % (
        state["target_size"], 
        state["context_size"], 
        state["event_vector_size"]
    ))
else:
    print("State file does not exist. Saving the initial model.")
    embedding.save(STATE_FILE)

Loading model...
STATE_FILE: /home/oonisim/home/repository/git/oonisim/python_programs/nlp/models/word2vec_vecsize_100.pkl
Model loaded.
    event_size 1
    context_size: 10
    event_vector_size: 100
    


### Continue training

In [32]:
NUM_SENTENCES = 50
MAX_ITERATIONS = 100000

def sentences_generator(path_to_file, num_sentences):
    stream = fileio.Function.file_line_stream(path_to_file)
    try:
        while True:
            _lines = fileio.Function.take(num_sentences, stream)
            yield np.array(_lines)
    finally:
        stream.close()

# Sentences for the trainig
path_to_input = path_to_ptb
source = sentences_generator(
    path_to_file=path_to_input, num_sentences=NUM_SENTENCES
)

# Restore the state if exists.
state = embedding.load(STATE_FILE)

# Continue training
profiler = cProfile.Profile()
profiler.enable()

total_sentences = 0
epochs = 0

for i in range(MAX_ITERATIONS):
    try:
        sentences = next(source)
        total_sentences += len(sentences)

        start = time.time()
        network.train(X=sentences, T=np.array([0]))

        if i % 100 == 0:
            print(
                f"Batch {i:05d} of {NUM_SENTENCES} sentences: "
                f"Average Loss: {np.mean(network.history):10f} "
                f"Duration {time.time() - start:3f}"
            )
        if i % 10 == 0:
            embedding.save(STATE_FILE)
        
    except fileio.Function.GenearatorHasNoMore as e:
        # Next epoch
        print(f"epoch {epochs} batches {i:05d} done")
        print(f"Average loss: {np.mean(network.history):15f}")
        epochs += 1
        source.close()
        source = sentences_generator(
            path_to_file=path_to_input, num_sentences=NUM_SENTENCES
        )

    except Exception as e:
        print("Unexpected error:", sys.exc_info()[0])
        source.close()
        raise e

embedding.save(STATE_FILE)

profiler.disable()
profiler.print_stats(sort="cumtime")

Batch 00000 of 50 sentences: Average Loss:   0.288738 Duration 0.785595
Batch 00100 of 50 sentences: Average Loss:   0.263785 Duration 0.821840
Batch 00200 of 50 sentences: Average Loss:   0.261323 Duration 0.686028
Batch 00300 of 50 sentences: Average Loss:   0.259980 Duration 0.873889
Batch 00400 of 50 sentences: Average Loss:   0.258004 Duration 0.696118
Batch 00500 of 50 sentences: Average Loss:   0.255848 Duration 0.872351
Batch 00600 of 50 sentences: Average Loss:   0.255005 Duration 0.538219
Batch 00700 of 50 sentences: Average Loss:   0.254163 Duration 0.502189
Batch 00800 of 50 sentences: Average Loss:   0.253061 Duration 0.586886
epoch 0 batches 00842 done
Average loss:        0.252672
Batch 00900 of 50 sentences: Average Loss:   0.252699 Duration 0.659787
Batch 01000 of 50 sentences: Average Loss:   0.252112 Duration 0.754639
Batch 01100 of 50 sentences: Average Loss:   0.252105 Duration 0.731786
Batch 01200 of 50 sentences: Average Loss:   0.251873 Duration 0.536669
Batch 0

Batch 10600 of 50 sentences: Average Loss:   0.242228 Duration 0.560842
Batch 10700 of 50 sentences: Average Loss:   0.242183 Duration 0.653175
Batch 10800 of 50 sentences: Average Loss:   0.242163 Duration 0.545556
Batch 10900 of 50 sentences: Average Loss:   0.242107 Duration 0.495770
epoch 12 batches 10958 done
Average loss:        0.242058
Batch 11000 of 50 sentences: Average Loss:   0.242065 Duration 0.680079
Batch 11100 of 50 sentences: Average Loss:   0.242017 Duration 0.492269
Batch 11200 of 50 sentences: Average Loss:   0.242026 Duration 0.565234
Batch 11300 of 50 sentences: Average Loss:   0.241996 Duration 0.861460
Batch 11400 of 50 sentences: Average Loss:   0.241951 Duration 0.655205
Batch 11500 of 50 sentences: Average Loss:   0.241890 Duration 0.427369
Batch 11600 of 50 sentences: Average Loss:   0.241871 Duration 0.551649
Batch 11700 of 50 sentences: Average Loss:   0.241832 Duration 0.852637
Batch 11800 of 50 sentences: Average Loss:   0.241748 Duration 0.249130
epoch 

epoch 24 batches 21074 done
Average loss:        0.239115
Batch 21100 of 50 sentences: Average Loss:   0.239117 Duration 0.706414
Batch 21200 of 50 sentences: Average Loss:   0.239099 Duration 0.722414
Batch 21300 of 50 sentences: Average Loss:   0.239084 Duration 0.895724
Batch 21400 of 50 sentences: Average Loss:   0.239066 Duration 0.599506
Batch 21500 of 50 sentences: Average Loss:   0.239044 Duration 0.274326
Batch 21600 of 50 sentences: Average Loss:   0.238998 Duration 0.535940
Batch 21700 of 50 sentences: Average Loss:   0.238987 Duration 0.587002
Batch 21800 of 50 sentences: Average Loss:   0.238958 Duration 0.693025
Batch 21900 of 50 sentences: Average Loss:   0.238919 Duration 0.604217
epoch 25 batches 21917 done
Average loss:        0.238913
Batch 22000 of 50 sentences: Average Loss:   0.238899 Duration 0.524585
Batch 22100 of 50 sentences: Average Loss:   0.238884 Duration 0.511303
Batch 22200 of 50 sentences: Average Loss:   0.238872 Duration 0.710792
Batch 22300 of 50 se

Batch 31500 of 50 sentences: Average Loss:   0.236908 Duration 0.690712
Batch 31600 of 50 sentences: Average Loss:   0.236886 Duration 0.478841
Batch 31700 of 50 sentences: Average Loss:   0.236855 Duration 0.578388
Batch 31800 of 50 sentences: Average Loss:   0.236840 Duration 0.593733
Batch 31900 of 50 sentences: Average Loss:   0.236817 Duration 0.360845
Batch 32000 of 50 sentences: Average Loss:   0.236787 Duration 0.387591
epoch 37 batches 32033 done
Average loss:        0.236778
Batch 32100 of 50 sentences: Average Loss:   0.236769 Duration 0.597708
Batch 32200 of 50 sentences: Average Loss:   0.236752 Duration 0.686003
Batch 32300 of 50 sentences: Average Loss:   0.236745 Duration 0.589600
Batch 32400 of 50 sentences: Average Loss:   0.236736 Duration 0.561581
Batch 32500 of 50 sentences: Average Loss:   0.236694 Duration 0.566597
Batch 32600 of 50 sentences: Average Loss:   0.236676 Duration 0.514654
Batch 32700 of 50 sentences: Average Loss:   0.236660 Duration 0.609902
Batch 

Batch 42000 of 50 sentences: Average Loss:   0.234933 Duration 0.423516
Batch 42100 of 50 sentences: Average Loss:   0.234907 Duration 0.492759
epoch 49 batches 42149 done
Average loss:        0.234894
Batch 42200 of 50 sentences: Average Loss:   0.234893 Duration 0.643545
Batch 42300 of 50 sentences: Average Loss:   0.234869 Duration 0.643559
Batch 42400 of 50 sentences: Average Loss:   0.234866 Duration 0.571243
Batch 42500 of 50 sentences: Average Loss:   0.234854 Duration 0.512357
Batch 42600 of 50 sentences: Average Loss:   0.234829 Duration 0.530386
Batch 42700 of 50 sentences: Average Loss:   0.234809 Duration 0.671252
Batch 42800 of 50 sentences: Average Loss:   0.234795 Duration 0.553913
Batch 42900 of 50 sentences: Average Loss:   0.234773 Duration 0.624893
epoch 50 batches 42992 done
Average loss:        0.234747
Batch 43000 of 50 sentences: Average Loss:   0.234746 Duration 0.567007
Batch 43100 of 50 sentences: Average Loss:   0.234730 Duration 0.569697
Batch 43200 of 50 se

Batch 52400 of 50 sentences: Average Loss:   0.233160 Duration 0.817258
Batch 52500 of 50 sentences: Average Loss:   0.233149 Duration 0.747409


KeyboardInterrupt: 

---
# Evaluate the vector space

Verify if the trained model, or the vector space W, has encoded the words in a way that **similar** words are close in the vector space.

* [How to measure the similarity among vectors](https://math.stackexchange.com/questions/4132458)

In [ ]:
n = 10
context = "cash".split()
word_indices = np.array(word_indexing.list_indices(context), dtype=TYPE_INT)

print(f"Words {context}")
print(f"Word indices {word_indices}")
print(f"prediction for {context}:\n{word_indexing.list_events([embedding.predict(word_indices, n)])}")

In [ ]:
np.zeros(shape=(141, 11))

In [ ]:
---
## Compare with [gensim word2vec](https://radimrehurek.com/gensim/models/word2vec.html)

In [ ]:
from gensim.models import (
    Word2Vec
)
from gensim.models.word2vec import (
    LineSentence    
)

In [ ]:
sentences = LineSentence(source=path_to_ptb)
w2v = Word2Vec(
    sentences=sentences, 
    sg=0,
    window=5, 
    negative=5,
    vector_size=100, 
    min_count=1, 
    workers=4
)
del sentences

In [ ]:
w2v.wv.most_similar(context, topn=n)