In [1]:
import numpy as np

In [49]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(linewidth=1000) 

In [16]:
a = np.zeros(5 * 3).reshape(3, 5)
b = a
print(a)
print (np.may_share_memory(a, b))
a[
    1:4:3,
    (1,2)
] = 1
#c = 1
print (np.may_share_memory(a, b))
print(a)
print(b)
a[1:4:3, (1,2)] = np.dot(a[1:4:3, (1,2)], 0)
print(a)
print (np.may_share_memory(a, b))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
True
True
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
True


In [36]:

X = np.random.randn(10, 8)
X[
    ::,
    0
] = 0

out = np.copy(X)
Y = out

N = X.shape[0]
mean = np.sum(X, axis=0) / N    # mean of each feature
deviation = X - mean
variance = np.var(X, axis=0)
sd = np.sqrt(variance)

mask = (sd == 0.0)
print(mask)
if np.any(mask):
    # Temporary replace the zero elements with one
    sd[mask] = 1.0

    # reuse deviation memory area
    out = deviation if out is None else out

    # standardize and zero clear the mask elements
    standardized = np.divide(deviation, sd, out)
    out[::, mask] = 0.0

    # restore sd
    sd[mask] = 0.0

else:
    standardized = np.divide(deviation, sd, out)

assert np.all(np.isfinite(standardized))
print (np.may_share_memory(a, b))



[ True False False False False False False False]
True


array([[ 0.        ,  0.63401531, -0.02272114, -1.32074605, -0.37547971,  1.24397671,  0.04377315, -0.85318264],
       [ 0.        ,  1.39898499, -0.94798154, -0.46228464, -0.74397546, -0.1951366 ,  0.13388639,  1.36570077],
       [ 0.        , -0.21252002, -0.05020735,  0.1509649 ,  0.49312099, -0.22747285,  0.11895831, -0.11739548],
       [ 0.        ,  1.25931439, -1.06279398, -0.4665774 ,  1.92634438,  1.2646767 ,  1.18250327, -0.57750535],
       [ 0.        , -0.60484621,  0.49956358,  0.36734102, -1.61717771, -1.79568549, -0.44486284, -1.28799455],
       [ 0.        ,  1.27204747, -0.86128076,  1.50000584,  1.19194821,  0.37859158, -1.44311422,  1.61931129],
       [ 0.        , -0.43778543,  1.15454473,  1.10723193, -0.40478027,  0.81581754, -1.79623246,  0.01655473],
       [ 0.        , -0.7530228 ,  2.26612817, -1.03240685, -0.47595658, -1.55076569,  1.09041356,  0.01640809],
       [ 0.        , -1.26981086, -0.6170983 ,  1.32571566, -0.67714719, -0.36878714, -0.2333929

In [37]:
np.std([1], ddof=1)

/home/oonisim/conda/envs/python_programs/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/oonisim/conda/envs/python_programs/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [51]:
num_nodes = 5
D = 10
W = np.random.rand(num_nodes, D)
W = np.c_[
    np.random.uniform(-1, 1, num_nodes),
    W
]
W.shape

(5, 11)

In [2]:
import numpy as np
1 / np.sqrt(1e-8)

10000.0

In [6]:
N = 5
M = 3
row = np.random.uniform(
    -5, 5, M
).astype(float)
X = np.ones((N, M)) * row
X

array([[-3.9845306 , -2.98058358,  2.45351387],
       [-3.9845306 , -2.98058358,  2.45351387],
       [-3.9845306 , -2.98058358,  2.45351387],
       [-3.9845306 , -2.98058358,  2.45351387],
       [-3.9845306 , -2.98058358,  2.45351387]])

In [17]:
X = np.array([
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096]
])

mean = np.mean(X, axis=0)
print(f"mean is \n{mean}\nX-mean is \n{X-mean}\n")


mean is 
[-1.11793447 -3.29686744 -3.50615096]
X-mean is 
[[0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]]


In [25]:
import numpy as np
import numexpr as ne

out = np.random.uniform(size=(3,2))
bak = np.copy(out)
ne.evaluate("out * out / log(out) +out", out=out)
Y = bak * bak / np.log(bak) + bak

out-Y

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
N = 3
M = 3

Xstd = np.random.uniform(size=(N,M))
_dXstd = np.random.uniform(size=(N,M))
_Xmd = Xstd - _dXstd
_dU = np.random.uniform(size=M)
_dV = np.random.uniform(size=M)
norm = 1 / np.std(Xstd)
gamma = np.ones(M)
__N = N
__ddof = 1 if __N > 1 else 0
__Xstd = Xstd
__dXstd = _dXstd
__Xmd = _Xmd
__dU = _dU
__dV = _dV
__norm = norm
__gamma = gamma

ne.evaluate("sum(-2 * __Xmd, axis=0)", out=_dU)
ne.evaluate("__dV / (__N - __ddof) * __dU", out=_dU)
__dU += ne.evaluate("sum(-1 * __dXstd, axis=0)")


In [ ]:
# --------------------------------------------------------------------------------
# dL/dU: (M,) = [ dL/dV:(M,) / (N-ddof) * sum(-2 * Xmd:(N,M), axis=0) ]
#             + [ sum(-dL/dXstd, axis=0) * norm ]
# Bessel's correction (N-ddof), see https://github.com/pytorch/pytorch/issues/1410
# --------------------------------------------------------------------------------

dU = __dV / (__N - __ddof) *  np.sum(-2 * __Xmd, axis=0) + 

In [35]:
a = np.empty((1,5), dtype=float)
a.prod()

0.0

In [46]:
X = np.array([[-2.06943465], 
 [ 0.27749823]])

sd = np.std(X, ddof=1, axis=0)
print(sd)
print(X- X.mean(axis=0))
(X - X.mean(axis=0)) / sd

[1.65953215]
[[-1.17346644]
 [ 1.17346644]]


array([[-0.70710678],
       [ 0.70710678]])

In [7]:
import numpy as np
X = np.random.randn(5, 5)
C = np.max(X, axis=-1)
exp = np.exp(X - C)
exp / np.sum(exp, axis=-1)

array([[0.09932131, 0.076589  , 1.88107042, 0.04163856, 0.09689739],
       [0.04624003, 0.21267103, 1.48257451, 0.07220712, 0.5514739 ],
       [0.02382374, 0.05013574, 0.22579799, 0.01821803, 0.23476214],
       [0.38943193, 0.10265627, 0.32329405, 0.0484258 , 0.5522042 ],
       [0.01895629, 0.03660251, 1.33710658, 0.10686229, 0.07089991]])

In [8]:
C = np.max(X, axis=-1, keepdims=True)
exp = np.exp(X - C)
exp / np.sum(exp, axis=-1, keepdims=True)


array([[0.1473607 , 0.26178298, 0.42508343, 0.09206111, 0.07371177],
       [0.04012672, 0.42516697, 0.19595748, 0.0933763 , 0.24537252],
       [0.07416356, 0.35955366, 0.10706081, 0.08451293, 0.37470903],
       [0.3779202 , 0.22950374, 0.0477855 , 0.07003039, 0.27476016],
       [0.03772157, 0.16779651, 0.40525855, 0.31688521, 0.07233816]])

In [2]:
isinstance(1.0, (int, float))

True