In [1]:
import numpy as np

In [2]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(linewidth=1000) 

In [3]:
a = np.zeros(5 * 3).reshape(3, 5)
b = a
print(a)
print (np.may_share_memory(a, b))
a[
    1:4:3,
    (1,2)
] = 1
#c = 1
print (np.may_share_memory(a, b))
print(a)
print(b)
a[1:4:3, (1,2)] = np.dot(a[1:4:3, (1,2)], 0)
print(a)
print (np.may_share_memory(a, b))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
True
True
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
True


In [4]:

X = np.random.randn(10, 8)
X[
    ::,
    0
] = 0

out = np.copy(X)
Y = out

N = X.shape[0]
mean = np.sum(X, axis=0) / N    # mean of each feature
deviation = X - mean
variance = np.var(X, axis=0)
sd = np.sqrt(variance)

mask = (sd == 0.0)
print(mask)
if np.any(mask):
    # Temporary replace the zero elements with one
    sd[mask] = 1.0

    # reuse deviation memory area
    out = deviation if out is None else out

    # standardize and zero clear the mask elements
    standardized = np.divide(deviation, sd, out)
    out[::, mask] = 0.0

    # restore sd
    sd[mask] = 0.0

else:
    standardized = np.divide(deviation, sd, out)

assert np.all(np.isfinite(standardized))
print (np.may_share_memory(a, b))



[ True False False False False False False False]
True


In [5]:
np.std([1], ddof=1)

/home/oonisim/conda/envs/python_programs/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/oonisim/conda/envs/python_programs/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [6]:
num_nodes = 5
D = 10
W = np.random.rand(num_nodes, D)
W = np.c_[
    np.random.uniform(-1, 1, num_nodes),
    W
]
W.shape

(5, 11)

In [7]:
import numpy as np
1 / np.sqrt(1e-8)

10000.0

In [8]:
N = 5
M = 3
row = np.random.uniform(
    -5, 5, M
).astype(float)
X = np.ones((N, M)) * row
X

array([[-3.37883362,  3.9863536 ,  1.30455143],
       [-3.37883362,  3.9863536 ,  1.30455143],
       [-3.37883362,  3.9863536 ,  1.30455143],
       [-3.37883362,  3.9863536 ,  1.30455143],
       [-3.37883362,  3.9863536 ,  1.30455143]])

In [9]:
X = np.array([
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096]
])

mean = np.mean(X, axis=0)
print(f"mean is \n{mean}\nX-mean is \n{X-mean}\n")


mean is 
[-1.11793447 -3.29686744 -3.50615096]
X-mean is 
[[0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]]



In [10]:
import numpy as np
import numexpr as ne

out = np.random.uniform(size=(3,2))
bak = np.copy(out)
ne.evaluate("out * out / log(out) +out", out=out)
Y = bak * bak / np.log(bak) + bak

out-Y

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
N = 3
M = 3

Xstd = np.random.uniform(size=(N,M))
_dXstd = np.random.uniform(size=(N,M))
_Xmd = Xstd - _dXstd
_dU = np.random.uniform(size=M)
_dV = np.random.uniform(size=M)
norm = 1 / np.std(Xstd)
gamma = np.ones(M)
__N = N
__ddof = 1 if __N > 1 else 0
__Xstd = Xstd
__dXstd = _dXstd
__Xmd = _Xmd
__dU = _dU
__dV = _dV
__norm = norm
__gamma = gamma

ne.evaluate("sum(-2 * __Xmd, axis=0)", out=_dU)
ne.evaluate("__dV / (__N - __ddof) * __dU", out=_dU)
__dU += ne.evaluate("sum(-1 * __dXstd, axis=0)")


In [12]:
# --------------------------------------------------------------------------------
# dL/dU: (M,) = [ dL/dV:(M,) / (N-ddof) * sum(-2 * Xmd:(N,M), axis=0) ]
#             + [ sum(-dL/dXstd, axis=0) * norm ]
# Bessel's correction (N-ddof), see https://github.com/pytorch/pytorch/issues/1410
# --------------------------------------------------------------------------------

dU = __dV / (__N - __ddof) *  np.sum(-2 * __Xmd, axis=0) + 

SyntaxError: invalid syntax (<ipython-input-12-0d900d4c2274>, line 7)

In [ ]:
a = np.empty((1,5), dtype=float)
a.prod()

In [ ]:
X = np.array([[-2.06943465], 
 [ 0.27749823]])

sd = np.std(X, ddof=1, axis=0)
print(sd)
print(X- X.mean(axis=0))
(X - X.mean(axis=0)) / sd

In [ ]:
import numpy as np
X = np.random.randn(5, 5)
C = np.max(X, axis=-1)
exp = np.exp(X - C)
exp / np.sum(exp, axis=-1)

In [ ]:
C = np.max(X, axis=-1, keepdims=True)
exp = np.exp(X - C)
exp / np.sum(exp, axis=-1, keepdims=True)


In [ ]:
isinstance(1.0, (int, float))

In [19]:
_HOGE = 1
class hoge:
    def __init__(
            self,
            name: str,
            num_nodes: int,
            momentum = 0.9,
    ):
        self.args = set(locals().keys())
        global _HOGE
        print(_HOGE)

a = hoge(name="name", num_nodes=1)

1


In [15]:
__HOGE = 1
class hoge:
    def __init__(
            self,
            name: str,
            num_nodes: int,
            momentum = 0.9,
    ):
        self.args = set(locals().keys())
        global __HOGE
        print(__HOGE)


In [16]:
a = hoge(name="name", num_nodes=1)

NameError: name '_hoge__HOGE' is not defined

In [ ]:
sig = inspect.signature(hoge.__init__)
for param in sig.parameters.values():
        print(f'Parameter: {param} param.default {param.default} {param.default is param.empty}')

In [ ]:
a = {
    "num_nodes": 8,
    "num_features": 3,
    "weights": {
        "scheme": "he"
    },
    "optimizer": {
        "lr": 0.1,
        "l2": 0.1
    }
}
a = set(a.keys())
set(['num_nodes', 'num_features', 'weights', 'optimizer']).issubset(a)
#b.issubset(a)

In [4]:
isinstance([], list)

True

In [23]:
network_specification = {
    "matmul01": {
        "scheme": "hoge",
        "parameters": {
            "num_nodes": 8,
            "num_features": 2,  # NOT including bias
            "weights": {
                "scheme": "he"
            },
            "optimizer": {
        "scheme": "hoge",
                "lr": 0.01,
                "l2": 1e-3
            }
        },
    },
    "activation01": {
        "scheme": "hoge",
        "parameters": {
            "num_nodes": 8
        }
    },
    "matmul02": {
        "scheme": "hoge",
        "parameters": {
            "num_nodes": 3,
            "num_features": 8,  # NOT including bias
            "weights": {
                "scheme": "he"
            }
        }
    },
    "activation02": {
        "scheme": "hoge",
        "parameters": {
            "num_nodes": 3
        }
    },
    "objective": {
        "scheme": "hoge",
        "parameters": {
            "num_nodes": 3,
            "loss_function": "softmax_cross_entropy_log_loss"
        }
    }
}

In [24]:
network_specification[-1]

KeyError: -1

In [27]:
import numpy as np
n=3
m=5
a = np.random.rand(n,m)
b = np.random.rand(n,m)
c = np.random.rand(n,m)
np.sum([a,b,c], axis=0)

20.195963183191576

In [28]:
_NAME = "name"
_NUM_NODES = "num_nodes"
_NUM_FEATURES = "num_features"
_WEIGHTS = "weights"
_OPTIMIZER = "optimizer"
_SCHEME = "scheme"
_PARAMETERS = "parameters"
_LOG_LEVEL = "log_level"
_LAYER_CLASS = "layer_class"
_LOSS_FUNCTION = "loss_function"
_LAYERS = "layers"
_COMPOSITE_LAYER_SPEC = "composite_layer_specification"

LOG_LOSS_GRADIENT_ACCEPTANCE_VALUE = float(1.2)

a = {
    "matmul02": {
        _PARAMETERS: {
            _NAME: "matmul02",
            _NUM_NODES: 3,
            _NUM_FEATURES: 8,  # NOT including bias
            _WEIGHTS: {
                _SCHEME: "he"
            }
        }
    }
}
a["matmul02"][_PARAMETERS][_NUM_NODES]

3

In [30]:
import numpy as np
a = [1,2,3]
f = lambda x: np.sum(x)
f(a)

6

In [35]:
a = np.arange(60).reshape((3,4,-1))
print(a[0].shape)
b = np.sum(a, axis=0, keepdims=False)
b.shape

(4, 5)


(4, 5)

In [40]:
X = np.array(1)
shape_Y = X[0].shape if X.ndim > 0 else ()
_Y = np.empty(shape_Y, dtype=float)
np.sum(X, out=_Y)

array(1.)

In [36]:
a = np.arange(60).reshape((3,4,-1))
shape = a[0].shape
Y = np.empty(shape)
np.sum(a, axis=0, out=Y)


array([[ 60.,  63.,  66.,  69.,  72.],
       [ 75.,  78.,  81.,  84.,  87.],
       [ 90.,  93.,  96.,  99., 102.],
       [105., 108., 111., 114., 117.]])

In [4]:
index = 1
f"matmul{index:03d}"

'matmul001'