In [1]:
import numpy as np
import tensorflow as tf

In [4]:
x = tf.constant((1,2))
x = x[x > 1]
x

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

In [4]:
a = np.arange(12).reshape(1,3,4)
b = np.arange(3).reshape(1,3,1)
print(a)
print(b)
np.einsum("ncd,ncd->nd", a, b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[0]
  [1]
  [2]]]


array([[20, 23, 26, 29]])

In [25]:
bbc_world_us_canada_56988381 = """
Mr Biden said at the White House on Monday: 'In two months let's celebrate independence as a nation and our independence from this virus. We can do this. We will do this.
The Democratic president also announced a new website, vaccines.gov, that Americans can use to more easily find vaccination sites after widespread complaints that the sign-up process was too difficult for some.
"""


len(bbc_world_us_canada_56988381.split(' '))

def max_line_in_sentences(sentences):
    from common.constant import (
        EOL,
        SPACE
    )

    max_length = 0
    for line in sentences.split('\n'):
        sentence = standardize(line)
        max_length = max(max_length, len(sentence.split(' ')))

    return max_length

max_line_in_sentences(bbc_world_us_canada_56988381)

AssertionError: 

In [2]:
class Hoge:
    def __init__(self):
        self._attr = "tako"

    def rm(self):
        del self._attr


In [3]:
hoge = Hoge()
hoge.rm()

In [9]:
x = np.array([1], dtype=np.float32)

TypeError: isinstance() arg 2 must be a type or tuple of types

In [20]:
def is_same_dtype(dtype_a, dtype_b):
    return tf.dtypes.as_dtype(dtype_a) == tf.dtypes.as_dtype(dtype_b)


In [21]:
is_same_dtype(x.dtype, np.int32)

False

In [13]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(linewidth=1000) 

In [30]:
indices= (1,3,5,7)
indices = range(1, 8, 2)
X = np.arange(15)
X[list(iter(indices))]

array([1, 3, 5, 7])

In [23]:
value = ["a", "b", "c"]
X = tf.convert_to_tensor(
    value, dtype=None, dtype_hint=None, name=None
)
X[0] == "a"

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [3]:
import re
import string

In [11]:
UNK="<UNK>"
rf'(?:(?!{UNK.lower()})[\W_](?<!{UNK.lower()}))+'

'(?:(?!<unk>)[\\W_](?<!<unk>))+'

'(?:(?!<a>)[\\W_](?<!<unk>))+'

In [3]:
a = np.zeros(5 * 3).reshape(3, 5)
b = a
print(a)
print (np.may_share_memory(a, b))
a[
    1:4:3,
    (1,2)
] = 1
#c = 1
print (np.may_share_memory(a, b))
print(a)
print(b)
a[1:4:3, (1,2)] = np.dot(a[1:4:3, (1,2)], 0)
print(a)
print (np.may_share_memory(a, b))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
True
True
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
True


In [4]:

X = np.random.randn(10, 8)
X[
    ::,
    0
] = 0

out = np.copy(X)
Y = out

N = X.shape[0]
mean = np.sum(X, axis=0) / N    # mean of each feature
deviation = X - mean
variance = np.var(X, axis=0)
sd = np.sqrt(variance)

mask = (sd == 0.0)
print(mask)
if np.any(mask):
    # Temporary replace the zero elements with one
    sd[mask] = 1.0

    # reuse deviation memory area
    out = deviation if out is None else out

    # standardize and zero clear the mask elements
    standardized = np.divide(deviation, sd, out)
    out[::, mask] = 0.0

    # restore sd
    sd[mask] = 0.0

else:
    standardized = np.divide(deviation, sd, out)

assert np.all(np.isfinite(standardized))
print (np.may_share_memory(a, b))



[ True False False False False False False False]
True


In [5]:
np.std([1], ddof=1)

/home/oonisim/conda/envs/tensorflow/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/oonisim/conda/envs/tensorflow/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [6]:
num_nodes = 5
D = 10
W = np.random.rand(num_nodes, D)
W = np.c_[
    np.random.uniform(-1, 1, num_nodes),
    W
]
W.shape

(5, 11)

In [7]:
import numpy as np
1 / np.sqrt(1e-8)

10000.0

In [8]:
N = 5
M = 3
row = np.random.uniform(
    -5, 5, M
).astype(float)
X = np.ones((N, M)) * row
X

array([[-3.91429608,  2.22784998, -3.54335084],
       [-3.91429608,  2.22784998, -3.54335084],
       [-3.91429608,  2.22784998, -3.54335084],
       [-3.91429608,  2.22784998, -3.54335084],
       [-3.91429608,  2.22784998, -3.54335084]])

In [9]:
X = np.array([
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096]
])

mean = np.mean(X, axis=0)
print(f"mean is \n{mean}\nX-mean is \n{X-mean}\n")


mean is 
[-1.11793447 -3.29686744 -3.50615096]
X-mean is 
[[0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]]



In [10]:
import numpy as np
import numexpr as ne

out = np.random.uniform(size=(3,2))
bak = np.copy(out)
ne.evaluate("out * out / log(out) +out", out=out)
Y = bak * bak / np.log(bak) + bak

out-Y

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
N = 3
M = 3

Xstd = np.random.uniform(size=(N,M))
_dXstd = np.random.uniform(size=(N,M))
_Xmd = Xstd - _dXstd
_dU = np.random.uniform(size=M)
_dV = np.random.uniform(size=M)
norm = 1 / np.std(Xstd)
gamma = np.ones(M)
__N = N
__ddof = 1 if __N > 1 else 0
__Xstd = Xstd
__dXstd = _dXstd
__Xmd = _Xmd
__dU = _dU
__dV = _dV
__norm = norm
__gamma = gamma

ne.evaluate("sum(-2 * __Xmd, axis=0)", out=_dU)
ne.evaluate("__dV / (__N - __ddof) * __dU", out=_dU)
__dU += ne.evaluate("sum(-1 * __dXstd, axis=0)")


In [12]:
# --------------------------------------------------------------------------------
# dL/dU: (M,) = [ dL/dV:(M,) / (N-ddof) * sum(-2 * Xmd:(N,M), axis=0) ]
#             + [ sum(-dL/dXstd, axis=0) * norm ]
# Bessel's correction (N-ddof), see https://github.com/pytorch/pytorch/issues/1410
# --------------------------------------------------------------------------------

dU = __dV / (__N - __ddof) *  np.sum(-2 * __Xmd, axis=0) 

In [13]:
a = np.empty((1,5), dtype=float)
a.prod()

-0.05768972559627533

In [14]:
X = np.array([[-2.06943465], 
 [ 0.27749823]])

sd = np.std(X, ddof=1, axis=0)
print(sd)
print(X- X.mean(axis=0))
(X - X.mean(axis=0)) / sd

[1.65953215]
[[-1.17346644]
 [ 1.17346644]]


array([[-0.70710678],
       [ 0.70710678]])

In [15]:
import numpy as np
X = np.random.randn(5, 5)
C = np.max(X, axis=-1)
exp = np.exp(X - C)
exp / np.sum(exp, axis=-1)

array([[4.36873120e-01, 4.08969344e-02, 4.88492260e-02, 6.17815558e-03, 9.11173304e-02],
       [1.06044927e+00, 1.15209859e-01, 2.12740136e-01, 3.40788839e-03, 3.15143253e-01],
       [2.07102415e+00, 3.94361445e-02, 4.05034393e-02, 1.94117715e-03, 7.03115559e-01],
       [1.22607795e+00, 6.16503023e-02, 9.58874819e-01, 4.49666261e-03, 2.25115649e-01],
       [8.90546808e-01, 4.28051850e-02, 7.72802977e-02, 1.40883090e-02, 3.89443956e-01]])

In [16]:
C = np.max(X, axis=-1, keepdims=True)
exp = np.exp(X - C)
exp / np.sum(exp, axis=-1, keepdims=True)


array([[0.14060114, 0.17196881, 0.2890776 , 0.22543459, 0.17291785],
       [0.12158112, 0.17258033, 0.44848602, 0.04429858, 0.21305395],
       [0.26906387, 0.06694068, 0.09675766, 0.02859325, 0.53864454],
       [0.05702648, 0.03746443, 0.82005621, 0.02371248, 0.06174041],
       [0.13164953, 0.08267693, 0.21006543, 0.23612915, 0.33947895]])

In [17]:
isinstance(1.0, (int, float))

True

In [18]:
_HOGE = 1
class hoge:
    def __init__(
            self,
            name: str,
            num_nodes: int,
            momentum = 0.9,
    ):
        self.args = set(locals().keys())
        global _HOGE
        print(_HOGE)

a = hoge(name="name", num_nodes=1)

1


In [19]:
__HOGE = 1
class hoge:
    def __init__(
            self,
            name: str,
            num_nodes: int,
            momentum = 0.9,
    ):
        self.args = set(locals().keys())
        global __HOGE
        print(__HOGE)


In [20]:
a = hoge(name="name", num_nodes=1)

NameError: name '_hoge__HOGE' is not defined

In [ ]:
sig = inspect.signature(hoge.__init__)
for param in sig.parameters.values():
        print(f'Parameter: {param} param.default {param.default} {param.default is param.empty}')

In [ ]:
a = {
    "num_nodes": 8,
    "num_features": 3,
    "weights": {
        "scheme": "he"
    },
    "optimizer": {
        "lr": 0.1,
        "l2": 0.1
    }
}
a = set(a.keys())
set(['num_nodes', 'num_features', 'weights', 'optimizer']).issubset(a)
#b.issubset(a)

In [ ]:
isinstance([], list)

In [ ]:
network_specification = {
    "matmul01": {
        "scheme": "hoge",
        "parameters": {
            "num_nodes": 8,
            "num_features": 2,  # NOT including bias
            "weights": {
                "scheme": "he"
            },
            "optimizer": {
        "scheme": "hoge",
                "lr": 0.01,
                "l2": 1e-3
            }
        },
    },
    "activation01": {
        "scheme": "hoge",
        "parameters": {
            "num_nodes": 8
        }
    },
    "matmul02": {
        "scheme": "hoge",
        "parameters": {
            "num_nodes": 3,
            "num_features": 8,  # NOT including bias
            "weights": {
                "scheme": "he"
            }
        }
    },
    "activation02": {
        "scheme": "hoge",
        "parameters": {
            "num_nodes": 3
        }
    },
    "objective": {
        "scheme": "hoge",
        "parameters": {
            "num_nodes": 3,
            "loss_function": "softmax_cross_entropy_log_loss"
        }
    }
}

In [ ]:
network_specification[-1]

In [ ]:
import numpy as np
n=3
m=5
a = np.random.rand(n,m)
b = np.random.rand(n,m)
c = np.random.rand(n,m)
np.sum([a,b,c], axis=0)

In [ ]:
_NAME = "name"
_NUM_NODES = "num_nodes"
_NUM_FEATURES = "num_features"
_WEIGHTS = "weights"
_OPTIMIZER = "optimizer"
_SCHEME = "scheme"
_PARAMETERS = "parameters"
_LOG_LEVEL = "log_level"
_LAYER_CLASS = "layer_class"
_LOSS_FUNCTION = "loss_function"
_LAYERS = "layers"
_COMPOSITE_LAYER_SPEC = "composite_layer_specification"

LOG_LOSS_GRADIENT_ACCEPTANCE_VALUE = float(1.2)

a = {
    "matmul02": {
        _PARAMETERS: {
            _NAME: "matmul02",
            _NUM_NODES: 3,
            _NUM_FEATURES: 8,  # NOT including bias
            _WEIGHTS: {
                _SCHEME: "he"
            }
        }
    }
}
a["matmul02"][_PARAMETERS][_NUM_NODES]

In [ ]:
import numpy as np
a = [1,2,3]
f = lambda x: np.sum(x)
f(a)

In [ ]:
a = np.arange(60).reshape((3,4,-1))
print(a[0].shape)
b = np.sum(a, axis=0, keepdims=False)
b.shape

In [ ]:
X = np.array(1)
shape_Y = X[0].shape if X.ndim > 0 else ()
_Y = np.empty(shape_Y, dtype=float)
np.sum(X, out=_Y)

In [ ]:
a = np.arange(60).reshape((3,4,-1))
shape = a[0].shape
Y = np.empty(shape)
np.sum(a, axis=0, out=Y)


In [ ]:
from more_itertools import take
d = {"a": 1, "b": 2}
take(1, d.items())

In [ ]:
index = 1
f"matmul{index:03d}"

In [ ]:
from typing import(
    Dict,
    List
)
import re
import string
import collections
import numpy as np
from preprocessing.constant import (
    DELIMITER,
    NIL
)
from preprocessing.text import (
    word_indexing, 
    standardize,
    sub_sampling
)

In [ ]:
corpus = "tako ika tako tako ika bin uni sashimi sashimi uni ika uni"
vocabulary, index_to_event, event_to_index, probabilities = word_indexing(corpus)
print(probabilities)

In [ ]:
from collections import Counter
corpus = "tako ika tako tako ika bin uni sashimi sashimi uni ika uni"
total = len(words:=corpus.split())
probabilities = {word: (count / total) for (word, count) in Counter(words).items()}
print(probabilities)

In [ ]:
def sub_sampling(corpus: str, power: float = float(0.75)):
    total = len(words := standardize(corpus).split())
    counts = collections.Counter(words)
    probabilities = {word: np.power((count / total), power) for (word, count) in counts.items()}

    sigma = np.sum(list(probabilities.values()))
    probabilities = {word: (p/sigma) for (word, p) in probabilities.items()}
    assert (1.0 - np.sum(list(probabilities.values()))) < 1e-5

    del words, total, counts, sigma
    return probabilities



sum(sub_sampling(corpus).values())

{75: 77,
 79: 81,
 69: 71,
 33: None,
 34: None,
 35: None,
 36: None,
 37: None,
 38: None,
 39: None,
 40: None,
 41: None,
 42: None,
 43: None,
 44: None,
 45: None,
 46: None,
 47: None,
 58: None,
 59: None,
 60: None,
 61: None,
 62: None,
 63: None,
 64: None,
 91: None,
 92: None,
 93: None,
 94: None,
 95: None,
 96: None,
 123: None,
 124: None,
 125: None,
 126: None}