In [4]:
import numpy as np

In [7]:
from typing import (
    Tuple,
    List
)
import numpy as np
from mathematics import (
    rotate,
    shift,
    is_point_inside_sector
)


In [11]:
from data import (
    sets_in_circles,
    set_in_A_not_B
)

In [12]:
def sets_of_circle_A_not_B(
        radius: float, ratio: float = 1.0, m: int = 3, d: int = 2, n: int = 10000
) -> Tuple[np.ndarray, np.ndarray]:
    """Generate m set (A NOT B).
        First generate m circles. Let circles[i] be A and circles[i+1] as B.
        A is a set of points that form a circle. B as well. Then A_NOT_B is
        those point in A but not in B.

    Args:
        radius: circle radius
        ratio: how far to locate a new centre of a circle
        d: dimension. 2 only for now
        m: number of circles
        n: Number of points in a circle
    Returns:
        [A_NOT_B]: List of A_NOT_B
        centre: coordinates of the centre of each circle. Shape (m, 2)
    """
    assert 2 <= m <= n and ratio > 0 and radius > 0.0
    circles, centres = sets_in_circles(radius=radius, ratio=ratio, m=m, n=n)
    result = []

    assert d == 2, "Only 2 is supported for now"

    for i in range(m):
        A = circles[i]
        centre_B = centres[(i+1) % m]
        A_NOT_B = set_in_A_not_B(A, centre_B, radius)
        
        print(A_NOT_B.shape)
        result.append(A_NOT_B)

    return np.array(result), centres


In [16]:
M = 3
N = 3
radius = 1
circles, centres = sets_of_circle_A_not_B(radius=radius, ratio=1.2, m=M, n=N)

print(circles)

np.array(circles)

(2, 2)
(3, 2)
(2, 2)
[array([[-0.68595   , -0.59704907],
       [-0.70704997, -0.30369686]])
 array([[ 0.51405   , -0.59704907],
       [ 1.51991102, -0.48112732],
       [ 0.49295003, -0.30369686]])
 array([[ 0.91991102,  0.55810317],
       [-0.10704997,  0.73553363]])]


<ipython-input-12-c1560bd90f84>:33: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return np.array(result), centres


array([array([[-0.68595   , -0.59704907],
       [-0.70704997, -0.30369686]]),
       array([[ 0.51405   , -0.59704907],
       [ 1.51991102, -0.48112732],
       [ 0.49295003, -0.30369686]]),
       array([[ 0.91991102,  0.55810317],
       [-0.10704997,  0.73553363]])], dtype=object)

In [21]:
a = np.array([
    [-0.68595   , -0.59704907],
    [-0.70704997, -0.30369686]])
b = np.array([
    [ 0.51405   , -0.59704907],
    [ 1.51991102, -0.48112732],
    [ 0.49295003, -0.30369686]])
c = np.array([
    [ 0.91991102,  0.55810317],
    [-0.10704997,  0.73553363]])

d = [a, b, c]
np.array(d)

<ipython-input-21-cd465a89490d>:13: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array(d)


array([array([[-0.68595   , -0.59704907],
       [-0.70704997, -0.30369686]]),
       array([[ 0.51405   , -0.59704907],
       [ 1.51991102, -0.48112732],
       [ 0.49295003, -0.30369686]]),
       array([[ 0.91991102,  0.55810317],
       [-0.10704997,  0.73553363]])], dtype=object)