# Extract the 1st record from Dataset

In [1]:
import numpy as np
import tensorflow as tf

In [6]:
dataset = tf.data.Dataset.from_tensor_slices([tf.reshape(tf.range(2*3*4),shape=(2,3,4))])
for record in dataset:
    print(record)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [8]:
next(dataset.as_numpy_iterator())

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)