In [3]:
import numpy as np
import tensorflow as tf

np.set_printoptions(threshold=np.inf)
np.set_printoptions(linewidth=1024)

In [17]:
x = tf.ones(shape=(4,8)) * -1
x

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[-1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1.]], dtype=float32)>

In [18]:
columns = tf.constant([6,3,1,5])
rows = tf.range(x.shape[0])
indices = tf.stack([rows, columns], axis=-1)
indices

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 6],
       [1, 3],
       [2, 1],
       [3, 5]], dtype=int32)>

In [19]:
updates = [0,1,2,3]

In [20]:
tf.tensor_scatter_nd_update(
    tensor=x,
    indices=indices,
    updates=updates
)

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[-1., -1., -1., -1., -1., -1.,  0., -1.],
       [-1., -1., -1.,  1., -1., -1., -1., -1.],
       [-1.,  2., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.,  3., -1., -1.]], dtype=float32)>

<img src="./image/update_tensor_row_wise.png" width=500 align="left"/>

In [22]:
!ls ./image

ScatterNd1_1D.png          tf_slicing_2d.png
tf_slicing_1d_1.png        update_tensor_row_wise.png
tf_slicing_1d_3.png
