In [1]:
import tensorflow as tf
import numpy as np

# References

* [How to efficiently update a tensor slice?](https://github.com/tensorflow/tensorflow/issues/36559)

```
var_slice = var[4:5]
var_slice.assign(math_ops.sub(var, const))
```

* [How to Replace Values by Index in a Tensor with TensorFlow-2.0](https://towardsdatascience.com/how-to-replace-values-by-index-in-a-tensor-with-tensorflow-2-0-510994fe6c5f)

# Constraint



---

# Update a slice region of tf.Variable

* [Tensorflow 2 - tf.slice and its NumPy slice syntax incompatible behavior](https://stackoverflow.com/questions/67378040/)

<img src="image/tf_slicing_2d.png" align="left" width=200 />

In [18]:
TYPE = tf.int32
N = 4
D = 5
shape = (N,D)

# Target to update
Y = tf.Variable(
    initial_value=tf.reshape(tf.range(N*D,dtype=TYPE), shape=shape),
    trainable=True
)
print(f"Target Y: \n{Y}\n")

# --------------------------------------------------------------------------------
# Slice region in the target to be updated
# --------------------------------------------------------------------------------
# S = tf.slice(      # Error "EagerTensor' object has no attribute 'assign'"
#     Y,
#     begin=[0,1],   # Coordinate (n,d) as the start point
#     size=[3,2]     # Shape (3,2) -> (n+3, n+2) as the end point
# )
S = Y[
    0:3,           # From coordinate (n=0,d),   slice rows (0,1,2)  or 'size'=3 -> shape (3,?)
    1:3            # From coordinate (n=0,d=1), slice columns (1,2) or 'size'=2 -> shape (3,2)
]                  
print(f"Slice to update S: \n{S}\n")

# Values to set
V = tf.ones(shape=tf.shape(S), dtype=TYPE)
print(f"Values to set V: \n{V}\n")

# Assing V to S region of T
S.assign(V)

Target Y: 
<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]], dtype=int32)>

Slice to update S: 
[[ 1  2]
 [ 6  7]
 [11 12]]

Values to set V: 
[[1 1]
 [1 1]
 [1 1]]



<tf.Variable 'UnreadVariable' shape=(4, 5) dtype=int32, numpy=
array([[ 0,  1,  1,  3,  4],
       [ 5,  1,  1,  8,  9],
       [10,  1,  1, 13, 14],
       [15, 16, 17, 18, 19]], dtype=int32)>

True