In [1]:
import tensorflow as tf
import numpy as np

# Update the tensor values where the condition matches


Numpy can use boolean indexing to directy update the array.

In [2]:
x = np.random.uniform(-1, 1, size=(3, 4))
print(x)
x[x > 0] = 0
print(x)

[[-0.21862459 -0.11904506 -0.65759051 -0.02053271]
 [ 0.85862027  0.59237733 -0.78714513 -0.0176912 ]
 [-0.94936706 -0.30497186  0.25053833  0.18807091]]
[[-0.21862459 -0.11904506 -0.65759051 -0.02053271]
 [ 0.          0.         -0.78714513 -0.0176912 ]
 [-0.94936706 -0.30497186  0.          0.        ]]


Tensorflow does not have such syntax, hence need to use ```tf.where```.

* [tf.where(condition, x=None, y=None, name=None)](https://www.tensorflow.org/api_docs/python/tf/where)

```
Returns:
    If x and y are provided: 
        A Tensor with the same type as x and y, and shape that is broadcast from condition, x, and y.
    Otherwise: 
        A Tensor with shape (num_true, dim_size(condition)).
```

However, it does not directly update the ```tf.Variable``` itself.

* [tensorflow 2 - how to conditionally update values directly in tf.Variable](https://stackoverflow.com/questions/66980404/tensorflow-2-how-to-conditionally-update-values-directly-in-tf-variable)

In [4]:
x = tf.Variable(np.random.uniform(-1, 1, size=(3,4)), dtype=tf.float32)
print(f"x:\n{x}\n")

# --------------------------------------------------------------------------------
# Boolean indices with the condition
# --------------------------------------------------------------------------------
mask = x > 0
print(f"Boolean indices (x > 0):\n{mask}\n")

# --------------------------------------------------------------------------------
# Update values in Variable wih boolean indices
# --------------------------------------------------------------------------------
x.assign(tf.where(mask, 1, x))
print(f"x.assign(tf.where(x>0, 1, x)):\n{x}")

x:
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.6215271 , -0.6722634 ,  0.9787062 ,  0.3303163 ],
       [ 0.71643543,  0.56936526,  0.74331343, -0.57534343],
       [-0.2167569 ,  0.6609811 , -0.45718992, -0.41778496]],
      dtype=float32)>

Boolean indices (x > 0):
[[ True False  True  True]
 [ True  True  True False]
 [False  True False False]]

x.assign(tf.where(x>0, 1, x)):
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 1.        , -0.6722634 ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        , -0.57534343],
       [-0.2167569 ,  1.        , -0.45718992, -0.41778496]],
      dtype=float32)>


* [How to efficiently update a tensor slice? #36559](https://github.com/tensorflow/tensorflow/issues/36559)

```
import tensorflow.keras.backend as K
units, timesteps = 4, 6
x = K.zeros((units, timesteps), dtype='float32', name='x')
x_new = x[:units, 0].assign(K.ones((units,), dtype='float32'))  # dummy example
K.set_value(x, K.get_value(x_new))
print(K.get_value(x))
```