# TF slicing

* [Introduction to tensor slicing](https://www.tensorflow.org/guide/tensor_slicing)

> In this guide, you will learn how to use the TensorFlow APIs to:
> * Extract slices from a tensor
> * Insert data at specific indices in a tensor

In [1]:
import numpy as np
import tensorflow as tf

# Extract multiple axes junctions

> To extract slices from multiple axes of a tensor, use tf.gather_nd. This is useful when you want to gather the elements of a matrix as opposed to just its rows or columns.

In [4]:
x = tf.constant(np.arange(24).reshape(4,6))
x

<tf.Tensor: shape=(4, 6), dtype=int64, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>

In [6]:
tf.gather_nd(x, indices=[
    [0,1],        # (row, col) = (0,1)
    [1,3],
    [2,5],
    [3,0]
])

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 1,  9, 17, 18])>