# Tranapose the internal (R, C) matrix in (N, R, C) Tensor

You have tensor of shape (N, R, C) which is N batch of ```(R, C)``` matrices. You waant to transpose ```(R, C)``` to ```(C, R)```, e.g:

From ```(N,R=2,C=3)```
```
[[
  [ 0  1  2]
  [ 3  4  5]
]]
```
To ```(N,C=2,R=3)```
```
[[
  [ 0,  3],
  [ 1,  4],
  [ 2,  5]
]]
```

In [3]:
import numpy as np
import tensorflow as tf

---
# (N, R, C) to (N, C, R)

In [16]:
N=2    # Number of batches
R=2    # Row
C=3    # Column

x = tf.reshape(
    tensor=np.arange(N*M*D).reshape(N,M,D), 
    shape=(N,M,D), 
    name="from_constant"
)
print(x)

tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]], shape=(2, 2, 3), dtype=int64)


## Permutation

```
perm=[
   0,      # Within the outer most axis=0
   2,1     # Trasponse axes=(1,2) into axes=(2,1)
]
```

In [19]:
tf.transpose(a=x, perm=[0, 2, 1])

<tf.Tensor: shape=(2, 3, 2), dtype=int64, numpy=
array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]])>

---
# (N, N, R, C) to (N, N, C, R)

In [20]:
N=2    # Number of rows
R=3    # Number of row
C=4    # Number of columns in a row=(x, y, h, w)

a = tf.reshape(
    tensor=np.arange(N*N*R*C).reshape(N,N,R,C), 
    shape=(N,N,R,C), 
)
a

<tf.Tensor: shape=(2, 2, 3, 4), dtype=int64, numpy=
array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]],


       [[[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]])>

In [22]:
tf.transpose(a=a, perm=(0,1,3,2))

<tf.Tensor: shape=(2, 2, 4, 3), dtype=int64, numpy=
array([[[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]],


       [[[24, 28, 32],
         [25, 29, 33],
         [26, 30, 34],
         [27, 31, 35]],

        [[36, 40, 44],
         [37, 41, 45],
         [38, 42, 46],
         [39, 43, 47]]]])>