# What Tensor is

## tf.Tensor 

Immutable multi-dimensional array with a uniform type with GPU support.

* [tf.Tensor](https://www.tensorflow.org/api_docs/python/tf/Tensor)
* [Introduction to Tensors](https://www.tensorflow.org/guide/tensor)


## Note

tf.Variable is mutable multi-dimensional array with GPU support.

In [1]:
import numpy as np
import tensorflow as tf

In [3]:
a = tf.constant([
    list(range(12))
])

In [3]:
dir(a)

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__tf_tracing_type__',
 '__true

In [4]:
a = tf.reshape(tensor=a, shape=(3,4), name="from_constant")
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

## Topology

In [5]:
a.ndim

2

In [6]:
a.shape

TensorShape([3, 4])

In [20]:
a.shape == (3,4)

True

In [17]:
a.shape[-1]

4

In [21]:
a.shape[-1] in (4, 5)

True

In [19]:
(1, 2)[-1]

2

## DType

* [tf.dtypes.DType](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType)



In [59]:
for t in dir(tf.dtypes): 
    if t[0] in ("bcfqu"):
        print(t)

bfloat16
bool
cast
complex
complex128
complex64
float16
float32
float64
qint16
qint32
qint8
quint16
quint8
uint16
uint32
uint64
uint8


In [7]:
a.dtype

tf.int32

In [8]:
a.dtype.is_integer

True

In [9]:
a.dtype.is_floating

False

In [10]:
a.dtype.min

-2147483648

In [11]:
a.dtype.max

2147483647

## Numpy I/F

In [12]:
a.dtype.is_compatible_with(np.int32)

True

In [13]:
a.numpy()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [14]:
np.array(a)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

---
# Convert to Tensor

* [tf.convert_to_tensor](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)

In [15]:
tf.convert_to_tensor(value=[1,2,3], dtype=tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

---
# Operations

### Cast

In [29]:
tf.cast(tf.constant([1,2,3]), tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [24]:
m = tf.random.normal(shape = (3,4), mean=10, stddev=2, dtype=tf.float32, seed=None,  name=None)
print(m.shape)
print(m)

(3, 4)
tf.Tensor(
[[13.191885  10.911267   9.512636   8.919833 ]
 [12.425211   8.730868   7.0700006 10.632405 ]
 [10.603993   9.163311  12.140513  11.256826 ]], shape=(3, 4), dtype=float32)


In [19]:
m @ tf.transpose(tf.sqrt(m))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[133.19125, 131.34326, 129.4595 ],
       [130.73251, 131.28784, 128.52892],
       [126.388  , 126.07254, 123.89667]], dtype=float32)>

### Add dimension

In [27]:
m[tf.newaxis, ..., tf.newaxis].shape

TensorShape([1, 3, 4, 1])

In [28]:
m[tf.newaxis, :, :, tf.newaxis].shape

TensorShape([1, 3, 4, 1])

### Merge two tensors

In [41]:
a = tf.random.normal(shape = (3,2,1), mean=10, stddev=2, dtype=tf.float32, seed=None,  name=None)
b = tf.random.normal(shape = (3,2,1), mean=10, stddev=2, dtype=tf.float32, seed=None,  name=None)
a

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[ 7.889156 ],
        [13.810212 ]],

       [[11.1803875],
        [ 8.357906 ]],

       [[ 7.016836 ],
        [11.254279 ]]], dtype=float32)>

concat(a=(..., 1), b=(..., 1)) into (..., 2)

In [44]:
c = tf.concat(values=[a, b], axis=-1)
print(c.shape)
c

(3, 2, 2)


<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 7.889156 ,  8.483684 ],
        [13.810212 ,  8.877228 ]],

       [[11.1803875, 10.522204 ],
        [ 8.357906 ,  7.8342514]],

       [[ 7.016836 ,  8.289329 ],
        [11.254279 , 12.411686 ]]], dtype=float32)>

### Max within a row

* [tf.math.reduce_max](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max)
* [tf.math.maximum](https://www.tensorflow.org/api_docs/python/tf/math/maximum)

In [51]:
tf.math.reduce_max(input_tensor=c, axis=-1, keepdims=True)

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[ 8.483684 ],
        [13.810212 ]],

       [[11.1803875],
        [ 8.357906 ]],

       [[ 8.289329 ],
        [12.411686 ]]], dtype=float32)>

In [46]:
tf.math.maximum(x=a, y=b)

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[ 8.483684 ],
        [13.810212 ]],

       [[11.1803875],
        [ 8.357906 ]],

       [[ 8.289329 ],
        [12.411686 ]]], dtype=float32)>

### Indices of Max in row

* [tf.math.argmax](https://www.tensorflow.org/api_docs/python/tf/math/argmax)

In [55]:
tf.math.argmax(input=c, axis=-1, output_type=tf.dtypes.int16)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 0],
       [0, 0],
       [1, 1]], dtype=int16)>

### Logic

In [29]:
a = tf.constant(np.array([[
    [0, 1, 2, 3],
    [2, 3, 1, 0],
]]), dtype=tf.dtypes.int16)
a

<tf.Tensor: shape=(1, 2, 4), dtype=int16, numpy=
array([[[0, 1, 2, 3],
        [2, 3, 1, 0]]], dtype=int16)>

In [30]:
indices_to_not_0_nor_1 = tf.math.logical_and(
    a != tf.constant(value=0, dtype=tf.dtypes.int16),
    a != tf.constant(value=1, dtype=tf.dtypes.int16)
)
indices_to_not_0_nor_1

<tf.Tensor: shape=(1, 2, 4), dtype=bool, numpy=
array([[[False, False,  True,  True],
        [ True,  True, False, False]]])>

In [31]:
a[indices_to_not_0_nor_1]

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([2, 3, 2, 3], dtype=int16)>

---
# Access Elements

See tensorflow/slicing for complex access patterns.

In [7]:
a = tf.constant(np.random.rand(3,4))
a

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[0.88954362, 0.47175678, 0.49189263, 0.62867941],
       [0.81096226, 0.69750478, 0.59386691, 0.16181152],
       [0.69407505, 0.8993122 , 0.99606113, 0.31047165]])>

In [8]:
a[0][0]

<tf.Tensor: shape=(), dtype=float64, numpy=0.8895436211768607>

In [9]:
a[0, 0]

<tf.Tensor: shape=(), dtype=float64, numpy=0.8895436211768607>

In [16]:
a[0:2, ...]   # Same with a[0:2]

<tf.Tensor: shape=(2, 4), dtype=float64, numpy=
array([[0.88954362, 0.47175678, 0.49189263, 0.62867941],
       [0.81096226, 0.69750478, 0.59386691, 0.16181152]])>

In [11]:
a[..., 0]

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.88954362, 0.81096226, 0.69407505])>

In [37]:
a = tf.random.normal(shape = (4,3,5), mean=10, stddev=2, dtype=tf.float32, seed=None,  name=None)
a[..., 2, 4].shape

TensorShape([4])