# What Tensor is

## tf.Tensor 

Immutable multi-dimensional array with a uniform type with GPU support.

* [tf.Tensor](https://www.tensorflow.org/api_docs/python/tf/Tensor)
* [Introduction to Tensors](https://www.tensorflow.org/guide/tensor)


## Note

tf.Variable is mutable multi-dimensional array with GPU support.

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = tf.constant([
    list(range(12))
])

In [3]:
dir(a)

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__tf_tracing_type__',
 '__true

In [4]:
a = tf.reshape(tensor=a, shape=(3,4), name="from_constant")
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

## Topology

In [5]:
a.ndim

2

In [6]:
a.shape

TensorShape([3, 4])

## DType

* [tf.dtypes.DType](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType)



In [7]:
a.dtype

tf.int32

In [8]:
a.dtype.is_integer

True

In [9]:
a.dtype.is_floating

False

In [10]:
a.dtype.min

-2147483648

In [11]:
a.dtype.max

2147483647

## Numpy I/F

In [12]:
a.dtype.is_compatible_with(np.int32)

True

In [13]:
a.numpy()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [14]:
np.array(a)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

---
# Convert to Tensor

* [tf.convert_to_tensor](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)

In [15]:
tf.convert_to_tensor(value=[1,2,3], dtype=tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

---
# Operations

In [24]:
m = tf.random.normal(shape = (3,4), mean=10, stddev=2, dtype=tf.float32, seed=None,  name=None)
print(m.shape)
print(m)

(3, 4)
tf.Tensor(
[[13.191885  10.911267   9.512636   8.919833 ]
 [12.425211   8.730868   7.0700006 10.632405 ]
 [10.603993   9.163311  12.140513  11.256826 ]], shape=(3, 4), dtype=float32)


In [19]:
m @ tf.transpose(tf.sqrt(m))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[133.19125, 131.34326, 129.4595 ],
       [130.73251, 131.28784, 128.52892],
       [126.388  , 126.07254, 123.89667]], dtype=float32)>

### Add dimension

In [27]:
m[tf.newaxis, ..., tf.newaxis].shape

TensorShape([1, 3, 4, 1])

In [28]:
m[tf.newaxis, :, :, tf.newaxis].shape

TensorShape([1, 3, 4, 1])

### Cast

In [29]:
tf.cast(tf.constant([1,2,3]), tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>