In [1]:
import numpy as np
import tensorflow as tf

In [5]:
x = tf.Variable(np.arange(24).reshape(2, 3,4))
x

<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

# Update slice 

In [7]:
x[..., 1:3].assign([-1, -2])
x

<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=int64, numpy=
array([[[ 0, -1, -2,  3],
        [ 4, -1, -2,  7],
        [ 8, -1, -2, 11]],

       [[12, -1, -2, 15],
        [16, -1, -2, 19],
        [20, -1, -2, 23]]])>

# Update rectanble

In [12]:
x: tf.Variable = tf.Variable(np.zeros(shape=(5,5), dtype=np.float32))
x

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [16]:
x[1:4,1:4].assign([[1,1,1], [1,1,1], [1,1,1]])

<tf.Variable 'UnreadVariable' shape=(5, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [21]:
x[0, 2:].assign(tf.constant([-1,-1,-1], dtype=np.float32))

<tf.Variable 'UnreadVariable' shape=(5, 5) dtype=float32, numpy=
array([[ 0.,  0., -1., -1., -1.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]], dtype=float32)>