# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
import sys
print(sys.version)
print(np.__version__)

3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
1.19.2


#### 3. Create a null vector of size 10 (★☆☆)

In [223]:
print(np.array([0.]*10))
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [224]:
a = np.zeros(10)
print(a)
import sys
print("sys.getsizeof(np.array) is %d" % sys.getsizeof(a))
print("pythhon object.__sizeof__() %d" %  a.__sizeof__())

print("np.array() attribute: nbytes is %d" % a.nbytes)
print("np.array() attribute: size %d, items %d -> size*items %d" % (a.size, a.itemsize, a.size * a.itemsize))
del a

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sys.getsizeof(np.array) is 176
pythhon object.__sizeof__() 176
np.array() attribute: nbytes is 80
np.array() attribute: size 10, items 8 -> size*items 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [225]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via t

In [226]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [227]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [228]:
np.array(range(10, 50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [229]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [230]:
a = np.arange(10, 50)
a[-1:None:-1]  # list[start:stop:step] start at the last and reverse with -1 step

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [231]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [232]:
np.divide(np.array([1,2,0,0,4,0]), [1,2,1,1,4,1])

array([1., 1., 0., 0., 1., 0.])

In [233]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [234]:
print(np.eye(3, 3))
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [235]:
import random
np.array([random.random() for i in range(27)]).reshape(3,3,3)

array([[[0.9512562 , 0.45038364, 0.9003079 ],
        [0.88213184, 0.99139672, 0.82712995],
        [0.35643266, 0.6996043 , 0.19757526]],

       [[0.61259671, 0.32902147, 0.30828354],
        [0.24320331, 0.24981166, 0.11294968],
        [0.22438466, 0.2879494 , 0.83014024]],

       [[0.20903842, 0.63054539, 0.03102333],
        [0.4224167 , 0.26712945, 0.04663775],
        [0.67504608, 0.05557815, 0.73136776]]])

In [236]:
np.random.random(27).reshape(3,3,3)

array([[[0.68378079, 0.86117153, 0.94622578],
        [0.7590776 , 0.74293375, 0.06891609],
        [0.10130943, 0.9712506 , 0.31437713]],

       [[0.97939332, 0.67692559, 0.22627524],
        [0.47810919, 0.91949699, 0.82480354],
        [0.53666864, 0.11034737, 0.55730482]],

       [[0.90247441, 0.51274668, 0.71978977],
        [0.54304507, 0.13414542, 0.73048941],
        [0.77775219, 0.79729463, 0.89448023]]])

In [237]:
np.random.random((3,3,3))

array([[[0.57857523, 0.31854192, 0.89992011],
        [0.97001638, 0.25079772, 0.31003123],
        [0.31703644, 0.33950619, 0.42572463]],

       [[0.59903961, 0.55526891, 0.49263307],
        [0.80474302, 0.68642078, 0.25138458],
        [0.11658698, 0.30526783, 0.12417241]],

       [[0.33716179, 0.09967849, 0.33772665],
        [0.11095585, 0.00699381, 0.5854301 ],
        [0.61438878, 0.96369112, 0.33602445]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [238]:
np.random.random((10, 10)).min()

0.008917656906944016

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [239]:
np.random.random((30)).mean()

0.47039511812893714

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [240]:
np.array([[1, 0]] * 5)

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [241]:
a = np.ones((5, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [242]:
a[0] = a[-1] = 0
a.T[0] = a.T[-1] = 0
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [243]:
np.pad(np.ones((5, 5)), pad_width=1, mode='constant')

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [244]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)           # Why false?

nan
False
False
nan
True
False


In [245]:
print(3 * 0.1 == 0.3)     # False
print(0.3 * 1 == 0.3)     # True
print(1 * 0.1 == 0.1)     # True
print(1/10 == 0.1)        # True
print(0.3 * 0.1 == 0.03)  # True

print("%0.55f" % (1.0 / 10))
print("%0.55f" % (0.1000000000000000055511151231257827021181583404541015625 - 0.1))

False
True
True
True
True
0.1000000000000000055511151231257827021181583404541015625
0.0000000000000000000000000000000000000000000000000000000


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [287]:
a = np.eye(5).reshape(25)
b = np.concatenate(
    (a[1::], [0])
)
b.reshape((5, 5))

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [294]:
np.arange(4) + 1

array([1, 2, 3, 4])

In [291]:
np.diag(
    (np.arange(4) + 1)
)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [292]:
np.diag(
    (np.arange(4) + 1),
    k=-1
)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [303]:

base = np.array([[0,1],[1,0]])
print(base)


[[0 1]
 [1 0]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [335]:
# Beware the dimension is moving higher to lower d3 -> d2 -> d1
# Note that 100th element -> index is [99], NOT 100.
d3_size = 6
d2_size = 7
d1_size = 8
sequence = np.arange(d3_size * d2_size * d1_size)

cube = np.array(sequence).reshape((d3_size, d2_size, d1_size))
d3 = int(100 / (d2_size * d1_size))
print(d3)

d1d2_items = int(100 % (d2_size * d1_size))
print(d1d2_items)

d2 = int(d1d2_items / d1_size)
d1 = int(d1d2_items % d1_size) -1  # -1 as 100th element is 99th in index.
print((d3, d2, d1))

print(cube[d3][d2])
cube[d3][d2][d1]

1
44
(1, 5, 3)
[ 96  97  98  99 100 101 102 103]


99

In [334]:
indices=(np.unravel_index(99,(6,7,8)))
print(indices)
cube[indices[0]][indices[1]][indices[2]]

(1, 5, 3)


99

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [340]:
a = np.arange(64).reshape((8,8))
(a - np.mean (a)) / (np.std (a))

array([[-1.70519568, -1.65106248, -1.59692929, -1.54279609, -1.4886629 ,
        -1.4345297 , -1.3803965 , -1.32626331],
       [-1.27213011, -1.21799691, -1.16386372, -1.10973052, -1.05559733,
        -1.00146413, -0.94733093, -0.89319774],
       [-0.83906454, -0.78493134, -0.73079815, -0.67666495, -0.62253176,
        -0.56839856, -0.51426536, -0.46013217],
       [-0.40599897, -0.35186578, -0.29773258, -0.24359938, -0.18946619,
        -0.13533299, -0.08119979, -0.0270666 ],
       [ 0.0270666 ,  0.08119979,  0.13533299,  0.18946619,  0.24359938,
         0.29773258,  0.35186578,  0.40599897],
       [ 0.46013217,  0.51426536,  0.56839856,  0.62253176,  0.67666495,
         0.73079815,  0.78493134,  0.83906454],
       [ 0.89319774,  0.94733093,  1.00146413,  1.05559733,  1.10973052,
         1.16386372,  1.21799691,  1.27213011],
       [ 1.32626331,  1.3803965 ,  1.4345297 ,  1.4886629 ,  1.54279609,
         1.59692929,  1.65106248,  1.70519568]])

In [341]:
a = np.arange(15).reshape((3,5))
(a - np.mean (a)) / (np.std (a))

array([[-1.62018517, -1.38873015, -1.15727512, -0.9258201 , -0.69436507],
       [-0.46291005, -0.23145502,  0.        ,  0.23145502,  0.46291005],
       [ 0.69436507,  0.9258201 ,  1.15727512,  1.38873015,  1.62018517]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [344]:
a = np.random.random((5,5))
(a - a.mean()) / a.std()

array([[ 1.26676342, -0.88109534,  1.20451325, -1.30315904,  0.09762636],
       [ 0.80578031,  1.29353626,  0.89162493,  0.22130967,  0.24921821],
       [-1.14943749,  0.65402644,  0.46657982,  1.40726987, -1.13914804],
       [-0.94192084, -0.89030719, -1.26329466, -0.06808972, -1.00284772],
       [ 1.07008664, -1.28699143, -1.33021077,  0.17981952,  1.44834754]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [395]:
color_type = np.dtype([
    ("r", np.ubyte, (1,)),
    ("g", np.ubyte, (1,)),
    ("b", np.ubyte, (1,))
])
colors = np.array(
    [
        (0, 0, 0),      # black
        (255,255,255),  # white 
        (255,0,0)       # red
    ]
)
colors

array([[  0,   0,   0],
       [255, 255, 255],
       [255,   0,   0]])

In [389]:
dt = np.dtype(
  [
    ('first', np.unicode_, 16),    
    ('middle', np.unicode_, (16)),   
    #('last', np.unicode_, (16,)),   
    ('last', np.unicode_, 16),   
    ('grades', np.float64, (2,))  
  ]
)
x = np.array(
    [
        ('Sarah', 'Jeanette', 'Conner', (8.0, 7.0)), 
        ('John', '', 'Conner', (6.0, 7.0))
    ], 
    dtype=dt
)

print(x[1])
print(x[1]['first'])
print(type(x[1]['grades']))

('John', '', 'Conner', [6., 7.])
John
<class 'numpy.ndarray'>


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [398]:
np.dot(np.random.random((5,3)), np.random.random((3,2)))

array([[0.57460442, 0.70796604],
       [0.5074391 , 0.69540674],
       [0.53745157, 0.61475245],
       [0.61348007, 0.76344271],
       [0.63491998, 0.80925926]])

In [399]:
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [401]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(tomorrow)

2020-12-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [404]:
np.arange(
    start=np.datetime64('2016-06-10'),
    stop=np.datetime64('2016-07-01'),
    step=np.timedelta64(1, 'D')
)

array(['2016-06-10', '2016-06-11', '2016-06-12', '2016-06-13',
       '2016-06-14', '2016-06-15', '2016-06-16', '2016-06-17',
       '2016-06-18', '2016-06-19', '2016-06-20', '2016-06-21',
       '2016-06-22', '2016-06-23', '2016-06-24', '2016-06-25',
       '2016-06-26', '2016-06-27', '2016-06-28', '2016-06-29',
       '2016-06-30'], dtype='datetime64[D]')

In [405]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [408]:
a = np.ones((5, 3))
print(a)

b = np.ones((5, 3))
np.add(a, b, out=a)
print(a)



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [412]:
Z = np.random.uniform(0,10,10)
print(Z)
Z.astype(np.int32)

[4.53463669 3.22148394 5.04004642 0.35688405 3.15655412 1.54410951
 1.73369491 0.93892766 4.65909665 4.09189976]


array([4, 3, 5, 0, 3, 1, 1, 0, 4, 4], dtype=int32)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [422]:
np.array([i for i in range(5)] * 5).reshape(5, 5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [424]:
# Using Broadcast
Z = np.zeros((5,5))
print(np.arange(5))  
Z += np.arange(5)   # [0 1 2 3 4] is broadcasted into (5, 5)
print(Z)

[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [426]:
(lambda x: np.arange(x, x+10, 1))(5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [436]:
np.linspace(
    start=0,
    stop=1,
    num=11,
    endpoint=False
)[1::]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [434]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [441]:
sorted([np.random.random() for i in range(10)])

[0.03189917257536179,
 0.16932551232288584,
 0.19607497553352382,
 0.25250003839966395,
 0.2741005874885327,
 0.3534499898891531,
 0.6694896460337765,
 0.7757011646990992,
 0.7976975984636301,
 0.9078019131499397]

In [457]:
Z = np.random.random((3,3))
print(Z)

Z.sort(axis=0)   # Mutable op to the row direction
print(Z)

Z.sort(axis=1)   # Mutable op to the column direction
print(Z)

[[0.0195375  0.76532405 0.40794293]
 [0.82686827 0.4125267  0.97171053]
 [0.28994105 0.42363926 0.52729317]]
[[0.0195375  0.4125267  0.40794293]
 [0.28994105 0.42363926 0.52729317]
 [0.82686827 0.76532405 0.97171053]]
[[0.0195375  0.40794293 0.4125267 ]
 [0.28994105 0.42363926 0.52729317]
 [0.76532405 0.82686827 0.97171053]]


#### 41. How to sum a small array faster than np.sum? (★★☆)

* [What is the difference between np.sum and np.add.reduce?
](https://stackoverflow.com/questions/16420097/what-is-the-difference-between-np-sum-and-np-add-reduce)
> np.sum ultimately calls add.reduce to do the work. The overhead of handling its argument and dispatching to add.reduce is why np.sum is slower.

In [458]:
np.add.reduce(np.arange(10))

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [465]:
np.array_equal(np.ones((5, 3)), np.ones((3, 3)))

False

In [466]:
np.equal(np.ones((5, 3)), np.ones((3, 3)))

ValueError: operands could not be broadcast together with shapes (5,3) (3,3) 

In [468]:
np.equal(np.ones((3, 3)), np.ones((3, 3)))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [469]:
np.equal(np.ones((3, 3)), np.ones((3, 3))).all()

True

#### 43. Make an array immutable (read-only) (★★☆)

In [476]:
a = np.random.random((5,3))
a.flags.writeable = False
a +=1

ValueError: output array is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [583]:
shape = (6, 7)
X = np.zeros(shape, dtype=int)
X[(4, 2)] = 1
X[(5, 3)] = 1
print("X is :\n{}\n".format(X))

Y = np.zeros(shape, dtype=int)
Y[(4, 2), (5, 3)] = 1
print("Y is :\n{}\n".format(Y))

X is :
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]]

Y is :
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0]]



In [596]:
# --------------------------------------------------------------------------------
# Target nd array X
# --------------------------------------------------------------------------------
shape = (6, 7)
X = np.zeros(shape, dtype=int)

# Same with X[(4, 5, 1), (2, 3, 1)] = 1
X[ 4, 2 ] = 1
X[(5, 3)] = 1
X[(1, 1)] = 1
print("X is:\n{}\n".format(X))


# --------------------------------------------------------------------------------
# Indices
# --------------------------------------------------------------------------------
per_dimensional_indices = np.array([
    [4, 5, 1],  # For dimension 2
    [2, 3, 1],  # For dimension 1
])
# Transpose of per_dimensional_indices is [(row, col)*] indices
print("Indices (row, col) are:\n{}\n".format(per_dimensional_indices.T))


# --------------------------------------------------------------------------------
# Flat indeices to the non-zero elements
# --------------------------------------------------------------------------------
# np.ravel(a, order='C') to flatten and np.nonzero(a) for non-zero element indices.
# When only condition is provided, np.where is a shorthand for np.asarray(condition).nonzero()
# numpy.nonzero(a) return the indices of the elements that are non-zero.
condition = (X.ravel() == 1)
print("X indices where value is non zero: {}\n".format(np.where(condition)))

# np.ravel_multi_index(multi_index, dims) to convert into flat inices.
print("X flat indices of \n{} \n into a nd array of shape {} are {}".format(
    per_dimensional_indices.T,
    shape,
    np.ravel_multi_index(
        multi_index=per_dimensional_indices, # One array for each dimension, NOT an index (4, 2)
        dims=shape
    )
))

X is:
[[0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]]

Indices (row, col) are:
[[4 2]
 [5 3]
 [1 1]]

X indices where value is non zero: (array([ 8, 30, 38]),)

X flat indices of 
[[4 2]
 [5 3]
 [1 1]] 
 into a nd array of shape (6, 7) are [30 38  8]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [601]:
a = np.random.random((2, 3, 4))
print(a)
print(a.max())

# By default, the index is into the flattened array, otherwise along the specified axis.
index = a.argmax(axis=None)
indices = np.unravel_index(index, a.shape)
print("Flat index = {}, indices = {}\n".format(index, indices))

# ndarray.flat is a 1-D iterator over the array.
print("max value via the flat index[{}] {}".format(index, a.flat[index]))

print("max value via ndarray[{}] {}".format(indices, a[indices]))

a.flat[a.argmax(axis=None)] = 0
a

[[[0.72804267 0.70472039 0.74884177 0.91117708]
  [0.65951272 0.33750482 0.70375701 0.26292579]
  [0.13170144 0.45042128 0.10979338 0.76123296]]

 [[0.45796694 0.16995102 0.97065454 0.37903716]
  [0.61116253 0.87424378 0.61114847 0.64561804]
  [0.24363055 0.6201267  0.73608913 0.77634606]]]
0.9706545381749268
Flat index = 14, indices = (1, 0, 2)

max value via the flat index[14] 0.9706545381749268
max value via ndarray[(1, 0, 2)] 0.9706545381749268


array([[[0.72804267, 0.70472039, 0.74884177, 0.91117708],
        [0.65951272, 0.33750482, 0.70375701, 0.26292579],
        [0.13170144, 0.45042128, 0.10979338, 0.76123296]],

       [[0.45796694, 0.16995102, 0.        , 0.37903716],
        [0.61116253, 0.87424378, 0.61114847, 0.64561804],
        [0.24363055, 0.6201267 , 0.73608913, 0.77634606]]])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [613]:
coordinate_type = np.dtype([
    ('x', np.int32, 1),  # To be deprecated to work as "only one element" which is NOT (1, ) as array
    ('y', np.int32)
])
a = np.zeros((5, 5), dtype=coordinate_type)
a

<ipython-input-613-3a53d564f050>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  coordinate_type = np.dtype([


array([[(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)]],
      dtype=[('x', '<i4'), ('y', '<i4')])

In [607]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [617]:
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [619]:
[print(v) for v in np.arange(10)] 

0
1
2
3
4
5
6
7
8
9


[None, None, None, None, None, None, None, None, None, None]

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [625]:
a = np.random.random((5, 5))
v = a.mean()
print(a)
print(v)
a.flat[np.abs((a - v)).argmin()]

[[0.20538748 0.03945493 0.839284   0.13524009 0.34927931]
 [0.94446203 0.23738962 0.59980789 0.98253086 0.06534221]
 [0.80734476 0.99991365 0.07303701 0.00998838 0.69304775]
 [0.0207284  0.44051771 0.68712596 0.07761618 0.79084154]
 [0.80465451 0.7405007  0.53566212 0.42190955 0.46984143]]
0.4788363230001724


0.46984143218549057

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [2]:
position_type = np.dtype([
    ('x', np.int32),
    ('y', np.int32)
])
color_type = np.dtype([
    ('r', np.int32),
    ('g', np.int32),
    ('b', np.int32)    
])
pixel_type = np.dtype([
    ('position', position_type),
    ('color', color_type)
])

print(np.arange(start=-1, stop=-3, step=-1, dtype=pixel_type))
print(np.arange(start=1, stop=3, step=1, dtype=pixel_type))

print(np.arange(start=0, stop=3, step=1, dtype=pixel_type))

[((-1, -1), (-1, -1, -1)) ((-2, -2), (-2, -2, -2))]
[((1, 1), (1, 1, 1)) ((2, 2), (2, 2, 2))]


ValueError: no fill-function for data-type.

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [41]:
shape = np.array([5, 2])
identity = ([[1, 1] for i in range(5)])
print(identity)
a = np.random.random(shape) * 10
print(a)
print(a.T)
np.multiply(a, identity)

[[1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]
[[9.47743968 8.60682597]
 [7.35620992 6.87031756]
 [5.05200433 3.62373581]
 [4.33732145 3.72994235]
 [4.34982473 4.46453609]]
[[9.47743968 7.35620992 5.05200433 4.33732145 4.34982473]
 [8.60682597 6.87031756 3.62373581 3.72994235 4.46453609]]


array([[9.47743968, 8.60682597],
       [7.35620992, 6.87031756],
       [5.05200433, 3.62373581],
       [4.33732145, 3.72994235],
       [4.34982473, 4.46453609]])

In [44]:
import scipy.spatial
scipy.spatial.distance.pdist(X)

array([2.74136411, 6.6645079 , 7.08553522, 6.59173729, 3.9811627 ,
       4.35610423, 3.85047223, 0.72253128, 1.09544571, 0.73470014])

In [56]:
X,Y = np.atleast_2d(a[:,0], a[:,1])
print("X\n{}\n".format(X))
print("X.T\n{}\n".format(X.T))
print("X-X.T \n{}\n".format(X-X.T))
#print("X.T-X \n{}\n".format(X-X.T))

D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

X
[[9.47743968 7.35620992 5.05200433 4.33732145 4.34982473]]

X.T
[[9.47743968]
 [7.35620992]
 [5.05200433]
 [4.33732145]
 [4.34982473]]

X-X.T 
[[ 0.         -2.12122976 -4.42543535 -5.14011823 -5.12761495]
 [ 2.12122976  0.         -2.30420559 -3.01888847 -3.00638519]
 [ 4.42543535  2.30420559  0.         -0.71468288 -0.7021796 ]
 [ 5.14011823  3.01888847  0.71468288  0.          0.01250328]
 [ 5.12761495  3.00638519  0.7021796  -0.01250328  0.        ]]

X.T-X 
[[ 0.         -2.12122976 -4.42543535 -5.14011823 -5.12761495]
 [ 2.12122976  0.         -2.30420559 -3.01888847 -3.00638519]
 [ 4.42543535  2.30420559  0.         -0.71468288 -0.7021796 ]
 [ 5.14011823  3.01888847  0.71468288  0.          0.01250328]
 [ 5.12761495  3.00638519  0.7021796  -0.01250328  0.        ]]

[[0.         2.74136411 6.6645079  7.08553522 6.59173729]
 [2.74136411 0.         3.9811627  4.35610423 3.85047223]
 [6.6645079  3.9811627  0.         0.72253128 1.09544571]
 [7.08553522 4.35610423 0.72253128 0.   

In [44]:
# https://stackoverflow.com/a/65402572/4281353
shape = (5,2)
X = np.random.random(shape)
print(X)
# X[:,0] --> x values
# X[:,1] --> y values
dist = np.sum((X[:,np.newaxis,:] - X[np.newaxis,:,:]) ** 2, axis = -1)
np.sqrt(dist)

[[0.89040545 0.45640201]
 [0.81887744 0.14263027]
 [0.00509963 0.41263332]
 [0.80592414 0.50974166]
 [0.38134466 0.75173631]]


array([[0.        , 0.32182132, 0.8863871 , 0.09991101, 0.58852803],
       [0.32182132, 0.        , 0.85740071, 0.36733985, 0.7499634 ],
       [0.8863871 , 0.85740071, 0.        , 0.80669072, 0.50650879],
       [0.09991101, 0.36733985, 0.80669072, 0.        , 0.48870149],
       [0.58852803, 0.7499634 , 0.50650879, 0.48870149, 0.        ]])

In [51]:
X[
    (0),
    (0, 1)
]

array([0.89040545, 0.45640201])

In [47]:
X[:,np.newaxis,:]

array([[[0.89040545, 0.45640201]],

       [[0.81887744, 0.14263027]],

       [[0.00509963, 0.41263332]],

       [[0.80592414, 0.50974166]],

       [[0.38134466, 0.75173631]]])

In [46]:
X[np.newaxis,:,:]

array([[[0.89040545, 0.45640201],
        [0.81887744, 0.14263027],
        [0.00509963, 0.41263332],
        [0.80592414, 0.50974166],
        [0.38134466, 0.75173631]]])

In [48]:
X[:,:,np.newaxis]

array([[[0.89040545],
        [0.45640201]],

       [[0.81887744],
        [0.14263027]],

       [[0.00509963],
        [0.41263332]],

       [[0.80592414],
        [0.50974166]],

       [[0.38134466],
        [0.75173631]]])

In [37]:
from numpy import array, newaxis
a = array([0.0, 10.0, 20.0, 30.0])
b = array([1.0, 2.0, 3.0])

print("a as shape{} is {} before newaxis.".format(a.shape, a))
print("b as shape{} is {}.".format(b.shape, b))

try:
    print(a + b)
except ValueError as e:
    print("(a.shape{} + b.shape{}) causes '{}'.\n".format(a.shape, b.shape, e))
    pass

a = a[
    :,        # dimension 1
    newaxis   # new dimension 2
]
print("a.shape after a[:, newaxis] is {}.".format(a.shape))

# stretching of both arrays to produce the desired 4x3 output array.
c = a + b
print("shape a{} + b{} streach both arrays into shape{} and produce:\n{}".format(
    a.shape, b.shape, c.shape, c
))


a as shape(4,) is [ 0. 10. 20. 30.] before newaxis.
b as shape(3,) is [1. 2. 3.].
(a.shape(4,) + b.shape(3,)) causes 'operands could not be broadcast together with shapes (4,) (3,) '.

a.shape after a[:, newaxis] is (4, 1).
shape a(4, 1) + b(3,) streach both arrays into shape(4, 3) and produce:
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [62]:
np.array(32, dtype=np.float32).astype(np.int32)

array(32, dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [78]:
a = np.array([
    [9, 2, 3, 1],
    [4, 5, 6, 2],
    [7, 0, 5, 4]
])
print(a.shape)
means = a.mean(axis=1)[
    ::,
    np.newaxis
]
print(means)
print(means.shape)
a - means

(3, 4)
[[3.75]
 [4.25]
 [4.  ]]
(3, 1)


array([[ 5.25, -1.75, -0.75, -2.75],
       [-0.25,  0.75,  1.75, -2.25],
       [ 3.  , -4.  ,  1.  ,  0.  ]])

In [81]:
a = np.array([
    [9, 2, 3, 1],
    [4, 5, 6, 2],
    [7, 0, 5, 4]
])
a - a.mean(axis=1, keepdims=True)

array([[ 5.25, -1.75, -0.75, -2.75],
       [-0.25,  0.75,  1.75, -2.25],
       [ 3.  , -4.  ,  1.  ,  0.  ]])

#### 59. How to sort an array by the nth column? (★★☆)

In [68]:
a = np.array([
    [9, 2, 3, 1],
    [4, 5, 6, 2],
    [7, 0, 5, 4]
])
sorted_row_indices = a[::,1].argsort() # row indices to sort rows by 2nd column 
print(sorted_row_indices)
sorted_rows = a[sorted_row_indices]
print(sorted_rows)

# a[(2, 0, 1)] is the same with
# a[
#   (2, 0, 1),
#   ::
#]

[2 0 1]
[[7 0 5 4]
 [9 2 3 1]
 [4 5 6 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [16]:
a = np.random.random((3,4))
a[1][2]=0.
print(a)
print(a.all(axis=0).all() == True)

[[0.7712959  0.28548046 0.48856075 0.19891033]
 [0.81769574 0.61816762 0.         0.15161647]
 [0.72000048 0.75293718 0.35973609 0.32008668]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [41]:
a = np.array([1,2,3,4])
a = a[
    ::,
    np.newaxis,
    np.newaxis
]
print(a)
print(a.shape)
print()

b = np.random.random((4, 3)) * 5
b = b[
    ::,
    ::
]
print("b is \n{}".format(b))
print(b.shape)
print()

print("b-a is \n{}\n".format(b-a))
print()

index = (np.abs((b-a)).argmin())
print(index)
print((b-a).flat[index])

[[[1]]

 [[2]]

 [[3]]

 [[4]]]
(4, 1, 1)

b is 
[[2.89218076 3.66395411 3.79569888]
 [4.57092262 0.63108437 3.1183377 ]
 [0.38071397 1.27679347 4.49779511]
 [0.9098184  0.8389455  4.69246343]]
(4, 3)

b-a is 
[[[ 1.89218076  2.66395411  2.79569888]
  [ 3.57092262 -0.36891563  2.1183377 ]
  [-0.61928603  0.27679347  3.49779511]
  [-0.0901816  -0.1610545   3.69246343]]

 [[ 0.89218076  1.66395411  1.79569888]
  [ 2.57092262 -1.36891563  1.1183377 ]
  [-1.61928603 -0.72320653  2.49779511]
  [-1.0901816  -1.1610545   2.69246343]]

 [[-0.10781924  0.66395411  0.79569888]
  [ 1.57092262 -2.36891563  0.1183377 ]
  [-2.61928603 -1.72320653  1.49779511]
  [-2.0901816  -2.1610545   1.69246343]]

 [[-1.10781924 -0.33604589 -0.20430112]
  [ 0.57092262 -3.36891563 -0.8816623 ]
  [-3.61928603 -2.72320653  0.49779511]
  [-3.0901816  -3.1610545   0.69246343]]]


9
-0.09018159870398246


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)