In [1]:
import numpy as np

# newaxis (newunit)
## Army analogy

When an army is small enough with 12 soldiers, a ```company``` of two levels (```squad```, ```soldier```) is sufficient.

``` 
company[
    ::   # squads   - dimension (grouping unit) 2
    ::   # soldiers - dimension (terminal unit) 1
]
```

Organize soldiers into a company (3 squads, 4 soldiers)=shape(3, 4):
```
company=[
  [ 0  1  2  3]   # squad 0: soldier (0, 1, 2, 3) 
  [ 4  5  6  7]   # squad 1
  [ 8  9 10 11]   # suqad 2
]
```

Note: **DO NOT mix up numpy slice format with the print output of the ndarray.**

In [20]:
army = company = np.arange(12).reshape((3,4))
print(company[
    ::,soldiers
    ::
])
print(company.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


### New unit platoon
Army needs to grow into 100 squads for a war, hence introduces a new structure **before** accepting new recruits.<br>

1. Introduce ```platoon```, a new **unit to group** squads.
2. Reorganize the existing squads into . 

```
compay=[
    ::,        # platoons - dimension 3
    newaxis,   # squads   - dimension 2, 
    ::         # soldiers - dimension 1
]
```

**Result:**
```
company=[      
  [                # platoon 0
    [ 0  1  2  3]  # squad 0 in platoon
  ]
  [                # platoon 1
    [ 4  5  6  7]  # squad 0
  ]
  [                # platoon 2
    [ 8  9 10 11]  # squad 0
  ]
]
```

In [87]:
company = company[
    ::,
    np.newaxis,
    ::
]
print(company)
print(company.shape)

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
(3, 1, 4)


In [16]:
a2 = a[
    np.newaxis, # dimension (n+1=3)
    ::,         # dimension 2
    ::,         # dimension 1
]
print(a2)
print(a2.shape)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
(1, 3, 3)


## Elevate dimensions

In [90]:
x=np.array([1,2,3])
y=np.array([4])
print("x.shape is {} y.shape is {}".format(x.shape, y.shape))
print("x+y is {}".format(x+y))

x.shape is (3,) y.shape is (1,)
x+y is [5 6 7]


In [111]:
A = np.arange(20).reshape((4, 5, 1))
B = np.arange(2).reshape((1,2))
print("A.shape {}".format(A.shape))
print("B.shape {}".format(B.shape))
print("A * B shape is {}".format((A*B).shape))

print("A * B is {}".format(A*B))

print("rank(A) {} rank(B) {}".format(A.ndim, B.ndim))
B = B[
    None,
    ::
]
B.shape

A.shape (4, 5, 1)
B.shape (1, 2)
A * B shape is (4, 5, 2)
A * B is [[[ 0  0]
  [ 0  1]
  [ 0  2]
  [ 0  3]
  [ 0  4]]

 [[ 0  5]
  [ 0  6]
  [ 0  7]
  [ 0  8]
  [ 0  9]]

 [[ 0 10]
  [ 0 11]
  [ 0 12]
  [ 0 13]
  [ 0 14]]

 [[ 0 15]
  [ 0 16]
  [ 0 17]
  [ 0 18]
  [ 0 19]]]
rank(A) 3 rank(B) 2


(1, 1, 2)

rank(A) 3 rank(B) 2
1


(1, 1, 2)

In [86]:
print(z[(1,1,1,1)])

40


In [17]:
a3= a[
    ::,         # dimension 2 -> 3
    np.newaxis, # dimension new 2
    ::,         # dimension 1
]
print(a3)
print(a3.shape)

[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]
(3, 1, 3)


In [ ]:

from numpy import array, newaxis
import numpy as np
a = np.arange(27).reshape((3,3,3))
print(a)
a = a[
    newaxis,
    :,
    :,
    :
]
a