In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.4.1'

In [4]:
tf.__name__

'tensorflow'

In [5]:
np.__name__

'numpy'

In [33]:
type(float)
type(int)

type

# TF Tensor

In numpy, objects of the primitive types e.g. ```np.float32``` are scalar and ```ndarray``` are array. 

In Tensorflow, both scalar and array are ```tf.Tensor``` that has ```dtype``` attribute.

## Scalar tenror

In [15]:
a = tf.constant(1, dtype=tf.float16)
print(f"tf.dtype {a.dtype} \nnp.dtype {a.dtype.as_numpy_dtype} \nshape {a.shape}")

tf.dtype <dtype: 'float16'> 
np.dtype <class 'numpy.float16'> 
shape ()


## Array tensor

In [17]:
x = tf.constant(np.random.rand(2,3,3))
print(f"x is \n{x}\ndtype is {x.dtype}\nshape is {x.shape}")
print(f"{tf.is_tensor(x)}")

x is 
[[[0.44974658 0.10869782 0.91826837]
  [0.77181561 0.40196069 0.89430434]
  [0.56086304 0.29416828 0.74066197]]

 [[0.98836431 0.03492795 0.43018318]
  [0.1153405  0.46684043 0.76705678]
  [0.89914149 0.09460138 0.48544693]]]
dtype is <dtype: 'float64'>
shape is (2, 3, 3)
True


## TF of float type

### Check if Tensor is float

#### Tensor.dtype.is_floating 

* [tf.dtypes.DType](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType)

> is_floating:  Returns whether this is a (non-quantized, real) floating point type.<br>
> is_integer:	Returns whether this is a (non-quantized) integer type.

In [58]:
tf.constant(np.random.rand(3,4)).dtype.is_floating

True

#### ```Tensor.dtype.__eq__(other)``` 

> __eq__(other): Returns True if this DType refers to the same type as other.


#### ```Tensor.dtype.__ne__(other)```

> __ne__(other): Returns True if self != other.

In [66]:
a = tf.constant(np.random.rand(3,4), dtype=np.float32) # np.dtype can be used
a.dtype.__eq__(tf.float32)

True

#### Tensor.dtype.as_numpy_dtype

> as_numpy_dtype:	Returns a Python type object based on this DType.

In [61]:
def is_np_float_type(dtype):
    return np.issubdtype(dtype, np.floating)

In [62]:
a = tf.constant(np.random.rand(3,4))
is_np_float_type(a.dtype.as_numpy_dtype)

True

## Check if tf.Tensor

* [is_tensor(x)](https://www.tensorflow.org/api_docs/python/tf/is_tensor)

### numpy array is not a TF tensor for sure

In [55]:
tf.is_tensor(np.float32(1))

False

In [56]:
a = tf.constant(np.float32(1), dtype=tf.float16)
tf.is_tensor(a)

True

---
# Type Casting

Tensorflow does not automatically cast types as it is an expesive operation. Need to be explicit.


## dtype mapping to TF from Python/Numpy

* [tf.dtypes.as_dtype(type)](https://www.tensorflow.org/api_docs/python/tf/dtypes/as_dtype)
* [Why Python “int” cannot be converted into Tensorflow dtype?](https://stackoverflow.com/questions/66977630)

In [34]:
print("np.float equivalent in TF is %s" % tf.dtypes.as_dtype(np.float))
print("Python float equivalent in TF is %s" % tf.dtypes.as_dtype(float))
# TypeError: Cannot convert value <class 'int'> to a TensorFlow DType. 
# print("Python int equivalent in TF is %s" % tf.dtypes.as_dtype(int))

np.float equivalent in TF is <dtype: 'float32'>
Python float equivalent in TF is <dtype: 'float32'>


## [tf.cast(x, dtype, name=None)](https://www.tensorflow.org/api_docs/python/tf/cast)


### float32 to 16

In [35]:
a = tf.reshape(tf.range(12, dtype=tf.float32), (3,4))
print(f"a.dtype is {a.dtype}")

# cast 32 to 16
a = tf.cast(a, tf.float16)
a.dtype

a.dtype is <dtype: 'float32'>


tf.float16

---
# Python Type Hint cannot be used

Python type hint does not recognize TF dtypes causing ```TypeError: Union[arg, ...]: each arg must be a type.```

In [1]:
from typing import (
    Union,
)
import tensorflow as tf
import numpy as np


def f(a: Union[tf.int32, tf.float32]):
    return a * 2


def g(a: Union[np.int32, np.float32]):
    return a * 2


def test():
    f(tf.cast(1.0, dtype=tf.float32))
    # g(np.float32(1.0))  # No issue

test(a)

TypeError: Union[arg, ...]: each arg must be a type. Got tf.int32.

In [13]:
a = tf.constant(1, dtype=tf.float16)
a.dtype.is_floating
tuple(a.shape.as_list())

()