In [1]:
import numpy as np
import tensorflow as tf

In [2]:
box = tf.constant([
    [0.410025716, 0.557291687, 0.732647777, 0.827083349],
    [0.424164534, 0.362499982, 0.365038544, 0.433333337],
    [0.645244241, 0.727083325, 0.241645277, 0.254166663],
    [0.593830347, 0.65, 0.185089946, 0.179166675]
])
box

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.41002572, 0.5572917 , 0.7326478 , 0.82708335],
       [0.42416453, 0.36249998, 0.36503854, 0.43333334],
       [0.64524424, 0.7270833 , 0.24164528, 0.25416666],
       [0.59383035, 0.65      , 0.18508995, 0.17916667]], dtype=float32)>

In [12]:
index = tf.constant([[12], [14], [12], [14]], dtype=tf.dtypes.float32)
index

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[12.],
       [14.],
       [12.],
       [14.]], dtype=float32)>

# Stack

Stacks a list of rank ```R``` tensors **with the same shape and type** into one rank ```(R+1)``` tensor, hence **automatically add an axis**.

> if axis == 0 then the output tensor will have the shape (N, A, B, C). if axis == 1 then the output tensor will have the shape (A, N, B, C). Etc.

* [tf.stack](https://www.tensorflow.org/api_docs/python/tf/stack)

> Stacks a list of rank-R tensors into one rank-(R+1) tensor.
> ```
> tf.stack(
>     values, axis=0, name='stack'
> )
> ```
> 
> * values:  
> A list of Tensor objects with the **same shape and type**.

```tf.concat``` does not change the rank (not add an axis).

In [13]:
tf.print("box shape", tf.shape(box), "index shape: ", tf.shape(index))

box shape [4 4] index shape:  [4 1]


Failes because the shapes are different. ```tf.stack``` does not have the automatic broadcasting mechanism like in numpy.

In [14]:
tf.stack([index, box])

InvalidArgumentError: {{function_node __wrapped__Pack_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Shapes of all inputs must match: values[0].shape = [4,1] != values[1].shape = [4,4] [Op:Pack] name: stack

---
# tf.concat

* [tf.concat](https://www.tensorflow.org/api_docs/python/tf/concat)

```
tf.concat(
    values, axis, name='concat'
)
```


> * axis : Mandatory argument of ```0``` - ```D``` int32 Tensor.   
> Dimension along which to concatenate. Must be in the range ```[-rank(values), rank(values))```.   
> Positive axis in the rage of ```[0, rank(values))``` refers to ```axis-th``` dimension and Negative axis refers to ```axis + rank(values)```-th dimension.

In [15]:
tf.concat([index, box], axis=-1)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[12.        ,  0.41002572,  0.5572917 ,  0.7326478 ,  0.82708335],
       [14.        ,  0.42416453,  0.36249998,  0.36503854,  0.43333334],
       [12.        ,  0.64524424,  0.7270833 ,  0.24164528,  0.25416666],
       [14.        ,  0.59383035,  0.65      ,  0.18508995,  0.17916667]],
      dtype=float32)>