In [1]:
import tensorflow as tf
import numpy as np

# Horizontal Stack

* np.concatenate(axix=1)
* np.c_
* np.hstack
* tf.concat(axis=1)

In [2]:
a = np.arange(12).reshape((3,4))

In [3]:
np.c_[a, a]

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [4]:
np.concatenate((a,a), axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [5]:
np.hstack([a,a])

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [6]:
tf.concat([a,a], axis=1)

<tf.Tensor: shape=(3, 8), dtype=int64, numpy=
array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])>

In [14]:
def concat(*values, axis=0):
    return tf.concat(*values, axis=axis)

def concat_numpy(*values, axis=0):
    return np.concatenate(*values, axis=axis)

In [15]:
concat((a,a,a), axis=1)

<tf.Tensor: shape=(3, 12), dtype=int64, numpy=
array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11]])>

In [16]:
concat_numpy((a,a,a), axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11]])