# Python built-in zip 

* ```zip(*iterables, strict=False)``` returns an **iterator of tuples**. 
* ```tuple(zipped)``` materializes the zip object.
* zip object is **consumable**, cannot use it twice.

## Consumable

In [6]:
zipped = zip(["a", "b", "c"], [1, 2, 3])

Materialize the zip object (iterator) - 1st

In [7]:
print(tuple(zipped))

(('a', 1), ('b', 2), ('c', 3))


Materialize the zip object (iterator) - 2nd. Empty because the zip object has been already consumed.

In [8]:
print(tuple(zipped))

()


## Non consumable
To reused the zip object content, use the materielized. 

In [9]:
zipped = zip(["a", "b", "c"], [1, 2, 3])
materialized = tuple(zipped)

In [10]:
print(materialized)  # 1st

(('a', 1), ('b', 2), ('c', 3))


In [11]:
print(materialized)  # 2nd

(('a', 1), ('b', 2), ('c', 3))


---

# Example - Minimize cost

* For a cost matrix M where ```M[row][col]``` represents a cost of a work. 
```
[6 8 4]
[1 2 2]
[1 1 6]
```
* At each row, a machine can work on one item.
* No machine can place in the same row. For instance (0, 1) and (1, 1) are not allowed.

The optimal machine coordinates are ```((0, 2), (1, 0), (2, 1))``` where the cost is 6 as ```(4, 1, 1)```.

Possible costs : ```[14, 9, 15, 11, 6, 7]```.

In [12]:
import collections as C
import itertools as I
import functools as F
import numpy as np

In [13]:
cost_matrix = np.random.randint(low=1, high=9, size=9).reshape((3,3))
print(cost_matrix)

[[3 2 2]
 [1 1 8]
 [3 7 4]]


In [25]:
N = 3
column_indices = range(N)
row_indices = range(N)

print("All possible non-sorted combinations of column position of a machine at each row")
column_combinations = list(I.permutations(column_indices, N))
print(column_combinations)

print("\nAll possible non-column-overlapping coordinates")
coordinates = [tuple(zip(row_indices, c)) for c in column_combinations]
for coordinate in coordinates:
    print(coordinate)

print("\nAll possible costs for the coordinates")
costs = [
    sum([cost_matrix[row][column] for row, column, in coordinate]) 
    for coordinate in coordinates
]
print(costs)       

index_of_min_cost = costs.index(min(costs))
print(f"\nMinimal cost {min(costs)} is at index {index_of_min_cost}")
print(f"Coordinate for the min cost is {coordinates[index_of_min_cost]}")

All possible non-sorted combinations of column position of a machine at each row
[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

All possible non-column-overlapping coordinates
((0, 0), (1, 1), (2, 2))
((0, 0), (1, 2), (2, 1))
((0, 1), (1, 0), (2, 2))
((0, 1), (1, 2), (2, 0))
((0, 2), (1, 0), (2, 1))
((0, 2), (1, 1), (2, 0))

All possible costs for the coordinates
[8, 18, 7, 13, 10, 6]

Minimal cost 6 is at index 5
Coordinate for the min cost is ((0, 2), (1, 1), (2, 0))
