# Multiple slices from iterable

# Generic function

In [100]:
import numpy as np
def xslice(x, slices):
    """Extract slices from array-like
    Args:
        x: array-like
        slices: slice or tuple of slice objects
    """
    if isinstance(slices, tuple):
        if isinstance(x, np.ndarray):
            return np.concatenate([x[_slice] for _slice in slices])
        else:
            return sum((x[s] if isinstance(s, slice) else [x[s]] for s in slices), [])        
    elif isinstance(slices, slice):
        return x[slices]
    else:
        return [x[slices]]
    

In [102]:
print(xslice(
    list(range(15)), s_[1:3, 5:7, 9:11]
))
print(xslice(
    list(range(15)), s_[:]
))

print(xslice(
    np.arange(15), s_[1:3, 5:7, 9:11]
))


[1, 2, 5, 6, 9, 10]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[ 1  2  5  6  9 10]


In [70]:
import numpy as np
a = np.arange(15)
a[np.r_[1:3, 5:7, 9:11]]

array([ 1,  2,  5,  6,  9, 10])

# Python iterable

In [67]:
import numpy as np
_list = list(range(15))
print("List is {}\n".format(_list))

print(sum(
    [ _list[_slice] for _slice in np.s_[1:3, 5:7, 9:11] ], 
    start=[]
))

List is [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

[1, 2, 5, 6, 9, 10]


In [50]:
import numpy as np
a = list(range(15))
print("array is {}\n".format(a))

result = []
slices = np.s_[1:3, 5:7, 9:11]
for _slice in slices:
    print("Adding a slice {} to the current result {}".format(
        a[_slice], result
    ))
    result = sum(
        [ a[_slice] ],  # Extract from outer list to do [...] + [...] operation
        start=result
    )

result

array is [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

Adding a slice [1, 2] to the current result []
Adding a slice [5, 6] to the current result [1, 2]
Adding a slice [9, 10] to the current result [1, 2, 5, 6]


[1, 2, 5, 6, 9, 10]

---

# numpy array

## One line

In [48]:
import numpy as np
a = np.arange(15, 50, 3).astype(np.int32)

In [50]:
%%timeit -n 10000
a[np.r_[1:3, 5:7, 9:11]]

31.6 µs ± 7.11 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [38]:
%%timeit -n 10000
[a[index] for index in np.r_[1:3, 5:7, 9:11]]

43.8 µs ± 1.28 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [39]:
%%timeit -n 10000
slices = np.s_[1:3, 5:7, 9:11]
np.concatenate([a[_slice] for _slice in slices])

7.17 µs ± 1.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [43]:
import numpy as np
a = np.arange(15, 50, 3).astype(np.int32)
slices = np.s_[1:3, 5:7, 9:11]
np.concatenate([a[_slice] for _slice in slices])

array([18, 21, 30, 33, 42, 45], dtype=int32)

In [40]:
a = list(range(15, 50, 3))

In [41]:
%%timeit -n 10000
[a[index] for index in np.r_[1:3, 5:7, 9:11]]

41.1 µs ± 1.71 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## loop

In [52]:
import numpy as np
a = np.arange(15).astype(np.int32)

result = np.array([], dtype=np.int32)
slices = s_[1:3, 5:7, 9:11]

for _slice in slices:
    result = np.append(result, a[_slice])
    
print(result)

array is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

True
[ 1  2  5  6  9 10]
[array([1, 2], dtype=int32), array([5, 6], dtype=int32), array([ 9, 10], dtype=int32)]


array([ 1,  2,  5,  6,  9, 10], dtype=int32)

## Python sum() is not applicable to numpy

In [66]:
import numpy as np
_list = np.arange(15)
print("List is {}\n".format(_list))

print(sum(
    [ _list[_slice] for _slice in np.s_[1:3, 5:7, 9:11] ], 
    start=[]
))

List is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]



ValueError: operands could not be broadcast together with shapes (0,) (2,) 

In [54]:
import numpy as np
a = np.arange(15)
print("array is {}\n".format(a))

result = []
slices = s_[1:3, 5:7, 9:11]
for _slice in slices:
    print("Adding a slice {} to the current result {}".format(
        a[_slice], result
    ))
    result = sum(
        [ a[_slice] ],
        result
    )

result

array is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Adding a slice [1 2] to the current result []


ValueError: operands could not be broadcast together with shapes (0,) (2,) 