In [1]:
import torch

In [10]:
x = torch.arange(12).view(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
x[:, 0::2]

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10]])

In [14]:
x[:, :2]

tensor([[0, 1],
        [4, 5],
        [8, 9]])