In [1]:
import numpy as np

# 0.1 is not 0.1

In [4]:
print(0.1 * 3)
print(30 / 100)
0.1 * 3 == 30 / 100

0.30000000000000004
0.3


False

In [9]:
print("{:.52f}".format(0.1))

0.1000000000000000055511151231257827021181583404541016


# Mean of the same values may not be the value

If the value X is all ```-3.29686744```, then ```X-mean``` is expected to be ```0``` but it may not.


In [13]:
X = np.array([
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096]
])

mean = np.mean(X, axis=0)
print(f"mean is \n{mean}\nX-mean is \n{X-mean}\n")

sd = np.std(X, axis=0)
print(f"SD is \n{sd}\n")

mean is 
[-1.11793447 -3.29686744 -3.50615096]
X-mean is 
[[0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]
 [0.0000000e+00 4.4408921e-16 4.4408921e-16]]

SD is 
[0.0000000e+00 4.4408921e-16 4.4408921e-16]



In [12]:
X = np.array([
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096],
    [-1.11793447, -3.29686744, -3.50615096]
])

mean = np.mean(X, axis=0)
print(f"mean is \n{mean}\nX-mean is \n{X-mean}\n")

sd = np.std(X, axis=0)
print(f"SD is \n{sd}\n")

mean is 
[-1.11793447 -3.29686744 -3.50615096]
X-mean is 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

SD is 
[0. 0. 0.]



In [15]:
X = np.array([
    [-1.11793447, -3.29686744, -3.50615096],
])

mean = np.mean(X, axis=0)
print(f"mean is \n{mean}\nX-mean is \n{X-mean}\n")

sd = np.std(X, axis=0)
print(f"SD is \n{sd}\n")

mean is 
[-1.11793447 -3.29686744 -3.50615096]
X-mean is 
[[0. 0. 0.]]

SD is 
[0. 0. 0.]

