# newaxis

In [1]:
import numpy as np

In [5]:
Z = np.arange(12).reshape(3, 4)
print(Z)
print(Z.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


## Upper newaxis
1. Create a new array.
2. Add Z inside the new array.

In [4]:
Z_UPPER = Z[
    np.newaxis,
    ::
]
print(Z_UPPER)
print(Z_UPPER.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
(1, 3, 4)


In [14]:
np.array([ Z ])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

## Lower newaxis

1. Unpack Z and extract each element.
2. Pack each element in a new array respectively.
3. Aggregate new arrays.

In [7]:
Z_LOWER = Z[
    ::,
    np.newaxis
]
print(Z_LOWER)
print(Z_LOWER.shape)

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
(3, 1, 4)


In [12]:
np.array([ [e] for e in Z])

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])