# How to apply function to slice

* [Best way to apply a function to a slice of a 3d numpy array](https://stackoverflow.com/questions/49480148/best-way-to-apply-a-function-to-a-slice-of-a-3d-numpy-array)

> vectorize normally feeds scalars to the function, but the newer versions have signature parameter that allow us to use it as:
> ```f = np.vectorize(foo, signature='(n,m)->()')```

In [1]:
import numpy as np

In [3]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Transpose sub arrays

In [20]:
def f(x: np.ndarray) -> np.ndarray:
    assert x.shape == (3, 4)
    return x.T


In [21]:
f_vectorized = np.vectorize(f, signature="(n,d)->(d,n)")

In [22]:
f_vectorized(a)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

## Column-wise mean on each subarray (3, 4)

In [29]:
def column_wise_mean(x: np.ndarray) -> np.ndarray:
    assert x.shape == (3, 4)
    return x.mean(axis=0, keepdims=True)

In [30]:
column_wise_mean_vectorized = np.vectorize(column_wise_mean, signature="(n,d)->(1,d)")

In [31]:
column_wise_mean_vectorized(a)

array([[[ 4.,  5.,  6.,  7.]],

       [[16., 17., 18., 19.]]])