In [3]:
import numpy as np

# In-place operation
Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

# Accumulative updates

Default bufferd operation only increments each element only once.

In [31]:
a = np.arange(12).reshape((3, 4))
b = a.copy()
print(f"a:\n{a}\n")

print("How to add +1 multiple times at index i?")
a[
  1, 
  [0, 2, 0, 2, 0]
] += 1

expression="""a[
  ::, 
  [0, 2, 0, 2]  # Expected [4+2, 5, 6+2, 7] as adding +1 twice at column 0 and 2 
] += 1\n--------------------"""
print(f"{expression}\n{a}\n")

print(f"Acutal is +1 only once at column 0 and 2\n{a-b}")

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

How to add +1 multiple times at index i?
a[
  ::, 
  [0, 2, 0, 2]  # Expected [4+2, 5, 6+2, 7] as adding +1 twice at column 0 and 2 
] += 1
--------------------
[[ 0  1  2  3]
 [ 5  5  7  7]
 [ 8  9 10 11]]

Acutal is +1 only once at column 0 and 2
[[0 0 0 0]
 [1 0 1 0]
 [0 0 0 0]]


<img src='images/numpy_accumulative_update.png' width=750 align='left'/>

## [numpy.ufunc.at(a, indices, b=None)](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.at.html)

Operation on operand ‘a’ for **each elements specified by ‘indices’**. Results are accumulated for elements that are indexed more than once because **unbuffered**. 

```[[0,0]] += 1``` will only increment the first element once because of buffering, whereas ```add.at(a, [0,0], 1)``` will increment the first element twice.

### [Universal functions (ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html)
> A universal function (or ufunc for short) is a function that **operates on ndarrays in an element-by-element** fashion, supporting array broadcasting, type casting, and several other standard features. That is, a ufunc is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.



In [83]:
a = np.arange(12).reshape((3, 4))
print(f"a:\n{a}\n")

indices = (
    ...,  # same with slice(0:None)
    (0,2,0,2)
)
np.add.at(
    a, 
    indices,
    1
)
print(a - b)

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[2 0 2 0]
 [2 0 2 0]
 [2 0 2 0]]


---
# Update a view with ```np.ufunc.at```.

In [84]:
N = 5
D = 4
W = np.arange(N*D).reshape((N,D))
print(f"W is {W}\n")

W is [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

