In [1]:
import numpy as np

# Boolean to Integer

In [2]:
a = np.array([ True, True, True, False], dtype=bool)
a

array([ True,  True,  True, False])

### Use astype()

In [3]:
i = a.astype(int)
i

array([1, 1, 1, 0])

### Add 0

In [4]:
a + 0

array([1, 1, 1, 0])

---

# Integer to Boolean

In [5]:
i = np.array([1, 1, 1, 0])
i

array([1, 1, 1, 0])

In [6]:
t = i.astype(bool)
t

array([ True,  True,  True, False])