In [1]:
import numpy as np

# isin
## Select those rows where ```row[:1]``` NOT in a list

In [56]:
#%%timeit
E = 1
C = 4
BATCH_SIZE = 2
N = 2

event_context = np.random.randint(0, 11, (BATCH_SIZE,(E+C)))
print(event_context)
EVENT_INDEX_META_ENTITIES = [1,5,9]
event_context = event_context[
    np.logical_not(np.sum(
        np.isin(
            event_context[
                ::,                 # All (event, context) pairs,
                :E     # 'event' part
            ],
            EVENT_INDEX_META_ENTITIES
        ),
        axis=-1
    ).astype(bool)),
]
print(event_context)
del event_context

[[1 6 8 1 8]
 [0 3 1 3 5]]
[[0 3 1 3 5]]


In [62]:
#%%timeit
E = 1
C = 4
BATCH_SIZE = 2
N = 2

event_context = np.random.randint(0, 11, (N,BATCH_SIZE,(E+C)))
print(event_context)
EVENT_INDEX_META_ENTITIES = [-9]
event_context = event_context[
    np.logical_not(np.sum(
        np.isin(
            event_context[
                ::,                 # All batches
                ::,                 # All (event, context) pairs,
                :E     # 'event' part
            ],
            EVENT_INDEX_META_ENTITIES
        ),
        axis=-1
    ).astype(bool)),
]
print(event_context)
del event_context

[[[ 5 10 10  1  4]
  [ 9  4  8  5  6]]

 [[ 7  3  6  9  4]
  [ 5  4  7  4  3]]]
[[ 5 10 10  1  4]
 [ 9  4  8  5  6]
 [ 7  3  6  9  4]
 [ 5  4  7  4  3]]


# Conditional

In [2]:
x = np.array(range(12)).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
x > 6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [4]:
x[x > 6]

array([ 7,  8,  9, 10, 11])