# Boolean indexing

In [1]:
import numpy as np

In [3]:
y = np.arange(20).reshape(5,4)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [4]:
print(y[
    [0, 2, 4],
    ::
])
print(y[
    [0, 2, 4],
    ::
])
print(y[
    [True, False, True, False, True],
    ::
])
print()

print("""y[
    (True, False, True, False, True)
] is \n{}\n with shape {}\n""".format(
    y[
        (True, False, True, False, True)
    ], 
    y[
        (True, False, True, False, True)
    ].shape    
))

print("""y[True] is \n{}\n with shape {}\n""".format(
    y[True], 
    y[True].shape
))

print("""y[True, True] is \n{}\n with shape {}\n""".format(
    y[True, True], 
    y[True, True].shape
))

print("""y[True] is \n{}\n with shape {}\n""".format(
    y[True, False], 
    y[True, False].shape
))


[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]

y[
    (True, False, True, False, True)
] is 
[]
 with shape (0, 5, 4)

y[True] is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]]
 with shape (1, 5, 4)

y[True, True] is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]]
 with shape (1, 5, 4)

y[True] is 
[]
 with shape (0, 5, 4)

