# reduce

In [2]:
import numpy as np

## Column-wise addition

In [4]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[5, 6, 7], [8, 9, 10]])
c = np.array([[5, 6, 7], [8, 9, 10]])
np.add.reduce((a, b, c), axis=0).tolist()

[[11, 14, 17], [20, 23, 26]]

In [5]:
a = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
print(a)
np.add.reduce(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [10]:
a = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
b = a * 10
c = b * 10
print(a)
print(b)
print(c)
print(np.add.reduce((a, b, c)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[100 200 300]
 [400 500 600]
 [700 800 900]]
[[111 222 333]
 [444 555 666]
 [777 888 999]]
