# Find the index of value(s) in array X

In [1]:
import numpy as np

In [36]:
X = np.array([ 1,  5,  2, 19,  7, 15, 16, 17, 11, 13,  4, 12])
X

array([ 1,  5,  2, 19,  7, 15, 16, 17, 11, 13,  4, 12])

# Objective
Find the indices of values [5, 7, 4] in X

## Warning

**DO NOT** use [numpy.in1d(ar1, ar2, assume_unique=False, invert=False, *, kind=None)](https://numpy.org/doc/stable/reference/generated/numpy.in1d.html) because it does **NOT preserve the order** of the values occur in X. ```in1d``` is good to find if the values are in X or not.

## Find indices to the values

* [numpy.searchsorted(a, v, side='left', sorter=None)](https://numpy.org/doc/stable/reference/generated/numpy.searchsorted.html)

> Find the indices into a sorted array ```a``` such that.  
> * sorter: array of integer indices to sort the array ```a``` in an ascending order in case it is not sorted


NOTE: Not same with TLB where TLB size is enough for physical memory page numbers, far smaller than VM space size.

<img src="./images/indices_to_values_in_array.png" align="left" width=500/>

# Mechanism

Example to find the index to 5 in the array x

In [40]:
sorted_X = X[np.argsort(X)]
sorted_X

array([ 1,  2,  4,  5,  7, 11, 12, 13, 15, 16, 17, 19])

In [47]:
indices_to_sorted = indices_to_map_table = np.argsort(X)
indices_to_sorted

array([ 0,  2, 10,  1,  4,  8, 11,  9,  5,  6,  7,  3])

1. Find the index to the value 5 in the sorted X.

This is equiavelnt with finding the virutla memory address where the value 5 is stored. In ```sorted_X```, the value ```5``` is at the index ```3```.


In [38]:
address_in_virtual_memory = np.searchsorted(a=X, v=[5], sorter=indices_to_sorted)
address_in_virtual_memory

array([3])

2. Use the index as the index at argsorted as well.

This is equivalent with the mapping table index where the record value is the physical memory address in which the actual value 5 is stored.

In [42]:
address_in_physical_memory = indices_to_sorted[address_in_virtual_memory]
address_in_physical_memory

array([1])

Verify the value at the address in physical memory (X)

In [43]:
X[address_in_physical_memory]

array([5])

# Implementation 

Find the indices of the values in Sorted X

In [49]:
indices_into_sorted_X = indices_into_map_table = np.argsort(X)
indices_of_values_in_sorted_X = np.searchsorted(a=X, v=[5, 7, 4], sorter=indices_into_sorted_X)

The indices are used for the map table (artsort of X) to get the indices of the values in X.

Virutual memory address (indices of sorted X) to physical memory address (indices of X) for the values.

In [51]:
indices_of_values_in_X = indices_into_map_table[indices_of_values_in_sorted_X]
indices_of_values_in_X

array([ 1,  4, 10])

In [52]:
X[indices_of_values_in_X]

array([5, 7, 4])