In [1]:
import numpy as np

# vstack
```np.vstack([...])``` : takes out the elements of ```[...]``` (monad bind) and concatenate all elements back into a list (monad unit).

In [2]:
a = np.vstack([
    np.array([]).reshape(0, 5),
    np.array([1,2,3,4,5]), 
    np.array([10, 20, 30, 40, 50])
]).astype(np.int32)
print(a.shape)
print(a)

(2, 5)
[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [3]:
a = np.arange(15).reshape(3, 5)
print(a)

np.vstack([
    [0,1,2,3,4],
    a
])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Vertical stack same rows without vstack

In [4]:
N = 5
M = 3
row = np.random.uniform(
    -5, 5, M
).astype(float)
print(f"{row}\n")
X = np.ones((N, M)) * row
X

[3.64723539 1.32567096 0.0771877 ]



array([[3.64723539, 1.32567096, 0.0771877 ],
       [3.64723539, 1.32567096, 0.0771877 ],
       [3.64723539, 1.32567096, 0.0771877 ],
       [3.64723539, 1.32567096, 0.0771877 ],
       [3.64723539, 1.32567096, 0.0771877 ]])

# r_

Row oriented concatenation which is the same with vstack.
```np.r_[...]```
1. Take out elements of ```[...]``` (monad bind).
2. Evaluate each element. e.g. slice expression ```1:3``` into a slice object.
3. Concatenate all elements back into an array (monad unit).

## Syntax for Slice Concatenation

> If the index expression contains slice notation or scalars then create a 1-D array with a range indicated by the slice notation.

In [5]:
print(np.r_[
    1:6:2,   # Creates an array [1,3,5]
    2:7:2,   # Creates an array [2,4,6]
    3        # Creates an array [3]
])           # Concatenates [1,3,5], [2,4,6], and [3]

[1 3 5 2 4 6 3]


In [6]:
print(np.r_[
    "-1, 3", # Create a container array of rank 3, and concatenate the arrays along the lowest axis (-1)
    1:6:2,   # Creates an array [1,3,5]
    2:7:2,   # Creates an array [2,4,6]
    3        # Creates an array [3]
])           # Concatenates [1,3,5], [2,4,6], and [3] in the lowest axis space

[[[1 3 5 2 4 6 3]]]


## Syntax for Array Stacking

> If the index expression contains comma separated arrays, then stack them along their first axis.

In [7]:
print(np.r_[
    np.array([        # Rank 2 array of shape (2,3)
        [1,2,3], 
        [-1,-2,-3]
    ]), 
    np.array([        # Rank 2 array of shape (1,3)
        [4,5,6]
    ])
])                    # Stack rank 2 arrays into (3,3) along the highest dimension axis at rank 2

[[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]]


Same with vstack

In [8]:
print(np.vstack((     # Stack rank 2 arrays into rank 2 array by concatenating the contents of the 2 arrays
    np.array([        # Rank 2 array of shape (2,3)
        [1,2,3], 
        [-1,-2,-3]
    ]), 
    np.array([        # Rank 2 array of shape (1,3)
        [4,5,6]
    ])
)))                   # Rank 2 array of shape (3, 3)

[[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]]


In [9]:
print(np.r_[
    "0,2",            # Frame a container array of rank 2, and concatenate the arrays along the 0th axis (highest)
    np.array([        # Rank 2 array of shape (2,3)
        [1,2,3], 
        [-1,-2,-3]
    ]), 
    np.array([        # Rank 2 array of shape (1,3)
        [4,5,6]
    ])
])                    # Stack rank 2 arrays into (3,3) along the highest dimension axis at rank 2

[[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]]


In [10]:
print(np.r_[
    np.array([1,2,3]), 
    np.array([4,5,6])
])

# Same with above
print(np.r_[
    # Frame 1-dimensional container, and concatenate elements 
    # along the default axis (-1), which is 0 (first axis)
    '-1,1',
    # Elements
    np.array([1,2,3]), 
    np.array([4,5,6])
])

# Same with above. Specific with which axis.
print(np.r_[
    '0,1',              
    np.array([1,2,3]), 
    np.array([4,5,6])
])

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [11]:
E = np.array([
    
]).reshape(0, 5)
print("E: \n{}\nShape {}\n".format(E, E.shape))

A = np.vstack([
    [1, 2, 3, 4, 5], 
    [10, 20, 30, 40, 50]]
)
print("A:\n{}\nShape {}\n".format(A, A.shape))

fmt = """C = np.r_[
    E, 
    A
].astype(np.int32)"""

C = np.r_[
    E, 
    A
].astype(np.int32)

print(f"{fmt} is\n{C}\nwith shape {C.shape}\n")

E: 
[]
Shape (0, 5)

A:
[[ 1  2  3  4  5]
 [10 20 30 40 50]]
Shape (2, 5)

C = np.r_[
    E, 
    A
].astype(np.int32) is
[[ 1  2  3  4  5]
 [10 20 30 40 50]]
with shape (2, 5)



## Framing output shape with string integer argument
``` 
np.r_[
  "<axis, rank, shift>,
  arrays
]
```

Example:
```
np.r_[
    # 1st integer '0' specifies the axis along which to concatenate elements.
    # 2nd integer '3' specifies to frame the container of n=3 dimensions.
    # 
    # It is telling numpy that.
    # 1. Frame 3-dimensional output.
    # 2. Concatenate elements along the 0th axis
    # 3. Shift the original shape twice to the right.
    '0,5,2', 
    [1,2,3], 
    [4,5,6]
]
```

In [12]:
np.r_[
    # 1st integer '0' specifies the axis along which to concatenate elements.
    # 2nd integer '3' specifies to frame the container of n=3 dimensions.
    # 
    # It is telling numpy that.
    # 1. Frame 3-dimensional output.
    # 2. Concatenate elements along the 0th axis
    # 3. Shift the original shape twice to the right to fit in the 3 dimensional frame.
    '0,3,-1', 
    [1,2,3], 
    [4,5,6]
]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [13]:
X = np.arange(2*2).reshape((2,2))
print(f"X is \n{X}\n")
Y = np.r_['0,4,2',X]
print(Y.shape)
print(f"np.r_['0,3,0',X] is\n{Y}\n")

X is 
[[0 1]
 [2 3]]

(1, 1, 2, 2)
np.r_['0,3,0',X] is
[[[[0 1]
   [2 3]]]]



In [14]:
print(np.r_[
    # Frame 2-dimensional output, and concatenate elements along the 1st axis.
    '0,2', 
    [1,2,3], 
    [4,5,6]
])

print(np.r_[
    # Frame 2-dimensional output, and concatenate elements along the 2nd axis.
    # [ [1,2,3] [4,5,6] ] cannot be [ [1,2,3], [4,5,6]] as it is stacking along the 1st axis.
    # Hence [ [1,2,3] [4,5,6] ] -> [ [1,2,3, 4,5,6] ] 
    '1,2', 
    [1,2,3], 
    [4,5,6]
])

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


### Setting the shape expantion
Plus(+) is shifting the original shape from the highest dimension side to lower in the expanded shape. Minus(-) is shifting the original shape from the lowest dimension side to higher.

In [15]:
# Plus(+) is shifting the original shape from the highest dimension side to the lower in the expanded shape.
import numpy as np
print(np.r_['0,5,0',np.ones((2,3))].shape)  # 0 places the original shape to the highest dimension side.
print(np.r_['0,5,1',np.ones((2,3))].shape)  # shift 1 to the right from highest to lower dimension.
print(np.r_['0,5,2',np.ones((2,3))].shape)  # shift 2 to the right from highest to lower dimension.
print(np.r_['0,5,3',np.ones((2,3))].shape)  # shift 3 to the right from highest to lower dimension.
#print(np.r_['0,5,4',np.ones((2,3))].shape)  # Cannot shift shape (2, 3) further than 3 in 5 dimension shape.

(2, 3, 1, 1, 1)
(1, 2, 3, 1, 1)
(1, 1, 2, 3, 1)
(1, 1, 1, 2, 3)


In [16]:
# Minus(-) is shifting the original shape from the lowest dimension side to the higher in the expanded shape.
import numpy as np
print(np.r_['0,5,-1',np.ones((2,3))].shape)  # -1: places the original shape at the lowest dimension side.
print(np.r_['0,5,-2',np.ones((2,3))].shape)  # shift 1 to the left from lowest to higher dimension.
print(np.r_['0,5,-3',np.ones((2,3))].shape)  # shift 2 to the left from lowest to higher dimension.
print(np.r_['0,5,-4',np.ones((2,3))].shape)  # shift 3 to the left from lowest to higher dimension.
#print(np.r_['0,5,-5',np.ones((2,3))].shape)  # Cannot shift shape (2, 3) further than 3 in 5 dimension shape.

(1, 1, 1, 2, 3)
(1, 1, 2, 3, 1)
(1, 2, 3, 1, 1)
(2, 3, 1, 1, 1)


In [17]:
print("--------------------------------------------------------------------------------")
print("Default implicit shape expantion, placing the original shape at the lowest dimension side.")
print(np.r_[
    # Frame a 2-dimensional output, and concatenate along the 1st axis (highest dimension).
    # Default shape expantion, which is -1, is placing the original shape at the lowest dimension side.
    '0,2', 
    [1,2,3],  # shape (3,)
    [4,5,6]   # shape (3,)
])

print("--------------------------------------------------------------------------------")
print("Simulating the default shape expantion -1 with np.newaxis.")
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.r_[
    # Frame a 2-dimensional output and concatenate the expanded elements along the 1st axis in the output.
    '0,2', 
    # Simulating the default shape expantion from (3,) to (1,3) using np.newaxis.
    a[
        np.newaxis,
        ::
    ],
    b[
        np.newaxis,
        ::
    ]
])

print("--------------------------------------------------------------------------------")
print("Default shape expantion with explicit default -1, placing the original shape at the lowest dimension side")
print(np.r_[
    # Frame a 2-dimensional output, and concatenate along the 1st axis in the output.
    # Expand the element shape using the default expansion (-1).
    '0,2,-1', 
    # Elements to be expanded from (3,) -> (1,3).
    [1,2,3],  
    [4,5,6]
])

print("--------------------------------------------------------------------------------")
print("Shape expantion with explicit -2, shifting the original shape 1 step to the left")
print(np.r_[
    # Frame a 2-dimensional output, and concatenate along the 1st axis in the output.
    # Expand the element shape by adding shape location 1 from (3,) to (1,3).
    '0,2,-2', 
    # Elements to be expanded from (3,) -> (1,3).
    [1,2,3],  
    [4,5,6]
])

print("--------------------------------------------------------------------------------")
print("Shape expantion with explicit 0, placing the original shape at the highest dimension side.")
print("0 is the lowest dimension, hence (3,) -> (3, 1)")
print(np.r_[
    # Frame a 2-dimensional output, and concatenate expanded elements along the first axis 0.
    # Expand the element shape from (3,) to (3,1) by placing the original shape at the highest dimension side.
    '0,2,0', 
    [1,2,3], 
    [4,5,6]
])

print("--------------------------------------------------------------------------------")
print("Simulating the shape expantion with 0 with np.newaxis.")
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.r_[
    # Frame a 2-dimensional output and concatenate the expanded elements along the 1st axis in the output.
    '0,2', 
    # Simulating the shape expantion with 0, from (3,) to (3, 1), using np.newaxis.
    a[
        ::,
        np.newaxis
    ],
    b[
        ::,
        np.newaxis
    ]
])


--------------------------------------------------------------------------------
Default implicit shape expantion, placing the original shape at the lowest dimension side.
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
Simulating the default shape expantion -1 with np.newaxis.
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
Default shape expantion with explicit default -1, placing the original shape at the lowest dimension side
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
Shape expantion with explicit -2, shifting the original shape 1 step to the left
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
--------------------------------------------------------------------------------
Shape expantion with explicit 0, placing the original shape at the highest dimension side.
0 is the lowest dimension, hence (3,) -> (3, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### Shifting in action

See how the original shape (2,3) is being shifted from the -1 or 0 case.

In [18]:
import numpy as np
print(np.ones((2, 3)))
np.r_['0,3',np.ones((2,3))].shape

print("r_[0,3,0] on (2, 3) is {}\n".format(
    np.r_[
        '0,3,0',
        np.ones((2,3))
    ].shape
))

print("r_[0,3,1] on (2, 3) is {}\n".format(
    np.r_[
        '0,3,1',
        np.ones((2,3))
    ].shape
))

"""print("r_[0,3,2] on (2, 3) is {}\n".format(
    np.r_[
        '0,3,2',
        np.ones((2,3))
    ].shape
))
"""
print("r_[0,4,0] on (2, 3) is {}\n".format(
    np.r_[
        '0,4,0',
        np.ones((2,3))
    ].shape
))

print("r_[0,4,1] on (2, 3) is {}\n".format(
    np.r_[
        '0,4,1',
        np.ones((2,3))
    ].shape
))

print("r_[0,4,2] on (2, 3) is {}\n".format(
    np.r_[
        '0,4,2',
        np.ones((2,3))
    ].shape
))

"""
print("r_[0,4,3] on (2, 3) is {}\n".format(
    np.r_[
        '0,4,3',
        np.ones((2,3))
    ].shape
))
---
ValueError: axes don't match array
"""

[[1. 1. 1.]
 [1. 1. 1.]]
r_[0,3,0] on (2, 3) is (2, 3, 1)

r_[0,3,1] on (2, 3) is (1, 2, 3)

r_[0,4,0] on (2, 3) is (2, 3, 1, 1)

r_[0,4,1] on (2, 3) is (1, 2, 3, 1)

r_[0,4,2] on (2, 3) is (1, 1, 2, 3)



'\nprint("r_[0,4,3] on (2, 3) is {}\n".format(\n    np.r_[\n        \'0,4,3\',\n        np.ones((2,3))\n    ].shape\n))\n---\nValueError: axes don\'t match array\n'

# numpy.concatenate((tuple), axis)

1. Take out elements in the tuple.
2. Concatenate **all the elements** back into an array.

Concatenate a 1D list elements into an empty array.

In [19]:
labels = np.array([]).reshape(0,)
print(labels.shape)

print(np.concatenate(
    (labels, [0, 1, 2])
))

(0,)
[0. 1. 2.]


Concatenate elements of 2D list of shape(1, 2) into an empty 2D array of shape(0,2).

In [20]:
initial =np.array([]).reshape((0, 2))
print(np.concatenate(
    (initial, [[1,2], [3,4]])
))


[[1. 2.]
 [3. 4.]]


Concatenate arrays (N1, M), (N2,M), (N3, M) into (N1+N2+N3, M)

In [22]:
a = np.array([
    [-0.68595   , -0.59704907],
    [-0.70704997, -0.30369686]])
b = np.array([
    [ 0.51405   , -0.59704907],
    [ 1.51991102, -0.48112732],
    [ 0.49295003, -0.30369686]])
c = np.array([
    [ 0.91991102,  0.55810317],
    [-0.10704997,  0.73553363]])

d = [a, b, c]
np.concatenate(d)

array([[-0.68595   , -0.59704907],
       [-0.70704997, -0.30369686],
       [ 0.51405   , -0.59704907],
       [ 1.51991102, -0.48112732],
       [ 0.49295003, -0.30369686],
       [ 0.91991102,  0.55810317],
       [-0.10704997,  0.73553363]])

In [23]:
# same with vstack
np.vstack(d)

array([[-0.68595   , -0.59704907],
       [-0.70704997, -0.30369686],
       [ 0.51405   , -0.59704907],
       [ 1.51991102, -0.48112732],
       [ 0.49295003, -0.30369686],
       [ 0.91991102,  0.55810317],
       [-0.10704997,  0.73553363]])

### Difference from [numpy.append(arr, values, axis=None)](https://numpy.org/doc/stable/reference/generated/numpy.append.html)

> If axis is not specified, values can be any shape and will be flattened before use.

np.append() with axis flattens values ```[[1, 2], [3, 4]].

```
np.append(
    [], 
    [
        [1,2]
        [3,4]
    ]
))
```

In [35]:
a = np.arange(12).reshape(3, 4)
print(a)
np.c_[
    a[::, 0:1],
    a[::, 1:2]
]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[0, 1],
       [4, 5],
       [8, 9]])

In [27]:
a = np.arange(6).reshape(2, 3)
print(a)
b = np.arange(6, 12).reshape(2, 3)
print(b)
np.c_[a, b]

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])