# One Hot Encoding (OHE) as Row Selector
OHE vector is a row of Identity Matrx (IM). Each row in IM selects a row in the targetat the 1 position.
```
[
 [ 0  1  2  3  4  5]   # <--- [1, 0, 0, 0] leaves this row by masking rows at 6, 12, 18 with its Zero/0.
 [ 6  7  8  9 10 11]   # <--- [0, 1, 0, 0]
 [12 13 14 15 16 17]   # <--- [0, 0, 1, 0]
 [18 19 20 21 22 23]   # <--- [0, 0, 0, 1]
]
```

In [1]:
import numpy as np

In [31]:
y = np.arange(24).reshape(4, 6)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
first  = np.array([1, 0, 0, 0])
second = np.array([0, 1, 0, 0])
third  = np.array([0, 0, 1, 0])
forth  = np.array([0, 0, 0, 1])

In [38]:
print("""Dot product of first {} and y \n{}\nselects the first row {}\n""".format(
    first, y, first@y
))

Dot product of first [1 0 0 0] and y 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
selects the first row [0 1 2 3 4 5]



In [39]:
print("""Dot product of second {} and y \n{}\nselects the second row {}\n""".format(
    first, y, second@y
))

Dot product of second [1 0 0 0] and y 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
selects the second row [ 6  7  8  9 10 11]



In [20]:
print("""Dot product of thrid {} and y \n{}\nselects the thrid row {}\n""".format(
    first, y, thrid@y
))

array([ 2,  6, 10, 14, 18])

In [40]:
print("""Dot product of forth {} and y \n{}\nselects the forth row {}\n""".format(
    first, y, forth@y
))

Dot product of forth [1 0 0 0] and y 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
selects the forth row [18 19 20 21 22 23]



# Identity matrix (eye) does the same

In [41]:
eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.dot(eye, y)

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])