In [1]:
import numpy as np

In [49]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(linewidth=1000) 

In [16]:
a = np.zeros(5 * 3).reshape(3, 5)
b = a
print(a)
print (np.may_share_memory(a, b))
a[
    1:4:3,
    (1,2)
] = 1
#c = 1
print (np.may_share_memory(a, b))
print(a)
print(b)
a[1:4:3, (1,2)] = np.dot(a[1:4:3, (1,2)], 0)
print(a)
print (np.may_share_memory(a, b))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
True
True
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
True


In [36]:

X = np.random.randn(10, 8)
X[
    ::,
    0
] = 0

out = np.copy(X)
Y = out

N = X.shape[0]
mean = np.sum(X, axis=0) / N    # mean of each feature
deviation = X - mean
variance = np.var(X, axis=0)
sd = np.sqrt(variance)

mask = (sd == 0.0)
print(mask)
if np.any(mask):
    # Temporary replace the zero elements with one
    sd[mask] = 1.0

    # reuse deviation memory area
    out = deviation if out is None else out

    # standardize and zero clear the mask elements
    standardized = np.divide(deviation, sd, out)
    out[::, mask] = 0.0

    # restore sd
    sd[mask] = 0.0

else:
    standardized = np.divide(deviation, sd, out)

assert np.all(np.isfinite(standardized))
print (np.may_share_memory(a, b))



[ True False False False False False False False]
True


array([[ 0.        ,  0.63401531, -0.02272114, -1.32074605, -0.37547971,  1.24397671,  0.04377315, -0.85318264],
       [ 0.        ,  1.39898499, -0.94798154, -0.46228464, -0.74397546, -0.1951366 ,  0.13388639,  1.36570077],
       [ 0.        , -0.21252002, -0.05020735,  0.1509649 ,  0.49312099, -0.22747285,  0.11895831, -0.11739548],
       [ 0.        ,  1.25931439, -1.06279398, -0.4665774 ,  1.92634438,  1.2646767 ,  1.18250327, -0.57750535],
       [ 0.        , -0.60484621,  0.49956358,  0.36734102, -1.61717771, -1.79568549, -0.44486284, -1.28799455],
       [ 0.        ,  1.27204747, -0.86128076,  1.50000584,  1.19194821,  0.37859158, -1.44311422,  1.61931129],
       [ 0.        , -0.43778543,  1.15454473,  1.10723193, -0.40478027,  0.81581754, -1.79623246,  0.01655473],
       [ 0.        , -0.7530228 ,  2.26612817, -1.03240685, -0.47595658, -1.55076569,  1.09041356,  0.01640809],
       [ 0.        , -1.26981086, -0.6170983 ,  1.32571566, -0.67714719, -0.36878714, -0.2333929

# Variance, SD Delta of degree of freedom

You need to make sure ```ddof=(N-1) > 0``` at ```Variance / (N-1)```.

In [37]:
np.std([1], ddof=1)

/home/oonisim/conda/envs/python_programs/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/oonisim/conda/envs/python_programs/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

# Numpy delete rows/cols

* [numpy.delete(arr, obj, axis=None)](https://numpy.org/doc/stable/reference/generated/numpy.delete.html)

In [57]:
num_nodes = 5
D = 5
W = np.random.rand(num_nodes, D)
W = np.c_[
    np.random.uniform(-1, 1, num_nodes),
    W
]
print(f"W.shape is {W.shape} W is \n{W}")

# Delete the 1st column
U = np.delete(W, 0, axis=1)
print (np.may_share_memory(W, U))

W.shape is (5, 6) W is 
[[ 4.47144043e-01  4.10824414e-04  1.23359180e-01  2.61962430e-01  7.28072006e-01  4.44182229e-01]
 [ 8.20683622e-01  8.99123077e-01  8.08961053e-01  3.52575863e-03  7.15409112e-01  7.22465258e-01]
 [-7.67978359e-01  9.00059616e-01  9.53641698e-01  8.06065772e-01  3.59177527e-01  8.10210224e-01]
 [ 9.88973379e-01  2.12178987e-01  3.77103943e-01  5.90208309e-01  5.88364600e-01  5.27245324e-01]
 [-3.46212320e-01  7.83591574e-01  7.62654726e-01  1.02234534e-02  9.70708024e-01  5.06796799e-01]]
False


In [63]:
num_nodes = 5
D = 5
W = np.random.rand(num_nodes, D)
print(f"W.shape is {W.shape} W is \n{W}")
U = W[
    ::,
    1::
]
# Delete the 1st column
print (np.may_share_memory(W, U))
print(U)

W.shape is (5, 5) W is 
[[0.11452948 0.60490927 0.6678025  0.28565915 0.19597239]
 [0.77427786 0.42063954 0.28470153 0.01509157 0.13727146]
 [0.29918505 0.21396133 0.7573232  0.43228129 0.40236131]
 [0.31987676 0.61457229 0.70164045 0.45291392 0.33502056]
 [0.15627297 0.17576852 0.25672442 0.92263637 0.26751086]]
True
[[0.60490927 0.6678025  0.28565915 0.19597239]
 [0.42063954 0.28470153 0.01509157 0.13727146]
 [0.21396133 0.7573232  0.43228129 0.40236131]
 [0.61457229 0.70164045 0.45291392 0.33502056]
 [0.17576852 0.25672442 0.92263637 0.26751086]]
