In [1]:
import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Indexing patterns

In [149]:
import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)

# Slice indexing
print(a[
    0:2,
    1:3
])

# Tuple indexing
print(a[
    (0, 2),
    (1, 3)
])

# Array indexing
print(a[
    [0, 2],
    [1, 3]
])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [5 6]]
[ 1 11]
[ 1 11]


### Indexing pattern and copy/view

In [92]:
import numpy as np
a = np.arange(24).reshape(2, 3, 4)
print(a)

b = a[
    (0),
    (0, 2),
    (1)
]
print(b)
print("Copy? {}".format(b.base is None))


indices = (
    [0],
    [0, 2],
    [1]
)
c = a[indices]
print(c)
print("Copy? {}".format(c.base is None))

d = a[
    0,
    0,
    0:1
]
print(d)
print("Copy? {}".format(d.base is None))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[1 9]
Copy? True
[1 9]
Copy? True
[0]
Copy? False


# Tuple indexing

In [49]:
print(a[
    (0, 2),
    (1, 3)
])

[ 1 11]


In [34]:
index = (
    (0, 
     2), (1, 
          3)
)
a[index]

array([ 1, 11])

In [36]:
index = (
    (0, 2), 
    (1, 3)
)
print(a[index])
print(a[
    (0, 2),
    (1, 3)
])

[ 1 11]
[ 1 11]


### Using array in tuple indexing is deprecated

In [50]:
index = [
    (0, 2), 
    (1, 3)
]
print(a[index])

[ 1 11]


<ipython-input-50-2fdfff8b4d68>:5: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(a[index])


In [2]:
import numpy as np
Z = np.arange(36).reshape(3, 3, 4)
print("Array Z is \n{}\n".format(Z))

print("Array indices Z[[0,2]] is \n{}\n Is view? {}\n".format(
    Z[
        [0,2]      # Select element 0, and 2 in dimension(n)
    ],
    Z[[0,2]].base is not None
))

print("Tuple indices Z[(0,2)] is \n{}\n Is view? {}\n".format(
    Z[
        (0,2)      # Select Z[0][2]
    ],
    Z[(0,2)].base is not None
))

print("Basic indices Z[0,2] is \n{}\n Is view? {}\n".format(
    Z[
        0,
        2      # Select Z[0][2]
    ],
    Z[0,2].base is not None
))

print("Z[(0,2)] is same with Z[0][2] {}. \nZ[0][2] is view? {}".format(
    Z[0][2],
    (Z[0][2]).base is not None
))


print("Slice indices Z[0:1,2:3] is \n{}\n Is view? {}\n".format(
    Z[
        0:1,
        2:3      # Select Z[0][2]
    ],
    Z[0:1, 2:3].base is not None
))



Array Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

Array indices Z[[0,2]] is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
 Is view? False

Tuple indices Z[(0,2)] is 
[ 8  9 10 11]
 Is view? True

Basic indices Z[0,2] is 
[ 8  9 10 11]
 Is view? True

Slice indices Z[0:1,2:3] is 
[[[ 8  9 10 11]]]
 Is view? True

Z[(0,2)] is same with Z[0][2] [ 8  9 10 11]. 
Z[0][2] is view? True


In [126]:
import numpy as np
Z = np.arange(36).reshape(3, 3, 4)
print("Z is \n{}\n".format(Z))

b =  Z[
    (0,2)      # Select Z[0][2]
]
print("Tuple indexing Z[(0,2)] is \n{}\nIs view? {}\n".format(
    b,
    b.base is not None
))

c = Z[         # Select Z[0][0][1] & Z[0][2][1]
    (0,2),
    (0)
]
print("Tuple indexing Z[(0, 2), (0)] is \n{}\nIs view? {}\n".format(
    c,
    c.base is not None
))

Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

Tuple indexing Z[(0,2)] is 
[ 8  9 10 11]
Is view? True

Tuple indexing Z[(0, 2), (0)] is 
[[ 0  1  2  3]
 [24 25 26 27]]
Is view? False



# Slice indexing

In [140]:
Z = np.arange(24).reshape(2, 3, 4)
print("Z is \n{}\n".format(Z))
a = Z[
    0:1,
    0:2,
    1:3
]
print("Slice indexing Z[0:1, 0:1, 1:3] is \n{}\nIs view? {}\n".format(
    a,
    a.base is not None
))

Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Slice indexing Z[0:1, 0:1, 1:3] is 
[[[1 2]
  [5 6]]]
Is view? True



# Array indexing

In [148]:
Z = np.arange(36).reshape(3, 3, 4)
print("Z is \n{}\n".format(Z))
a = Z[
    [0],
    [1],
    [0,1,2]
]

print("Array indexing Z[[0],[1],[0,1,2]] is \n{}\nIs view? {}\n".format(
    a,
    a.base is not None
))

Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

Array indexing Z[[0],[1],[0,1,2]] is 
[4 5 6]
Is view? False



In [171]:
Z = np.arange(36).reshape(3, 3, 4)
print("Z is \n{}\n".format(Z))

indices= np.array([[0, 2], [1, 2]])
print("indices is \n{}\n".format(indices))

b = Z[indices]
print("Z[np.array([[0, 2], [1, 2]])] is \n{} Is view? {}\n".format(
    b,
    b.base is not None
))


i = [[0, 2], [1, 2]]
c = Z[i] 
print("Z[i] with i = [[0, 2], [1, 2]] is \n{} Is view? {}\n".format(
    c,
    c.base is not None
))

d = Z[
    np.array([0, 2]), np.array([1, 2])
]
print("Z[np.array([0, 2]), np.array([1, 2])] is \n{} Is view? {}\n".format(
    d,
    d.base is not None
))


Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

indices is 
[[0 2]
 [1 2]]

Z[np.array([[0, 2], [1, 2]])] is 
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]]


 [[[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]

  [[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]]] Is view? False

Z[i] with i = [[0, 2], [1, 2]] is 
[[ 4  5  6  7]
 [32 33 34 35]] Is view? False

Z[np.array([0, 2]), np.array([1, 2])] is 
[[ 4  5  6  7]
 [32 33 34 35]] Is view? False



<ipython-input-171-730f8014a9ec>:15: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  c = Z[i]


In [180]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)

print("x[rows, columns] \n{}\n".format(x[rows, columns]))

indices = np.array([rows, columns])
print("indices is \n{}\n".format(indices))
print(x[indices])

x[rows, columns] 
[[ 0  2]
 [ 9 11]]

indices is 
[[[0 0]
  [3 3]]

 [[0 2]
  [0 2]]]

[[[[ 0  1  2]
   [ 0  1  2]]

  [[ 9 10 11]
   [ 9 10 11]]]


 [[[ 0  1  2]
   [ 6  7  8]]

  [[ 0  1  2]
   [ 6  7  8]]]]
