In [1]:
import numpy as np

# vstack

In [7]:
a = np.vstack([
    np.array([]).reshape(0, 5),
    np.array([1,2,3,4,5]), 
    np.array([10, 20, 30, 40, 50])]
).astype(np.int32)
print(a.shape)
print(a)

(2, 5)
[[ 1  2  3  4  5]
 [10 20 30 40 50]]


# r_

In [23]:
print(np.r_[
    np.array([1,2,3]), 
    np.array([4,5,6])
])

# Same with above
print(np.r_[
    # Frame 1-dimensional container, and concatenate elements 
    # along the default axis (-1), which is 0 (first axis)
    '-1,1',
    # Elements
    np.array([1,2,3]), 
    np.array([4,5,6])
])

# Same with above. Specific with which axis.
print(np.r_[
    '0,1',              
    np.array([1,2,3]), 
    np.array([4,5,6])
])

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [17]:
E = np.array([
    
]).reshape(0, 5)
print("E: \n{}\nShape {}\n".format(E, E.shape))

A = np.vstack([
    [1, 2, 3, 4, 5], 
    [10, 20, 30, 40, 50]]
)
print("A:\n{}\nShape {}\n".format(A, A.shape))

C = np.r_[
    E, 
    A
].astype(np.int32)

print("C:\n{}\nShape {}\n".format(C, C.shape))

E: 
[]
Shape (0, 5)

A:
[[ 1  2  3  4  5]
 [10 20 30 40 50]]
Shape (2, 5)

C:
[[ 1  2  3  4  5]
 [10 20 30 40 50]]
Shape (2, 5)



## Framing output shape with string integer argument

In [25]:
print(np.r_[
    # Frame 2-dimensional output, and concatenate elements along the 1st axis.
    '0,2', 
    [1,2,3], 
    [4,5,6]
])

print(np.r_[
    # Frame 2-dimensional output, and concatenate elements along the 2nd axis.
    # [ [1,2,3] [4,5,6] ] cannot be [ [1,2,3], [4,5,6]] as it is stacking along the 1st axis.
    # Hence [ [1,2,3] [4,5,6] ] -> [ [1,2,3, 4,5,6] ] 
    '1,2', 
    [1,2,3], 
    [4,5,6]
])

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


### Setting the shape expantion
Plus(+) is shifting the original shape from the highest dimension side to lower in the expanded shape. Minus(-) is shifting the original shape from the lowest dimension side to higher.

In [7]:
# Plus(+) is shifting the original shape from the highest dimension side to the lower in the expanded shape.
import numpy as np
print(np.r_['0,5,0',np.ones((2,3))].shape)  # 0 places the original shape to the highest dimension side.
print(np.r_['0,5,1',np.ones((2,3))].shape)  # shift 1 to the right from highest to lower dimension.
print(np.r_['0,5,2',np.ones((2,3))].shape)  # shift 2 to the right from highest to lower dimension.
print(np.r_['0,5,3',np.ones((2,3))].shape)  # shift 3 to the right from highest to lower dimension.
print(np.r_['0,5,4',np.ones((2,3))].shape)  # Cannot shift shape (2, 3) further than 3 in 5 dimension shape.

(2, 3, 1, 1, 1)
(1, 2, 3, 1, 1)
(1, 1, 2, 3, 1)
(1, 1, 1, 2, 3)


ValueError: axes don't match array

In [9]:
# Minus(-) is shifting the original shape from the lowest dimension side to the higher in the expanded shape.
import numpy as np
print(np.r_['0,5,-1',np.ones((2,3))].shape)  # -1 places the original shape at the lowest dimension side.
print(np.r_['0,5,-2',np.ones((2,3))].shape)  # shift 1 to the left from lowest to higher dimension.
print(np.r_['0,5,-3',np.ones((2,3))].shape)  # shift 2 to the left from lowest to higher dimension.
print(np.r_['0,5,-4',np.ones((2,3))].shape)  # shift 3 to the left from lowest to higher dimension.
print(np.r_['0,5,-5',np.ones((2,3))].shape)  # Cannot shift shape (2, 3) further than 3 in 5 dimension shape.

(1, 1, 1, 2, 3)
(1, 1, 2, 3, 1)
(1, 2, 3, 1, 1)
(2, 3, 1, 1, 1)


ValueError: axes don't match array

In [10]:
print("--------------------------------------------------------------------------------")
print("Default implicit shape expantion, placing the original shape at the lowest dimension side.")
print(np.r_[
    # Frame a 2-dimensional output, and concatenate along the 1st axis (highest dimension).
    # Default shape expantion, which is -1, is placing the original shape at the lowest dimension side.
    '0,2', 
    [1,2,3],  # shape (3,)
    [4,5,6]   # shape (3,)
])

print("--------------------------------------------------------------------------------")
print("Simulating the default shape expantion -1 with np.newaxis.")
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.r_[
    # Frame a 2-dimensional output and concatenate the expanded elements along the 1st axis in the output.
    '0,2', 
    # Simulating the default shape expantion from (3,) to (1,3) using np.newaxis.
    a[
        np.newaxis,
        ::
    ],
    b[
        np.newaxis,
        ::
    ]
])

print("--------------------------------------------------------------------------------")
print("Default shape expantion with explicit default -1, placing the original shape at the lowest dimension side")
print(np.r_[
    # Frame a 2-dimensional output, and concatenate along the 1st axis in the output.
    # Expand the element shape using the default expansion (-1).
    '0,2,-1', 
    # Elements to be expanded from (3,) -> (1,3).
    [1,2,3],  
    [4,5,6]
])

print("--------------------------------------------------------------------------------")
print("Shape expantion with explicit -2, shifting the original shape 1 step to the left")
print(np.r_[
    # Frame a 2-dimensional output, and concatenate along the 1st axis in the output.
    # Expand the element shape by adding shape location 1 from (3,) to (1,3).
    '0,2,-2', 
    # Elements to be expanded from (3,) -> (1,3).
    [1,2,3],  
    [4,5,6]
])

print("--------------------------------------------------------------------------------")
print("Shape expantion with explicit 0, placing the original shape at the highest dimension side.")
print("0 is the lowest dimension, hence (3,) -> (3, 1)")
print(np.r_[
    # Frame a 2-dimensional output, and concatenate expanded elements along the first axis 0.
    # Expand the element shape from (3,) to (3,1) by placing the original shape at the highest dimension side.
    '0,2,0', 
    [1,2,3], 
    [4,5,6]
])

print("--------------------------------------------------------------------------------")
print("Simulating the shape expantion with 0 with np.newaxis.")
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.r_[
    # Frame a 2-dimensional output and concatenate the expanded elements along the 1st axis in the output.
    '0,2', 
    # Simulating the shape expantion with 0, from (3,) to (3, 1), using np.newaxis.
    a[
        ::,
        np.newaxis
    ],
    b[
        ::,
        np.newaxis
    ]
])


--------------------------------------------------------------------------------
Default implicit shape expantion, placing the original shape at the lowest dimension side.
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
Simulating the default shape expantion -1 with np.newaxis.
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
Default shape expantion with explicit default -1, placing the original shape at the lowest dimension side
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
Shape expantion with explicit -2, shifting the original shape 1 step to the left
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
--------------------------------------------------------------------------------
Shape expantion with explicit 0, placing the original shape at the highest dimension side.
0 is the lowest dimension, hence (3,) -> (3, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### Shifting in action

See how the original shape (2,3) is being shifted from the -1 or 0 case.

In [31]:
import numpy as np
print(np.ones((2, 3)))
np.r_['0,3',np.ones((2,3))].shape

print("r_[0,3,0] on (2, 3) is {}\n".format(
    np.r_[
        '0,3,0',
        np.ones((2,3))
    ].shape
))

print("r_[0,3,1] on (2, 3) is {}\n".format(
    np.r_[
        '0,3,1',
        np.ones((2,3))
    ].shape
))

"""print("r_[0,3,2] on (2, 3) is {}\n".format(
    np.r_[
        '0,3,2',
        np.ones((2,3))
    ].shape
))
"""
print("r_[0,4,0] on (2, 3) is {}\n".format(
    np.r_[
        '0,4,0',
        np.ones((2,3))
    ].shape
))

print("r_[0,4,1] on (2, 3) is {}\n".format(
    np.r_[
        '0,4,1',
        np.ones((2,3))
    ].shape
))

print("r_[0,4,2] on (2, 3) is {}\n".format(
    np.r_[
        '0,4,2',
        np.ones((2,3))
    ].shape
))

print("r_[0,4,3] on (2, 3) is {}\n".format(
    np.r_[
        '0,4,3',
        np.ones((2,3))
    ].shape
))

[[1. 1. 1.]
 [1. 1. 1.]]
r_[0,3,0] on (2, 3) is (2, 3, 1)

r_[0,3,1] on (2, 3) is (1, 2, 3)

r_[0,4,0] on (2, 3) is (2, 3, 1, 1)

r_[0,4,1] on (2, 3) is (1, 2, 3, 1)

r_[0,4,2] on (2, 3) is (1, 1, 2, 3)



ValueError: axes don't match array