In [4]:
import numpy as np

In [8]:
a = np.arange(0, 4)
b = np.arange(4, 8)

c = np.concatenate([a, b])
print(c)

# Split into 2-equal arrays
print(np.split(c, 2))

# Split after the each index specified as iterable.
print(np.split(c, [3, 6]))  # like 0:3, 3:6

[0 1 2 3 4 5 6 7]
[array([0, 1, 2, 3]), array([4, 5, 6, 7])]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]


In [24]:
a = np.arange(60).reshape((4, 3, 5))
print(a)
print()

# Spit along the 1st axis as 0:2, 2:
print(np.split(a, [2], axis=0))

# Spit along the 3rd axis as :2, 2:4, 4:
print(np.split(a, [2, 4], axis=2))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]

 [[45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

[array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]]), array([[[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])]
[array([[[ 0,  1],
        [ 5,  6],
        [10, 11]],

       [[15, 16],
        [20, 21],
        [25, 26]],

       [[30, 31],
        [35, 36],
        [40, 41]],

       [[45, 46],
        [50, 51],
        [55, 56]]]), array([[[ 2,  3],
        [ 7,  8],
        [12, 13]],

       [[17, 18],
        [22, 23],
        [27, 28]],

       [[32, 33],
        [37, 38],
        [42, 43]],

True