In [1]:
import numpy as np

# In-place operation
Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

# Accumulative updates

Default bufferd operation only increments each element only once.

In [2]:
a = np.arange(12).reshape((3, 4))
b = a.copy()
print(a)

a[1, [0, 2, 0, 2, 0]] += 1
print(a-b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [1 0 1 0]
 [0 0 0 0]]


<img src='images/numpy_accumulative_update.png' width=750 align='left'/>

## [numpy.ufunc.at(a, indices, b=None)](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.at.html)

Operation on operand ‘a’ for **each elements specified by ‘indices’**. Results are accumulated for elements that are indexed more than once because **unbuffered**. 

```[[0,0]] += 1``` will only increment the first element once because of buffering, whereas ```add.at(a, [0,0], 1)``` will increment the first element twice.

### [Universal functions (ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html)
> A universal function (or ufunc for short) is a function that **operates on ndarrays in an element-by-element** fashion, supporting array broadcasting, type casting, and several other standard features. That is, a ufunc is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.



In [4]:
a = np.arange(12).reshape((3, 4))
b = a.copy()
print(a)

np.add.at(a, (1, [0, 2, 0, 2, 0]), 1)
print(a - b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [3 0 2 0]
 [0 0 0 0]]
