# Shuffle array

In [1]:
import numpy as np

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
np.random.choice(a=a, size=len(a), replace=False)

array([ 2,  1,  0,  8, 10, 11,  6,  5,  7,  9,  3,  4])

## multi dimensional

In [4]:
a = a.reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
indices = np.random.choice(a=range(a.size), size=a.size, replace=False)
indices

array([ 0, 10, 11,  5,  2,  7,  9,  1,  8,  4,  3,  6])

In [20]:
a.ravel()[indices].reshape(a.shape)

array([[ 0, 10, 11,  5],
       [ 2,  7,  9,  1],
       [ 8,  4,  3,  6]])