In [1]:
import numpy as np

# vstack

In [7]:
a = np.vstack([
    np.array([]).reshape(0, 5),
    np.array([1,2,3,4,5]), 
    np.array([10, 20, 30, 40, 50])]
).astype(np.int32)
print(a.shape)
print(a)

(2, 5)
[[ 1  2  3  4  5]
 [10 20 30 40 50]]


# r_

In [23]:
print(np.r_[
    np.array([1,2,3]), 
    np.array([4,5,6])
])

# Same with above
print(np.r_[
    # Frame 1-dimensional container, and concatenate elements 
    # along the default axis (-1), which is 0 (first axis)
    '-1,1',
    # Elements
    np.array([1,2,3]), 
    np.array([4,5,6])
])

# Same with above. Specific with which axis.
print(np.r_[
    '0,1',              
    np.array([1,2,3]), 
    np.array([4,5,6])
])

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [17]:
E = np.array([
    
]).reshape(0, 5)
print("E: \n{}\nShape {}\n".format(E, E.shape))

A = np.vstack([
    [1, 2, 3, 4, 5], 
    [10, 20, 30, 40, 50]]
)
print("A:\n{}\nShape {}\n".format(A, A.shape))

C = np.r_[
    E, 
    A
].astype(np.int32)

print("C:\n{}\nShape {}\n".format(C, C.shape))

E: 
[]
Shape (0, 5)

A:
[[ 1  2  3  4  5]
 [10 20 30 40 50]]
Shape (2, 5)

C:
[[ 1  2  3  4  5]
 [10 20 30 40 50]]
Shape (2, 5)



## Framing output shape with string integer argument

In [25]:
print(np.r_[
    # Frame 2-dimensional output, and concatenate elements along the 1st axis.
    '0,2', 
    [1,2,3], 
    [4,5,6]
])

print(np.r_[
    # Frame 2-dimensional output, and concatenate elements along the 2nd axis.
    # [ [1,2,3] [4,5,6] ] cannot be [ [1,2,3], [4,5,6]] as it is stacking along the 1st axis.
    # Hence [ [1,2,3] [4,5,6] ] -> [ [1,2,3, 4,5,6] ] 
    '1,2', 
    [1,2,3], 
    [4,5,6]
])

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


### Setting the shape expantion

In [47]:
print("--------------------------------------------------------------------------------")
print("Default implicit shape expantion, adding higher dimension(s) to the shape.")
print(np.r_[
    # Frameing a 2-dimensional output, and concatenate along the 1st axis (highest dimension).
    # Default shape expantion, which is -1, is adding higher dimension(s), eg (3,) -> (1, 3).
    '0,2', 
    [1,2,3],  # shape (3,)
    [4,5,6]   # shape (3,)
])

print("--------------------------------------------------------------------------------")
print("Simulating the default shape expantion -1 with np.newaxis.")
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.r_[
    # Frame a 2-dimensional output and concatenate the expanded elements along the 1st axis in the output.
    '0,2', 
    # Simulating the default shape expantion from (3,) to (1,3) using np.newaxis.
    a[
        np.newaxis,
        ::
    ],
    b[
        np.newaxis,
        ::
    ]
])

print("--------------------------------------------------------------------------------")
print("Default shape expantion with explicit default -1, adding higher dimension(s) to the shape.")
print(np.r_[
    # Frame a 2-dimensional output, and concatenate along the 1st axis in the output.
    # Expand the element shape using the default expansion (-1).
    '0,2,-1', 
    # Elements to be expanded from (3,) -> (1,3).
    [1,2,3],  
    [4,5,6]
])

print("--------------------------------------------------------------------------------")
print("Shape expantion with explicit 1, from (3,) into (1,3).")
print("When expanding the shape (3,) into (1,3), default -1 is the same with 1.")
print("For a shape (k, j, i), 2 is the location integer for 'k', 1 for 'j', 0 for 'i'")  
print(np.r_[
    # Frame a 2-dimensional output, and concatenate along the 1st axis in the output.
    # Expand the element shape by adding shape location 1 from (3,) to (1,3).
    '0,2,1', 
    # Elements to be expanded from (3,) -> (1,3).
    [1,2,3],  
    [4,5,6]
])

print("--------------------------------------------------------------------------------")
print("Shape expantion with explicit 0, adding the lowest dimension as the shape location to expand.")
print("0 is the lowest dimension, hence (3,) -> (3, 1)")
print(np.r_[
    # Frame a 2-dimensional output, and concatenate expanded elements along the first axis 0.
    # Expand the element shape from (3,) to (3,1) by adding the lowerst dimension to the shape.
    '0,2,0', 
    [1,2,3], 
    [4,5,6]
])

print("--------------------------------------------------------------------------------")
print("Simulating the shape expantion with 0 with np.newaxis.")
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.r_[
    # Frame a 2-dimensional output and concatenate the expanded elements along the 1st axis in the output.
    '0,2', 
    # Simulating the shape expantion with 0, from (3,) to (3, 1), using np.newaxis.
    a[
        ::,
        np.newaxis
    ],
    b[
        ::,
        np.newaxis
    ]
])


--------------------------------------------------------------------------------
Default implicit shape expantion, adding higher dimension(s) to the shape.
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
Simulating the default shape expantion -1 with np.newaxis.
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
Default shape expantion with explicit default -1, adding higher dimension(s) to the shape.
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
Shape expantion with explicit 1, from (3,) into (1,3).
When expanding the shape (3,) into (1,3), default -1 is the same with 1.
For a shape (k, j, i), 2 is the location integer for 'k', 1 for 'j', 0 for 'i'
[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
Shape expantion with explicit 0, adding the lowest dimension as the shape location to e