In [2]:
import numpy as np

# ```arange()``` is interval (step) based

In [3]:
D = 10
np.arange(D-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [4]:
list(range(0, D))[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

## D points between ```[0, length)``` having ```length/D``` steps

```D steps = D intervals``` e.g. "3 steps forward" makes 3 equal intervals ```(0->1, 1->2, 2->3)```. 

In [18]:
D = 8
np.arange(0, np.pi * 2, step=(np.pi * 2)/D) / (np.pi)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75])

### To have same interval (step) with linspace

```linspace``` is **```n``` points creating ```n-1``` intervals (steps)**. To have a ```n=1 interval``` requires ```2 points = n+1```. 

In [21]:
np.linspace(0, 2 * np.pi, D+1) / np.pi

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [34]:
def is_broadcastable(x, y):
    return list((m == n) or (m == 1) or (n == 1) for m, n in zip(x.shape[::-1], y.shape[::-1]))


In [35]:
b = np.random.randn(2,4)
a = np.random.randn(2,15)
print(a.shape)
print(b.shape)
print(all((m == n) or (m == 1) or (n == 1) for m, n in zip(a.shape[::-1], b.shape[::-1])))
print(is_broadcastable(a, b))


(2, 15)
(2, 4)
False
[False, True]
