In [1]:
import numpy as np
print(np.__version__)

1.19.2


In [2]:
print([1, 2, 3][slice(1, 2)])     # This is valid
print([1, 2, 3][1:2])             # Valid
# print([1, 2, 3][(1:2)])         # Inalid
print([1, 2, 3][(slice(1, 2))])   # Inalid

[2]
[2]
[2]


# View or Copy

In [3]:
X = np.arange(36).reshape(3, 3, 4)
print("X is \n{}\n".format(X))
print("X.__array_interface__ \n{}\n".format(X.__array_interface__))

_x =  X[
    0,
    2
]
print("X[0,1] is \n{}\nIs view? {}\n".format(
    _x,
    _x.base is not None
))
print("_x.__array_interface__ is \n{}\n".format(_x.__array_interface__))


Y = np.arange(12).reshape(3, 4)
print("Y is \n{}\n".format(Y))
print("Y.__array_interface__ is \n{}\n".format(Y.__array_interface__))

_y = Y[
    0,
    1
]
print("Y[0,1] is \n{}\nIs view {}\n".format(
    _y,  
    _y.base is not None
))
print(".Y[0,1].__array_interface__ is \n{}\n".format(_y.__array_interface__))

X is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

X.__array_interface__ 
{'data': (93926088450032, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (3, 3, 4), 'version': 3}

X[0,1] is 
[ 8  9 10 11]
Is view? True

_x.__array_interface__ is 
{'data': (93926088450096, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (4,), 'version': 3}

Y is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Y.__array_interface__ is 
{'data': (93926080730672, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (3, 4), 'version': 3}

Y[0,1] is 
1
Is view False

.Y[0,1].__array_interface__ is 
{'data': (93926090314928, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (), 'version': 3, '__ref': array(1)}



In [4]:
X = np.arange(72).reshape(2, 3, 3, 4)
print(X)
_x = X[
    0, # One element in dimension 3 
    1, # One element in dimension 2
    2  # One element in dimension 1
]
print("X[0,1,2] is {} \nview is {} because of what?\n".format(
    _x, _x.base is not None))

_y = X[
    0, # One element in dimension 3 
    [1,2], # One element in dimension 2
    2  # One element in dimension 1
]
print("X[0,(1,2),2] is \n{} \nview is {} because [1,2] triggers advance indexing\n".format(
    _y, _y.base is not None))

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]

  [[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]]


 [[[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]

  [[48 49 50 51]
   [52 53 54 55]
   [56 57 58 59]]

  [[60 61 62 63]
   [64 65 66 67]
   [68 69 70 71]]]]
X[0,1,2] is [20 21 22 23] 
view is True because of what?

X[0,(1,2),2] is 
[[20 21 22 23]
 [32 33 34 35]] 
view is False because [1,2] triggers advance indexing



## Slice indexing is always View

In [5]:
Z = np.arange(36).reshape(3, 3, 4)
print("Z is \n{}\n".format(Z))
print(Z.__array_interface__)
print("Z[0:1, 0:3, 2] is \n{}\n".format(Z[
    0:1, 0:3, 2    # () cannot be used to create slice tuple
]))

a = Z[
    (slice(0, 1), slice(0, 3), 2)
]
print("Z[(slice(1, 2), slice(2, 3), 1)] is \n{}\n".format(a))
print(a.base is not None)
print(a.__array_interface__)

Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

{'data': (93926088450032, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (3, 3, 4), 'version': 3}
Z[0:1, 0:3, 2] is 
[[ 2  6 10]]

Z[(slice(1, 2), slice(2, 3), 1)] is 
[[ 2  6 10]]

True
{'data': (93926088450048, False), 'strides': (96, 32), 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (1, 3), 'version': 3}


## Zero(0) dimension result is copy

In [6]:
X = np.arange(36).reshape(3, 3, 4)
_x = X[1,2]
print("X[1,2] is {} \nview is {} because it is n > 0 dimiension array.\n".format(
    _x, _x.base is not None))

_y = X[1,2,3]
print("X[1,2,3] is {} \nview is {} because it is n = 0 dimiension array.\n".format(
    _y, _y.base is not None))


X[1,2] is [20 21 22 23] 
view is True because it is n > 0 dimiension array.

X[1,2,3] is 23 
view is False because it is n = 0 dimiension array.



# Comma makes a completely different story

**comma** can trigger the a[dvanced indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html#advanced-indexing) which makes a completely different story.


> Warning The definition of advanced indexing means that ***x[(1,2,3),] is
> fundamentally different than x[(1,2,3)]***. The latter is equivalent to
> x[1,2,3] which will trigger basic selection while the former will
> trigger advanced indexing. Be sure to understand why this occurs.


In [7]:
Z = np.arange(12).reshape(3, 4)
print("Z is \n{}\n".format(Z))

print("Comma makes a totally different story")
print("Z[(0,1)] is \n{}\nIs view {}\n".format(
    Z[(0,1)],  # Same with Z[0,1]
    Z[(0,1)].base is not None
))
print(Z[0,1].base)
print("Z[(0,1),] is \n{} \nIs view {}\n".format(
    Z[(0,1),],
    Z[(0,1),].base is not None
))

Z is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Comma makes a totally different story
Z[(0,1)] is 
1
Is view False

None
Z[(0,1),] is 
[[0 1 2 3]
 [4 5 6 7]] 
Is view False



### Difference between tuple indexing and array indexing when advance indexing
[numpy - is Z[[1, 2],[1]] completely same with Z[(1,2),(1)]?
](https://stackoverflow.com/questions/65501075/numpy-is-z1-2-1-completely-same-with-z1-2-1)

In [8]:
Z = np.arange(12).reshape(3, 4)
print("Z is \n{}\n".format(Z))

print("Z[[1, 2],[1]] is \n{} Is view {}\n__array_interface__ {}\n".format(
    Z[
        [1,2],
        [1]
    ],
    Z[[1,2],[1]].base is not None,
    Z[[1,2],[1]].__array_interface__
))

# Comparison with tuple indexing
print("Z[(1,2),(1)] is \n{} Is view {}\n__array_interface__ {}\n".format(
    Z[
        (1,2),
        (1)
    ],
    Z[(1,2),(1)].base is not None,
    Z[(1,2),(1)].__array_interface__
))

Z is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Z[[1, 2],[1]] is 
[5 9] Is view False
__array_interface__ {'data': (93926090328176, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (2,), 'version': 3}

Z[(1,2),(1)] is 
[5 9] Is view False
__array_interface__ {'data': (93926087646496, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (2,), 'version': 3}



---

# Indexing patterns

In [9]:
import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)

# Slice indexing
print(a[
    0:2,
    1:3
])

# Tuple indexing
print(a[
    (0, 2),
    (1, 3)
])

# Array indexing
print(a[
    [0, 2],
    [1, 3]
])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [5 6]]
[ 1 11]
[ 1 11]


### Indexing pattern and copy/view

In [10]:
import numpy as np
a = np.arange(24).reshape(2, 3, 4)
print(a)

b = a[
    (0),
    (0, 2),
    (1)
]
print(b)
print("Copy? {}".format(b.base is None))


indices = (
    [0],
    [0, 2],
    [1]
)
c = a[indices]
print(c)
print("Copy? {}".format(c.base is None))

d = a[
    0,
    0,
    0:1
]
print(d)
print("Copy? {}".format(d.base is None))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[1 9]
Copy? True
[1 9]
Copy? True
[0]
Copy? False


# Tuple indexing

In [18]:
a = np.arange(12).reshape(3, 4)
print(f"a is \n{a}")
print(a[
    (0, 2),
    (1, 3)
])

a is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1 11]


In [21]:
index = (
    (0, 
     2), (1, 
          3)
)
a[index]

array([ 1, 11])

In [22]:
index = (
    (0, 2), 
    (1, 3)
)
print(a[index])
print(a[
    (0, 2),
    (1, 3)
])

[ 1 11]
[ 1 11]


### Using array in tuple indexing is deprecated

In [23]:
index = [
    (0, 2), 
    (1, 3)
]
print(a[index])

[ 1 11]


<ipython-input-23-2fdfff8b4d68>:5: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(a[index])


In [24]:
import numpy as np
Z = np.arange(36).reshape(3, 3, 4)
print("Array Z is \n{}\n".format(Z))

print("Array indices Z[[0,2]] is \n{}\n Is view? {}\n".format(
    Z[
        [0,2]      # Select element 0, and 2 in dimension(n)
    ],
    Z[[0,2]].base is not None
))

print("Tuple indices Z[(0,2)] is \n{}\n Is view? {}\n".format(
    Z[
        (0,2)      # Select Z[0][2]
    ],
    Z[(0,2)].base is not None
))

print("Basic indices Z[0,2] is \n{}\n Is view? {}\n".format(
    Z[
        0,
        2      # Select Z[0][2]
    ],
    Z[0,2].base is not None
))

print("Z[(0,2)] is same with Z[0][2] {}. \nZ[0][2] is view? {}".format(
    Z[0][2],
    (Z[0][2]).base is not None
))


print("Slice indices Z[0:1,2:3] is \n{}\n Is view? {}\n".format(
    Z[
        0:1,
        2:3      # Select Z[0][2]
    ],
    Z[0:1, 2:3].base is not None
))



Array Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

Array indices Z[[0,2]] is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
 Is view? False

Tuple indices Z[(0,2)] is 
[ 8  9 10 11]
 Is view? True

Basic indices Z[0,2] is 
[ 8  9 10 11]
 Is view? True

Z[(0,2)] is same with Z[0][2] [ 8  9 10 11]. 
Z[0][2] is view? True
Slice indices Z[0:1,2:3] is 
[[[ 8  9 10 11]]]
 Is view? True



In [25]:
import numpy as np
Z = np.arange(36).reshape(3, 3, 4)
print("Z is \n{}\n".format(Z))

b =  Z[
    (0,2)      # Select Z[0][2]
]
print("Tuple indexing Z[(0,2)] is \n{}\nIs view? {}\n".format(
    b,
    b.base is not None
))

c = Z[         # Select Z[0][0][1] & Z[0][2][1]
    (0,2),
    (0)
]
print("Tuple indexing Z[(0, 2), (0)] is \n{}\nIs view? {}\n".format(
    c,
    c.base is not None
))

Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

Tuple indexing Z[(0,2)] is 
[ 8  9 10 11]
Is view? True

Tuple indexing Z[(0, 2), (0)] is 
[[ 0  1  2  3]
 [24 25 26 27]]
Is view? False



# Slice indexing

[Basic Slicing and Indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html)

> Basic slicing occurs when obj is a slice object (constructed by start:stop:step notation inside of brackets), an integer, or a tuple of **slice objects and integers**. Ellipsis and newaxis objects can be interspersed with these as well.

In [42]:
Z = np.arange(24).reshape(2, 3, 4)
print("Z is \n{}\n".format(Z))
a = Z[
    0:1,
    0:2,
    1:3
]
print("Slice indexing Z[0:1, 0:1, 1:3] is \n{}\nIs view? {}\n".format(
    a,
    a.base is not None
))

Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Slice indexing Z[0:1, 0:1, 1:3] is 
[[[1 2]
  [5 6]]]
Is view? True



## Diffrence between slice indexing and tuple indexing

In [51]:
Z = np.arange(12).reshape(3, 4)
print("Z is \n{}\n".format(Z))
fmt="""Z[
    0:-1:1,
    (0,2,3)
]
"""

V0=Z[
    # slice "0:3:1" is NOT the same with the tuple indexing (0,1,2,3).
    # Slice indexing applies (0,2,3) to all the rows on 0:3:1.
    # Tuple indexing creates indices from the product((0,1,2), (0,2,3)) which are Z[0][0],Z[1][2],Z[2][3].
    0:3:1,           
    (0,2,3)
]
print(f"{fmt} is \n{V0}\n")
fmt="""Z[
    (0,1,2),
    (0,2,3)
]"""
V1=Z[
    (0,1,2),
    (0,2,3)
]
print(f"{fmt} is \n{V1}")

Z is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Z[
    0:-1:1,
    (0,2,3)
]
 is 
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]

Z[
    (0,1,2),
    (0,2,3)
] is 
[ 0  6 11]


## Syntax
Beware it is **slice objects** but NOT slice expressions. Python does not generate a slice object from ```(0:1)```.

>  a tuple of **slice objects and integers**


```
list(range(10))[(1:2)]
---
  File "<ipython-input-113-69d6c13ca5be>", line 1
    list(range(10))[(1:2)]
                      ^
SyntaxError: invalid syntax


Z = np.arange(36).reshape(3, 3, 4)
print("Z is \n{}\n".format(Z))

a = Z[
    (0:1, 2:3, 1)
]
---
  File "<ipython-input-53-26b1604433cd>", line 5
    (0:1, 2:3, 1)
      ^
SyntaxError: invalid syntax
```

### numpy ```s_ ``` utility

```s_``` function can take slice expressions and integer expressions and returns **a tuple of slice objects and integers** .

In [27]:
from numpy import s_
Z = np.arange(36).reshape(3, 3, 4)
print("Z is \n{}\n".format(Z))

print(s_[0:1, 2:3, 1])
print(Z[s_[0:1, 2:3, 1]])

Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

(slice(0, 1, None), slice(2, 3, None), 1)
[[9]]


## Selecting multiple slices
It is not possible to select multiple blocks within a dimension with mutliple slices expressions.

```
Z = np.arange(12).reshape(3, 4)
print("Z is \n{}\n".format(Z))

Z[
    1,
    [0:1, 1:2, 3]
]
---
  File "<ipython-input-118-550cf22b0e60>", line 6
    [0:1, 1:2, 3]
      ^
SyntaxError: invalid syntax
```

A tuple of slice objects and integers cannot be used within a dimension, either.
```
from numpy import s_
Z = np.arange(12).reshape(3, 4)
print("Z is \n{}\n".format(Z))

Z[
    1,
    [slice(0,1), slice(1,2), 3]
]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-117-d0b88945e9b3> in <module>
      3 print("Z is \n{}\n".format(Z))
      4 
----> 5 Z[
      6     1,
      7     [slice(0,1), slice(1,2), 3]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

You need to manually select regions and concatenate them.

In [28]:
import numpy as np
def xslice(x, slices):
    """Extract slices from array-like by interating over a list of slice objects
    Args:
        x: array-like
        slices: slice or tuple of slice objects
    """
    if isinstance(slices, tuple):
        if isinstance(x, np.ndarray):
            return np.concatenate([x[_slice] for _slice in slices])
        else:
            return sum((x[s] if isinstance(s, slice) else [x[s]] for s in slices), [])        
    elif isinstance(slices, slice):
        return x[slices]
    else:
        return [x[slices]]


Z = np.arange(12).reshape(3, 4)
print("Z is \n{}\n".format(Z))
print("Z[0,xslice(list(range(Z.shape[1])), s_[0:2, 3]] is\n{}\n".format(
    Z[
        0,
        xslice(list(range(Z.shape[1])), s_[0:2, 3])
    ]
))

Z[
    [[0]],
    [[0, 1, 3]]
] = 100
fmt = """Z[
    [[0]],
    [[0, 1, 3]]
] = 100
"""
print(f"{fmt} is \n{Z}")

Z is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Z[0,xslice(list(range(Z.shape[1])), s_[0:2, 3]] is
[0 1 3]

Z[
    [[0]],
    [[0, 1, 3]]
] = 100
 is 
[[100 100   2 100]
 [  4   5   6   7]
 [  8   9  10  11]]


In [29]:
x = list(range(10))
slices = (slice(0, 0, None), slice(0, 2, None))
print([s for s in slices])
g = (x[s] for s in slices)
a = []
for e in g:
    b = np.append(a, e).astype(int)
    print(b)
    
#print(np.sum([x[s] for s in slices], start=np.empty(1)))

[slice(0, 0, None), slice(0, 2, None)]
[]
[0 1]


In [30]:
x = np.arange(10)
slices = (slice(0, 0, None), slice(0, 2, None))
print([s for s in slices])
g = (x[s] for s in slices)
a = []
for e in g:
    b = np.append(a, e).astype(int)
    print(b)
    
#print(np.sum([x[s] for s in slices], start=np.empty(1)))

[slice(0, 0, None), slice(0, 2, None)]
[]
[0 1]


In [31]:
#X = np.arange(10)
X = list(range(10))  # [i for i in range(10)]
print(X)
indices = s_[0:2, 4:5]

print(list(s for s in indices))
print((X[s] for s in indices))
print(list(X[s] for s in indices))


xslice(list(range(10)), indices)
xslice(X, indices)

#sum([list(range(10))[s] for s in indices], [])




[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[slice(0, 2, None), slice(4, 5, None)]
<generator object <genexpr> at 0x7fd0392a8cf0>
[[0, 1], [4]]


[0, 1, 4]

# Array indexing

In [32]:
Z = np.arange(12).reshape(3, 4)
print("Z is \n{}\n".format(Z))
print("Z[[1, 2],[1]] is \n{} Is view {}\n".format(
    Z[
        [1,2],
        [1]
    ],
    Z[[1,2],[1]].base is not None
))

# Comparision with slice indexing
print("Z[(1,2),(1)] is \n{} Is view {}\n".format(
    Z[
        (1,2),
        (1)
    ],
    Z[(1,2),(1)].base is not None
))

# Comma makes a difference
print("Z[(0,1)] is \n{}\nIs view {}\n".format(
    Z[(0,1)],  # Same with Z[0,1]
    Z[(0,1)].base is not None
))

print("Z[(0,1),] is \n{} \nIs view {}\n".format(
    Z[(0,1),],
    Z[(0,1),].base is not None
))

Z is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Z[[1, 2],[1]] is 
[5 9] Is view False

Z[(1,2),(1)] is 
[5 9] Is view False

Z[(0,1)] is 
1
Is view False

Z[(0,1),] is 
[[0 1 2 3]
 [4 5 6 7]] 
Is view False



In [33]:
Z = np.arange(36).reshape(3, 3, 4)
print("Z is \n{}\n".format(Z))
a = Z[
    [0],
    [1],
    [0,1,2]
]

print("Array indexing Z[[0],[1],[0,1,2]] is \n{}\nIs view? {}\n".format(
    a,
    a.base is not None
))

Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

Array indexing Z[[0],[1],[0,1,2]] is 
[4 5 6]
Is view? False



In [34]:
Z = np.arange(36).reshape(3, 3, 4)
print("Z is \n{}\n".format(Z))

indices= np.array([[0, 2], [1, 2]])
print("indices is \n{}\n".format(indices))

b = Z[indices]
print("Z[np.array([[0, 2], [1, 2]])] is \n{} Is view? {}\n".format(
    b,
    b.base is not None
))


i = [[0, 2], [1, 2]]
c = Z[i] 
print("Z[i] with i = [[0, 2], [1, 2]] is \n{} Is view? {}\n".format(
    c,
    c.base is not None
))

d = Z[
    np.array([0, 2]), np.array([1, 2])
]
print("Z[np.array([0, 2]), np.array([1, 2])] is \n{} Is view? {}\n".format(
    d,
    d.base is not None
))


Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

indices is 
[[0 2]
 [1 2]]

Z[np.array([[0, 2], [1, 2]])] is 
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]]


 [[[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]

  [[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]]] Is view? False

Z[i] with i = [[0, 2], [1, 2]] is 
[[ 4  5  6  7]
 [32 33 34 35]] Is view? False

Z[np.array([0, 2]), np.array([1, 2])] is 
[[ 4  5  6  7]
 [32 33 34 35]] Is view? False



<ipython-input-34-730f8014a9ec>:15: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  c = Z[i]


## numpy.r_[] 
```np.r_[]``` can create an array from multiple slices or arrays.

In [35]:
Z = np.arange(12).reshape(3, 4)
print("np.r_[0:2, 3:4] is {}".format(np.r_[0:2, 3:4]))
Z[
    0,
    np.r_[0:2, 3:4]
]

np.r_[0:2, 3:4] is [0 1 3]


array([0, 1, 3])

In [10]:
import numpy as np
a = np.arange(12).reshape(3, 4)
x = 1
a[
    ::,
    slice(x, 2*x)
] = a[
    ::,
    slice(x, 2*x)
] * 2
a

array([[ 0,  2,  2,  3],
       [ 4, 10,  6,  7],
       [ 8, 18, 10, 11]])

# Matrix indexing
Same with Array Indexing. Instead of intenger:
```
Z[
  [0, 1, 2],
  [1, 2, 3]
]
```
matrices is the index elements, but the behavior is the same.
```
Z[
  [[0, 1, 2],
   [0, 0, 1]],
  [[0, 1, 0],
   [1, 2, 0]]
]
```

<img src='images/matrix_indexing.png' width=650, align="left"/>

In [36]:
Z = np.arange(36).reshape(3, 3, 4)
print("Z is \n{}\n".format(Z))

axis3_indices = [
    [0, 1, 2, 0],
    [2, 1, 0, 2]
]
axis2_indices = [
    [2, 1, 0, 2],
    [0, 1, 0, 1]
]
axis1_indices = [
    [3, 2, 1, 0],
    [2, 1, 2, 1]
]

Z[
    axis3_indices, 
    axis2_indices, 
    axis1_indices
]

Z is 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]



array([[11, 18, 25,  8],
       [26, 17,  2, 29]])

In [37]:
Z = np.arange(12).reshape(3, 4)
print("Z is \n{}\n".format(Z))

axis_2_indices_01 = np.array([[0, 1],
                              [2, 1]], dtype=np.intp)
axis_2_indices_02 = np.array([[2, 1],
                              [0, 2]], dtype=np.intp)
indices = np.array([
    [ axis_2_indices_01, axis_2_indices_02 ]   # dimension 2 selector
    # You can add dimension 1 indices 
])
print(Z[indices])

print(Z[
    axis_2_indices_01,
    axis_2_indices_02  # Use axis_2_indices_02 as axis_1_indices
])
print(Z[
    [ axis_2_indices_01 ],
    [ np.array([[2, 1],
                [0, 2]], dtype=np.intp)]
])

Z is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[[[ 0  1  2  3]
    [ 4  5  6  7]]

   [[ 8  9 10 11]
    [ 4  5  6  7]]]


  [[[ 8  9 10 11]
    [ 4  5  6  7]]

   [[ 0  1  2  3]
    [ 8  9 10 11]]]]]
[[2 5]
 [8 6]]
[[[2 5]
  [8 6]]]


In [38]:
Z = np.arange(12).reshape(3, 4)
print("Z is \n{}\n".format(Z))

rows = [
    [0, 1],
    [2, 1]
]
cols = [
    [2, 1],
    [0, 2]
]

print(Z[
    rows,
    ::
])
print(Z[
    ::,
    cols
])
print(Z[
    rows,
    cols
])


indices_01 = np.array([[0, 1],
                       [2, 1]], dtype=np.intp)
indices_02 = np.array([[2, 1],
                       [0, 2]], dtype=np.intp)

print(Z[
    indices_01,
    indices_02
])
Z[
    [[0, 1], 
     [2, 1]],
    [[2, 1], 
     [0, 2]]
]

Z is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 4  5  6  7]]]
[[[ 2  1]
  [ 0  2]]

 [[ 6  5]
  [ 4  6]]

 [[10  9]
  [ 8 10]]]
[[2 5]
 [8 6]]
[[2 5]
 [8 6]]


array([[2, 5],
       [8, 6]])

# np.choose()

* [numpy.choose(a, choices, out=None, mode='raise')](https://numpy.org/doc/stable/reference/generated/numpy.choose.html#numpy.choose)

```
np.choose(a,c) == np.array([c[a[I]][I] for I in ndi.ndindex(a.shape)])
```

In [39]:
import numpy as np

print("--------------------------------------------------------------------------------")
print("Index array 'a' and array of choice(s).")
print("--------------------------------------------------------------------------------")
a = np.array([4, 3, 2, 1])
print("'a' is {} shape is {}\n".format(
    a, a.shape
))
    
c = np.arange(60).reshape((5, 3, 4))
_choice = c[0]
print("An example choice is \n{} \nshape is {}\n".format(
    _choice,
    _choice.shape
))

print("--------------------------------------------------------------------------------")
print("np.choose() broadcasts 'a' and 'choice' to match (here only on a)")
print("--------------------------------------------------------------------------------")
a = np.vstack([
    np.array(a) for i in range(_choice.shape[0])
])
print("Broadcast shape of 'a' is {}\n 'a' is \n{}\n.".format(a.shape, a))


print("--------------------------------------------------------------------------------")
print("Simulate np.choose() behavior of choosing elements c[a[I]][I]]]:")
print("np.array([ c[a[I]][I] for I in np.lib.index_tricks.ndindex(a.shape) ])")
print("--------------------------------------------------------------------------------")
result = np.array([]).astype(int)
for I in np.lib.index_tricks.ndindex(a.shape):
    print("Selecting the element {} at c[{},{}]".format(
        c[a[I]][I].astype(int), a[I], I
    ))
    result = np.concatenate([result, [c[a[I]][I].astype(int)]])
    print("chosen items: {}".format(result))
    
print("\nResult is \n{}\n".format(
    result.reshape(a.shape)
))
    
print("--------------------------------------------------------------------------------")
print("Run np.choose(a, c):")
print("--------------------------------------------------------------------------------")
print(np.choose(a, c))

--------------------------------------------------------------------------------
Index array 'a' and array of choice(s).
--------------------------------------------------------------------------------
'a' is [4 3 2 1] shape is (4,)

An example choice is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
shape is (3, 4)

--------------------------------------------------------------------------------
np.choose() broadcasts 'a' and 'choice' to match (here only on a)
--------------------------------------------------------------------------------
Broadcast shape of 'a' is (3, 4)
 'a' is 
[[4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]]
.
--------------------------------------------------------------------------------
Simulate np.choose() behavior of choosing elements c[a[I]][I]]]:
np.array([ c[a[I]][I] for I in np.lib.index_tricks.ndindex(a.shape) ])
--------------------------------------------------------------------------------
Selecting the element 48 at c[4,(0, 0)]
chosen items: [48]
Selecting the ele

In [40]:
list(np.lib.index_tricks.ndindex(a.shape))

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3)]